import tsPlugin from '@typescript-eslint/eslint-plugin';
import tsParser from '@typescript-eslint/parser';

export default [
  {
    files: ['packages/**/*.ts', 'packages/**/*.tsx'],
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      // Suites are exempt from the size and complexity budgets: a thorough test file is
      // long by design, and a table-driven case is nested by design. The `.tsx` and
      // `__tests__` forms were missing, so component suites were being held to the
      // production budgets while their `.ts` siblings were not.
      '**/*.test.ts',
      '**/*.test.tsx',
      '**/*.spec.ts',
      '**/*.spec.tsx',
      '**/__tests__/**',
      // Generated from the Paper design file. Its size is a property of the design - 79
      // icon glyphs - not a decision anyone made in this repo, and it is regenerated by
      // `bun run paper:icons` rather than edited.
      '**/*.generated.ts',
    ],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: 2022,
        sourceType: 'module',
      },
    },
    plugins: {
      '@typescript-eslint': tsPlugin,
    },
    rules: {
      complexity: ['error', { max: 10 }],
      'max-lines-per-function': ['error', { max: 50, skipBlankLines: true, skipComments: true }],
      'max-lines': ['error', { max: 300, skipBlankLines: true, skipComments: true }],
      'max-depth': ['error', { max: 5 }],
      'max-nested-callbacks': ['error', { max: 3 }],
      'max-params': ['error', { max: 4 }],
      '@typescript-eslint/no-explicit-any': 'warn',
    },
  },
];
