import { z } from "zod"

// Closed table of Todo 3 producer contract routes (plus task plans, approval policy and orgs) the renderer may invoke through main (see desktop remote-contracts.ts).
export type ContractOp = { method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE"; path: string; slow?: boolean; text?: boolean }
export const CONTRACT_OPS = {
  "code.attempts": { method: "GET", path: "/code/sessions/{session}/attempts" },
  "code.attempts.retry": { method: "POST", path: "/code/sessions/{session}/attempts", slow: true },
  "code.attempts.choose": { method: "POST", path: "/code/sessions/{session}/attempts/{attempt}/choose" },
  "code.comments": { method: "GET", path: "/code/sessions/{session}/diff/comments" },
  "code.comments.add": { method: "POST", path: "/code/sessions/{session}/diff/comments" },
  "code.comments.remove": { method: "DELETE", path: "/code/sessions/{session}/diff/comments/{comment}" },
  "code.diff.resolve": { method: "POST", path: "/code/sessions/{session}/diff/resolve", slow: true },
  "code.pr.open": { method: "POST", path: "/code/sessions/{session}/pull-request", slow: true },
  "code.pr.review": { method: "POST", path: "/code/sessions/{session}/pull-request/review" },
  "code.pr.reviewers": { method: "GET", path: "/code/sessions/{session}/pull-request/reviewers" },
  "code.pr.reviewers.request": { method: "POST", path: "/code/sessions/{session}/pull-request/reviewers" },
  "code.grant": { method: "POST", path: "/code/sessions/{session}/permissions/session-grant" },
  "code.grant.revoke": { method: "DELETE", path: "/code/sessions/{session}/permissions/session-grant" },
  "code.runtimes": { method: "GET", path: "/code/runtimes" },
  "code.runtime.lifecycle": { method: "POST", path: "/code/runtimes/{runtime}/lifecycle", slow: true },
  "code.runtime.remove": { method: "DELETE", path: "/code/runtimes/{runtime}", slow: true },
  "code.secrets": { method: "GET", path: "/code/runtimes/{runtime}/secrets" },
  "code.secrets.put": { method: "PUT", path: "/code/runtimes/{runtime}/secrets/{secret}" },
  "code.secrets.remove": { method: "DELETE", path: "/code/runtimes/{runtime}/secrets/{secret}" },
  "code.egress": { method: "GET", path: "/code/runtimes/{runtime}/egress" },
  "code.egress.put": { method: "PUT", path: "/code/runtimes/{runtime}/egress", slow: true },
  "code.repository.put": { method: "PUT", path: "/code/repositories/{owner}/{repo}" },
  "code.repository.remove": { method: "DELETE", path: "/code/repositories/{owner}/{repo}" },
  "bot.status": { method: "PATCH", path: "/mascots/{bot}" },
  "bot.task.pause": { method: "POST", path: "/mascots/{bot}/tasks/{task}/pause" },
  "bot.task.resume": { method: "POST", path: "/mascots/{bot}/tasks/{task}/resume" },
  "bot.task.retry": { method: "POST", path: "/mascots/{bot}/tasks/{task}/retry" },
  "bot.takeover": { method: "POST", path: "/mascots/{bot}/computer/takeover" },
  "bot.drafts": { method: "GET", path: "/mascots/{bot}/tasks/{task}/drafts" },
  "bot.credentials.requests": { method: "GET", path: "/mascots/{bot}/tasks/{task}/credentials" },
  "bot.draft.send": { method: "POST", path: "/mascots/{bot}/tasks/{task}/drafts/{draft}/send" },
  "bot.draft.cancel": { method: "POST", path: "/mascots/{bot}/tasks/{task}/drafts/{draft}/cancel" },
  "bot.credentials": { method: "POST", path: "/mascots/{bot}/tasks/{task}/credentials" },
  "bot.approval.transfer": { method: "POST", path: "/bot/approvals/{approval}/transfer" },
  "plans.list": { method: "GET", path: "/task-plans" },
  "plans.create": { method: "POST", path: "/task-plans" },
  "plans.get": { method: "GET", path: "/task-plans/{plan}" },
  "plans.remove": { method: "DELETE", path: "/task-plans/{plan}" },
  "plans.step.add": { method: "POST", path: "/task-plans/{plan}/steps" },
  "plans.step.update": { method: "PATCH", path: "/task-plans/{plan}/steps/{step}" },
  "plans.step.remove": { method: "DELETE", path: "/task-plans/{plan}/steps/{step}" },
  "policy.get": { method: "GET", path: "/approval-policy" },
  "policy.put": { method: "PUT", path: "/approval-policy" },
  "policy.diff": { method: "GET", path: "/approval-policy/diff" },
  "orgs.list": { method: "GET", path: "/orgs" },
  // Todo 6b app screens: owner-scoped trunk routes, same closed-table rules.
  "app.channel": { method: "GET", path: "/channels/{channel}" },
  "app.channel.messages": { method: "GET", path: "/channels/{channel}/messages" },
  "app.channel.send": { method: "POST", path: "/channels/{channel}/messages", slow: true },
  "app.share.preview": { method: "GET", path: "/bot/shares/{token}" },
  "app.share.clone": { method: "POST", path: "/bot/shares/{token}/clone" },
  "app.computer": { method: "GET", path: "/mascots/{bot}/computer" },
  "app.computer.lifecycle": { method: "POST", path: "/mascots/{bot}/computer/lifecycle", slow: true },
  "app.automations": { method: "GET", path: "/code/automations" },
  "app.automations.create": { method: "POST", path: "/code/automations" },
  "app.automations.runs": { method: "GET", path: "/code/automations/runs" },
  "app.automation": { method: "GET", path: "/code/automations/{automation}" },
  "app.automation.update": { method: "PATCH", path: "/code/automations/{automation}" },
  "app.automation.remove": { method: "DELETE", path: "/code/automations/{automation}" },
  "app.automation.run": { method: "POST", path: "/code/automations/{automation}/run", slow: true },
  "app.github.start": { method: "POST", path: "/code/github/oauth/start" },
  "app.instance": { method: "GET", path: "/instance" },
  "app.providers": { method: "GET", path: "/providers" },
  "app.provider": { method: "GET", path: "/providers/{provider}" },
  "app.models": { method: "GET", path: "/models" },
  "app.registry.models": { method: "GET", path: "/registry/models?limit=200" },
  "app.conversations": { method: "GET", path: "/conversations" },
  "app.conversation.messages": { method: "GET", path: "/conversations/{conversation}/messages" },
  "app.permissions": { method: "GET", path: "/conversations/{conversation}/permissions" },
  "app.permission.decide": { method: "POST", path: "/conversations/{conversation}/permissions/{prompt}" },
  "app.library": { method: "GET", path: "/library" },
  "app.note.create": { method: "POST", path: "/library/notes" },
  "app.file": { method: "GET", path: "/library/{file}" },
  "app.file.rename": { method: "PATCH", path: "/library/{file}" },
  "app.file.content": { method: "GET", path: "/library/{file}/content", text: true },
  "app.file.remove": { method: "DELETE", path: "/library/{file}" },
  "app.scheduled": { method: "GET", path: "/scheduled-tasks" },
  "app.scheduled.create": { method: "POST", path: "/scheduled-tasks" },
  "app.scheduled.get": { method: "GET", path: "/scheduled-tasks/{scheduled}" },
  "app.scheduled.update": { method: "PATCH", path: "/scheduled-tasks/{scheduled}" },
  "app.scheduled.remove": { method: "DELETE", path: "/scheduled-tasks/{scheduled}" },
  "app.scheduled.run": { method: "POST", path: "/scheduled-tasks/{scheduled}/run", slow: true },
  "app.skills": { method: "GET", path: "/skills?surface=chat" },
  "app.skill.create": { method: "POST", path: "/skills" },
  "app.skill": { method: "GET", path: "/skills/{skill}" },
  "app.skill.update": { method: "PATCH", path: "/skills/{skill}" },
  "app.skill.remove": { method: "DELETE", path: "/skills/{skill}" },
  "app.skill.enable": { method: "PUT", path: "/skills/{skill}/enable?surface=chat" },
  "app.integrations": { method: "GET", path: "/integrations" },
  "app.mcp.add": { method: "POST", path: "/integrations/mcp", slow: true },
  "app.devices": { method: "GET", path: "/me/devices" },
  "app.me": { method: "GET", path: "/me" },
  "app.mcp.remove": { method: "DELETE", path: "/integrations/mcp/{mcp}" },
} as const satisfies Record<string, ContractOp>
export type ContractOpName = keyof typeof CONTRACT_OPS
export const ContractCall = z.object({
  epoch: z.string().min(1).max(256),
  op: z.enum(Object.keys(CONTRACT_OPS) as [ContractOpName, ...ContractOpName[]]),
  params: z.record(z.string(), z.string().max(200)).default({}),
  body: z.record(z.string(), z.unknown()).optional(),
}).strict()
export type ContractCall = z.input<typeof ContractCall>
export type ContractResult = { status: number; data: unknown }
