import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';

const root = process.cwd();
const { chromium } = await import(path.join(root, 'node_modules/playwright/index.mjs'));
const [out] = process.argv.slice(2);
assert(out);
const browser = await chromium.connectOverCDP('http://127.0.0.1:19444');
const page = browser.contexts()[0].pages().find(p => p.url().startsWith('cortex://app/'));
assert(page);
const errors = [];
page.on('pageerror', e => errors.push(e.message));
const ssh = command => execFileSync('ssh', ['-o', 'BatchMode=yes', 'mac-live', command], { encoding: 'utf8' }).trim();
const wid = ssh(`swift -e 'import CoreGraphics; for w in CGWindowListCopyWindowInfo([.optionOnScreenOnly], kCGNullWindowID) as! [[String: Any]] where w["kCGWindowOwnerName"] as? String == "Cortex" && w["kCGWindowLayer"] as? Int == 0 { print(w["kCGWindowNumber"] as! Int); break }' 2>/dev/null`);
assert(/^\d+$/.test(wid));
fs.mkdirSync(out, { recursive: true });
const captures = [];
const capture = async name => {
  const r = await fetch(`http://127.0.0.1:19445/${wid}`, { method: 'POST' });
  assert(r.ok);
  fs.writeFileSync(path.join(out, `${name}.png`), Buffer.from(await r.arrayBuffer()));
  captures.push({ name, url: page.url() });
};
const show = async hash => {
  await page.goto(`cortex://app/index.html#/${hash}`);
  await page.waitForFunction(() => document.querySelector('main.content')?.textContent.trim());
  await page.evaluate(() => document.fonts.ready);
  await page.waitForTimeout(450);
};
const call = (url, method = 'GET', body) => page.evaluate(async ({ url, method, body }) => {
  const r = await window.__bridgeFetch(`cortex://local${url}`, { method, headers: { 'content-type': 'application/json' }, body: body === undefined ? undefined : JSON.stringify(body) });
  if (!r.ok) throw new Error(`Fixture setup failed: ${r.status}`);
  return r.status === 204 ? null : r.json();
}, { url, method, body });
await show('home');
await page.evaluate(() => localStorage.setItem('cortex.locale', 'en'));
await page.reload();
await page.emulateMedia({ reducedMotion: 'reduce' });
ssh('osascript -e \'tell application "System Events" to tell process "Cortex" to set size of window 1 to {960, 640}\'');
await page.waitForFunction(() => innerWidth === 960 && innerHeight === 640);
await call('/api/providers/fake/key', 'PUT', { key: 'sk-test-native-coverage' });
for (const theme of ['light', 'dark']) {
  ssh(`osascript -e 'tell application "System Events" to tell appearance preferences to set dark mode to ${theme === 'dark'}'`);
  await show(`home?theme=${theme}`);
  await page.reload();
  await page.locator('.home h1').waitFor();
  assert.equal(await page.locator('html').getAttribute('data-theme'), theme);
  assert(await page.locator('.home h1').evaluate(el => getComputedStyle(el).color === getComputedStyle(document.body).color));
  assert.equal(await page.locator('.home .composer').evaluate(el => getComputedStyle(el).transitionDuration), '0s');
  assert.equal(await page.locator('.home .composer').evaluate(el => getComputedStyle(el).animationDuration), '0.001s');
  await capture(`home-reduced-${theme}`);
  await show(`work-home?theme=${theme}&shot&v=board`);
  const pane = page.locator('.page');
  assert(await pane.evaluate(el => el.scrollWidth <= el.clientWidth + 1));
  const positions = await page.locator('.travail-col').evaluateAll(els => els.map(el => Math.round(el.getBoundingClientRect().x)));
  assert.equal(new Set(positions).size, 2);
  await capture(`work-board-top-${theme}`);
  await page.getByRole('region', { name: 'Done', exact: true }).scrollIntoViewIfNeeded();
  assert(await pane.evaluate(el => el.scrollLeft === 0));
  await capture(`work-board-bottom-${theme}`);

  await show(`work-task?theme=${theme}&shot&v=done`);
  await page.waitForFunction(() => document.querySelector('.sidebar .row .mascot[data-state="done"]'));
  await capture(`work-done-activity-${theme}`);
  await show(`code-settings?theme=${theme}&shot&v=instructions`);
  assert.equal(await page.locator('.code-lead code').evaluate(el => getComputedStyle(el).fontSize), '11px');
  await capture(`code-instructions-${theme}`);

  const chat = await call('/api/sessions', 'POST', { kind: 'chat', model: { providerID: 'fake', modelID: 'text-only' } });
  await show(`chat?theme=${theme}&id=${chat.id}`);
  await page.getByTestId('composer-input').fill('Keep this image and draft');
  await page.getByTestId('model-trigger').click();
  await page.getByTestId('model-option').filter({ hasText: 'Plain Text' }).click();
  await page.getByTestId('attach-input').setInputFiles({ name: 'dot.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==', 'base64') });
  await page.locator('.chat-att-img').waitFor();
  const clockTime = Date.now();
  await page.clock.install({ time: clockTime });
  await page.clock.pauseAt(clockTime + 1000);
  await page.getByTestId('composer-send').click();
  await page.getByText('This model can’t read images.', { exact: true }).first().waitFor();
  for (const control of [page.getByTestId('composer-input'), page.getByTestId('model-trigger'), page.getByTestId('composer-send'), page.locator('.chat-att-x')]) await control.click({ trial: true, timeout: 1500 });
  await page.getByTestId('model-trigger').click({ timeout: 1500 });
  await page.clock.runFor(100);
  await page.getByTestId('model-option').filter({ hasText: 'Reasoner Large' }).click({ timeout: 1500 });
  await page.clock.runFor(100);
  assert(await page.getByText('This model can’t read images.', { exact: true }).first().isVisible());
  assert.equal(await page.getByTestId('composer-input').inputValue(), 'Keep this image and draft');
  await capture(`chat-refused-${theme}`);
  ssh('osascript -e \'tell application "System Events" to tell process "Cortex" to set size of window 1 to {1024, 685}\'');
  await page.clock.runFor(100);
  await page.waitForFunction(() => innerWidth === 1024 && innerHeight === 685, null, { polling: 50 });
  for (const control of [page.getByTestId('composer-input'), page.getByTestId('model-trigger'), page.getByTestId('composer-send'), page.locator('.chat-att-x')]) await control.click({ trial: true, timeout: 1500 });
  await capture(`chat-refused-1024-${theme}`);
  ssh('osascript -e \'tell application "System Events" to tell process "Cortex" to set size of window 1 to {960, 640}\'');
  await page.clock.resume();
  await page.waitForFunction(() => innerWidth === 960 && innerHeight === 640);

  const code = await call('/api/sessions', 'POST', { kind: 'code', directory: '/tmp', model: { providerID: 'anthropic', modelID: 'claude-x' } });
  await show(`code-session?theme=${theme}&id=${code.id}`);
  await page.getByTestId('code-composer-input').fill('Keep this Code draft');
  await page.getByTestId('composer-send').click();
  await page.getByText('Message not sent', { exact: true }).first().waitFor();
  for (const control of [page.getByTestId('code-composer-input'), page.getByTestId('composer-send'), page.locator('.split-l .composer .model')]) await control.click({ trial: true, timeout: 1500 });
  await capture(`code-refused-${theme}`);

  const bot = await call('/api/bots', 'POST', { name: 'Recovery bot', model: { providerID: 'anthropic', modelID: 'claude-x' } });
  const task = await call(`/api/bots/${bot.id}/sessions`, 'POST', { title: 'Refused task stays to do' });
  await show(`work-task?theme=${theme}&id=${task.id}`);
  await page.getByTestId('composer-input').fill('Keep this Work draft');
  await page.getByTestId('composer-send').click();
  await page.getByText('Couldn’t send that. Try again.', { exact: true }).first().waitFor();
  for (const control of await page.locator('.composer').locator('input, button').all()) await control.click({ trial: true, timeout: 1500 });
  assert.equal(await page.locator('.content-top .badge').innerText(), 'To do');
  await capture(`work-refused-${theme}`);
  await page.reload();
  await page.waitForFunction(() => document.querySelector('.content-top .badge')?.textContent === 'To do');
  assert.deepEqual(await call(`/api/sessions/${task.id}/messages`), []);
}
assert.deepEqual(errors, []);
fs.writeFileSync(path.join(out, 'manifest.json'), JSON.stringify({ appSha256: ssh('shasum -a 256 /Applications/Cortex.app/Contents/Resources/app.asar').split(/\s/)[0], nativeWindowID: Number(wid), captures, errors }, null, 2) + '\n');
await browser.close();
console.log(`Verified ${captures.length} native correction captures`);
