// Prepared only: future Activity package, independent source approval, coordinator-owned execution.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { protocol, key, prompt, answer, reasoning, steps } from './terminal-state-native-backend.mjs';
const [out, root, asar, revision, membersFile] = process.argv.slice(2), repo = fs.realpathSync(process.cwd());
assert(process.argv.length === 7 && /^\/tmp\/opencode\/activity-native-[\w.-]+$/.test(out ?? '') && /^\/(?:private\/)?tmp\/opencode\/desktop-terminal-state-activity-[\w.-]+$/.test(root ?? '') && /^[a-f0-9]{64}$/.test(asar ?? '') && /^[a-f0-9]{40}$/.test(revision ?? '') && path.isAbsolute(membersFile ?? ''), 'Usage: node activity-native.mjs <fresh-output> <fresh-mac-root> <asar-sha256> <revision> <members.json>');
assert(!['96df66c', 'f82a648'].some(pin => revision.startsWith(pin)), 'Future Activity package required'); assert(!fs.existsSync(out) && out !== repo && !out.startsWith(`${repo}/`)); fs.mkdirSync(out);
const sha = value => createHash('sha256').update(value).digest('hex'), quote = value => `'${value.replaceAll("'", "'\\''")}'`;
const helpers = { 'terminal-state-native-backend.mjs': 'd22fcbe2287a7898452778ea58d665f0742f4a1d4d580ec7c237dc10cfc70d4d', 'launch-terminal-state-native.py': '4aec6651e6178bf890a299551497514f5159342a8f94db8972515c000fc10257', 'cleanup-terminal-state-native.py': 'c46f218f17bcda2ba031fe8f2959f9f8e18dda379a7edcd076b01be0c881c08a' };
const report = { status: 'running', revision, asar, startedAt: new Date().toISOString(), invocation: { argv: process.argv.slice(1), cwd: repo, nodeVersion: process.version }, budget: { flowMs: 120000, captures: 4, nativeSamples: 8, originalBytes: 8388608, totalBytes: 33554432, manifestBytes: 409600, ipcCalls: 180 }, capturesRequested: 0, captures: [], nativeChecks: [], checks: [], calls: [], errors: [], cleanup: {} };
const save = () => { const text = JSON.stringify(report, null, 2) + '\n'; assert(Buffer.byteLength(text) <= report.budget.manifestBytes); fs.writeFileSync(path.join(out, 'manifest.json'), text); };
const diagnostic = error => String(error?.stack ?? error).replaceAll(key, '[redacted-test-key]').replace(/\bBearer\s+[^\s"'`,]+/gi, 'Bearer [redacted]').replace(/https?:\/\/[^\s"'<>]+/g, '[network-url]').slice(0, 1200);
const ssh = command => execFileSync('ssh', ['-o', 'BatchMode=yes', '-o', 'ConnectTimeout=8', 'mac-live', command], { encoding: 'utf8', timeout: 15000, maxBuffer: 1048576, stdio: ['pipe', 'pipe', 'pipe'] }).trim();
const appearance = () => ssh(`/usr/bin/osascript -e 'tell application "System Events" to tell appearance preferences to get dark mode'`);
const setAppearance = dark => assert.equal(ssh(`/usr/bin/osascript -e 'tell application "System Events" to tell appearance preferences to set dark mode to ${dark}' -e 'tell application "System Events" to tell appearance preferences to get dark mode'`), String(dark));
const backend = endpoint => { assert(['health', 'receipt'].includes(endpoint)); return JSON.parse(ssh(`/usr/bin/curl --fail --silent --show-error --max-time 5 http://127.0.0.1:9456/${endpoint}`)); };
const receipt = count => {
  const r = backend('receipt'); report.backendReceipt = r; save(); for (const field of ['runID', 'root', 'pid', 'scriptSHA256']) assert.equal(r[field], report.backend[field]); assert.equal(r.counts.errors, 0); assert.deepEqual(r.failures, []); assert.equal(r.requests.length, count); assert(count <= 3);
  assert.deepEqual(r.requests, steps.slice(0, count).map(([theme, turn]) => ({ theme, turn, userTexts: (turn === 'recover' ? ['fail', 'recover'] : ['fail']).map(t => prompt(theme, t)), replayAnswers: [], modelExact: true, authorizationExact: true, workingDirectoryExact: true, toolsAbsent: true, reasoningOptionFields: [], httpStatus: turn === 'fail' ? 401 : 200, outputFields: turn === 'fail' ? [] : ['reasoning_content', 'content'], ...(turn === 'recover' ? { reasoningText: reasoning(theme), answerText: answer(theme) } : {}), completed: true })));
};
const installed = () => { const value = JSON.parse(ssh(`/usr/bin/python3 ${quote(`${root}/launch-terminal-state-native.py`)} --inspect ${quote(root)} ${asar} ${revision}`)); assert.equal(value.membersSHA256, report.membersSHA256); assert.equal(value.membersVerified, report.memberCount); assert.equal(value.inspectorSHA256, helpers['launch-terminal-state-native.py']); return value; };
const swift = 'import Foundation; import AppKit; import CoreGraphics; let rows = (CGWindowListCopyWindowInfo([.optionOnScreenOnly], kCGNullWindowID) as! [[String: Any]]).filter { $0["kCGWindowOwnerName"] as? String == "Cortex" && $0["kCGWindowLayer"] as? Int == 0 }.map { w in ["id": w["kCGWindowNumber"]!, "pid": w["kCGWindowOwnerPID"]!, "bounds": w["kCGWindowBounds"]!, "active": NSWorkspace.shared.frontmostApplication?.processIdentifier == (w["kCGWindowOwnerPID"] as! Int32)] as [String: Any] }; print(String(data: try! JSONSerialization.data(withJSONObject: rows), encoding: .utf8)!)';
const nativeProbe = String.raw`import json,subprocess,sys; rows=json.loads(subprocess.check_output(["/usr/bin/swift","-e",sys.argv[1]],text=True,timeout=10)); dark=subprocess.run(["/usr/bin/osascript","-e",'tell application "System Events" to tell appearance preferences to get dark mode'],capture_output=True,text=True,timeout=3); print(json.dumps({"rows":rows,"appearanceStatus":dark.returncode,"appearanceStdout":dark.stdout}))`;
const nativeWindow = (theme, point) => {
  assert(report.nativeChecks.length < 8); const sample = JSON.parse(ssh(`/usr/bin/python3 -c ${quote(nativeProbe)} ${quote(swift)}`)); report.nativeChecks.push({ stage, theme, point, measuredAt: new Date().toISOString(), ...sample }); save();
  assert.equal(sample.appearanceStatus, 0); assert(['true\n', 'false\n'].includes(sample.appearanceStdout)); assert(Array.isArray(sample.rows)); assert.equal(sample.rows.length, 1);
  const w = { ...sample.rows[0], osDark: sample.appearanceStdout === 'true\n' }; assert(w.active && w.pid === report.installedBefore.pid && w.bounds.Width === 960 && w.bounds.Height === 640 && w.osDark === (theme === 'dark')); if (report.captures.length) assert.equal(w.id, report.captures[0].id); return w;
};
const model = { providerID: 'fake', modelID: 'reasoner' }, titles = ['Native completed turn', 'Native failed turn'];
const fixture = { name: 'Native Activity Bot', persona: 'Use only the controlled fixture.', model, mascot: { shape: 'pebble', color: 'meadow', eyes: 'round', mouth: 'smile', accessories: [] }, tools: {}, permission: [] };
const copy = { scope: 'The latest finished turn from each of up to 40 recently updated Bot conversations.', empty: 'No finished turns here', emptyBody: 'Finished Bot turns from these recent conversations will appear here.' };
let page, expect, call, verifyLists, go, bot, previous, previousProvider, oldDark, initialHash, fresh = false, changed = false, providerChanged = false, cleanupPhase = false, stage = 'preflight', promptAttempts = 0;
const sessions = [], histories = new Map(), writes = new Set(), elapsed = () => Date.now() - Date.parse(report.startedAt);
const budget = () => assert(elapsed() < report.budget.flowMs, 'Activity flow exceeded 120-second budget');
const mark = next => { stage = next; report.stage = next; save(); budget(); };
const preference = () => page.evaluate(() => ({ stored: localStorage.getItem('cortex.theme'), pref: document.querySelector('.theme [aria-checked=true]')?.dataset.themeValue, theme: document.documentElement.dataset.theme }));
save();
try {
  report.helperHashes = { [path.basename(fileURLToPath(import.meta.url))]: sha(fs.readFileSync(new URL(import.meta.url))), ...Object.fromEntries(Object.keys(helpers).map(name => [name, sha(fs.readFileSync(new URL(name, import.meta.url)))])) }; for (const [name, hash] of Object.entries(helpers)) assert.equal(report.helperHashes[name], hash);
  const pins = fs.readFileSync(membersFile), members = JSON.parse(pins); assert.equal(members.revision, revision); assert(Array.isArray(members.members) && members.members.length >= 4 && members.members.every(m => /^(packages\/app\/dist\/|packages\/desktop\/dist\/)/.test(m.path) && /^[a-f0-9]{64}$/.test(m.sha256))); assert.equal(new Set(members.members.map(m => m.path)).size, members.members.length); report.membersSHA256 = sha(pins); report.memberCount = members.members.length;
  const hashSource = 'import hashlib,json,pathlib,sys; p=pathlib.Path(sys.argv[1]); print(json.dumps({n:hashlib.sha256((p/n).read_bytes()).hexdigest() for n in sys.argv[2:]}))'; report.rootHelperHashes = JSON.parse(ssh(`/usr/bin/python3 -c ${quote(hashSource)} ${quote(root)} ${Object.keys(helpers).map(quote).join(' ')}`)); assert.deepEqual(report.rootHelperHashes, helpers);
  mark('identity'); report.installedBefore = installed(); report.backend = backend('health'); assert.equal(report.backend.protocol, protocol); assert.equal(report.backend.platform, 'darwin'); assert.equal(report.backend.port, 9456); assert.equal(report.backend.root, report.installedBefore.root); assert.equal(report.backend.scriptSHA256, helpers['terminal-state-native-backend.mjs']); receipt(0);
  const modules = [path.join(repo, 'node_modules'), '/tmp/opencode/node_modules'].find(dir => fs.existsSync(path.join(dir, '@playwright/test/index.mjs'))); assert(modules); const pw = await import(pathToFileURL(path.join(modules, '@playwright/test/index.mjs')).href); expect = pw.expect.configure({ timeout: 10000 });
  const browser = await pw.chromium.connectOverCDP('http://127.0.0.1:19444', { timeout: 10000 }), cdp = await browser.newBrowserCDPSession();
  const pidCheck = async () => assert.deepEqual((await cdp.send('SystemInfo.getProcessInfo')).processInfo.filter(p => p.type === 'browser').map(p => p.id), [report.installedBefore.pid]); await pidCheck();
  const pages = browser.contexts().flatMap(context => context.pages()).filter(p => p.url().startsWith('cortex://app/')); assert.equal(pages.length, 1); [page] = pages; page.setDefaultTimeout(10000); initialHash = new URL(page.url()).hash; assert.equal(initialHash, '#/home');
  await page.emulateMedia({ colorScheme: null, reducedMotion: null, forcedColors: null, contrast: null }); const fail = error => { if (report.errors.length < 20) report.errors.push(diagnostic(error)); };
  page.on('pageerror', fail); page.on('console', message => { if (message.type() === 'error') fail('Renderer console error'); }); page.on('dialog', async dialog => { fail('Unexpected dialog'); await dialog.dismiss(); }); for (const context of browser.contexts()) { context.on('page', () => fail('Unexpected page')); context.on('request', request => { if (/^https?:/.test(request.url())) fail('Unexpected renderer HTTP request'); }); }
  const lists = ['/api/bots', '/api/sessions', '/api/projects', '/api/providers', '/api/tasks', '/api/plugins', '/api/permissions'];
  call = async (route, method = 'GET', body) => {
    if (!cleanupPhase) budget(); assert(report.calls.length < (cleanupPhase ? 180 : 160)); const ownBot = bot && route === `/api/bots/${bot.id}`, ownSession = sessions.find(s => route === `/api/sessions/${s.id}`), messages = sessions.some(s => route === `/api/sessions/${s.id}/messages`); let allowed = false, status = 200;
    if (method === 'GET') allowed = body === undefined && (lists.includes(route) || ['/api/connection', '/api/providers/fake', '/api/catalog/providers', '/api/catalog/providers/fake/models'].includes(route) || ownBot || ownSession || messages);
    else if (fresh && cleanupPhase) { allowed = method === 'DELETE' && body === undefined && (ownBot || ownSession || providerChanged && route === '/api/providers/fake/key'); if (providerChanged && method === 'PATCH' && route === '/api/providers/fake') { assert.deepEqual(body, { enabled: previousProvider.enabled, baseURL: previousProvider.baseURL ?? null }); allowed = true; } }
    else if (fresh) {
      if (method === 'PATCH' && route === '/api/providers/fake') { assert.deepEqual(body, { enabled: true, baseURL: 'http://127.0.0.1:9456/v1' }); allowed = true; }
      if (method === 'PUT' && route === '/api/providers/fake/key') { assert.deepEqual(body, { key }); allowed = true; }
      if (method === 'POST' && route === '/api/bots' && !bot) { assert.deepEqual(body, fixture); allowed = true; status = 201; }
      if (bot && method === 'POST' && route === `/api/bots/${bot.id}/sessions` && sessions.length < 2) { assert.deepEqual(body, { title: titles[sessions.length], directory: report.installedBefore.root }); allowed = true; status = 201; }
      if (method === 'POST' && promptAttempts < 3 && route === `/api/sessions/${sessions[[0, 0, 1][promptAttempts]]?.id}/prompt`) { assert.deepEqual(body, { parts: [{ type: 'text', text: prompt(...steps[promptAttempts]) }], reasoning: true }); promptAttempts++; allowed = true; status = 202; }
    }
    assert(allowed, 'Refused uncontrolled IPC request'); if (method !== 'GET') { const token = JSON.stringify([cleanupPhase, method, route, body]); assert(!writes.has(token), 'Duplicate mutation refused'); writes.add(token); }
    const response = await page.evaluate(async ({ route, method, body }) => { const r = await window.cortex.request({ url: `cortex://local${route}`, method, headers: body === undefined ? [] : [['content-type', 'application/json']], body: body === undefined ? undefined : JSON.stringify(body) }); return { status: r.status, data: JSON.parse(r.body) }; }, { route, method, body });
    report.calls.push({ stage, route, method, status: response.status, ...(Array.isArray(response.data) ? { count: response.data.length } : {}) }); save(); assert(response.status === status || cleanupPhase && method === 'DELETE' && response.status === 404, `Unexpected IPC status: ${method} ${route}`); return response.data;
  };
  verifyLists = async () => { for (const route of lists) assert.deepEqual(await call(route), cleanupPhase && providerChanged && route === '/api/providers' ? [previousProvider] : []); assert.deepEqual(await call('/api/connection'), { mode: 'local', signedIn: false }); };
  await page.waitForFunction(() => window.cortex?.platform === 'darwin' && document.querySelector('.theme [aria-checked=true]')); await expect(page.locator('html')).toHaveAttribute('lang', 'en'); mark('fresh-profile'); await verifyLists(); previousProvider = await call('/api/providers/fake'); assert.deepEqual(previousProvider, { providerID: 'fake', enabled: true, hasKey: false }); fresh = true;
  const providers = await call('/api/catalog/providers'), models = await call('/api/catalog/providers/fake/models'); assert.deepEqual(providers.map(p => [p.id, p.api, p.npm, p.modelCount]), [['fake', 'http://127.0.0.1:9456/v1', '@ai-sdk/openai-compatible', 1]]); assert.deepEqual(models.map(m => [m.providerID, m.id, m.tool_call]), [['fake', 'reasoner', false]]);
  await page.waitForFunction(() => document.documentElement.dataset.theme === (document.querySelector('.theme [aria-checked=true]')?.dataset.themeValue === 'system' ? matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light' : document.querySelector('.theme [aria-checked=true]')?.dataset.themeValue)); previous = await preference(); oldDark = appearance(); assert(['true', 'false'].includes(oldDark) && ['system', 'light', 'dark'].includes(previous.pref)); report.previous = { ...previous, nativeDark: oldDark, hash: initialHash };
  go = async hash => { assert([initialHash, '#/activity'].includes(hash)); await page.evaluate(value => { history.pushState(null, '', value); dispatchEvent(new Event('cortex-variant')); }, hash); await expect(page).toHaveURL(`cortex://app/index.html${hash}`); };
  const main = page.locator('main'), rows = main.locator('li > button.travail-act'), row = i => rows.filter({ has: page.getByText(titles[i], { exact: true }) }), all = main.getByRole('button', { name: 'All', exact: true }), errors = main.getByRole('button', { name: 'Errors', exact: true }), picker = main.locator('.travail-act-picker'), scope = main.getByText(copy.scope, { exact: true });
  await go('#/activity'); await expect(main.getByRole('heading', { name: copy.empty, exact: true })).toBeVisible(); await expect(main.getByText(copy.emptyBody, { exact: true })).toBeVisible(); await expect(rows).toHaveCount(0); report.checks.push({ stage, initialEmpty: true });
  mark('controlled-histories'); providerChanged = true; await call('/api/providers/fake', 'PATCH', { enabled: true, baseURL: 'http://127.0.0.1:9456/v1' }); const saved = await call('/api/providers/fake/key', 'PUT', { key }); assert.deepEqual(saved, { providerID: 'fake', enabled: true, hasKey: true, keyHint: key.slice(-4), baseURL: 'http://127.0.0.1:9456/v1' });
  bot = await call('/api/bots', 'POST', fixture); report.bot = bot; save(); assert(/^bot_[\w-]+$/.test(bot.id)); assert.deepEqual(bot, { ...fixture, id: bot.id, memory: [], routines: [], time: bot.time });
  // ponytail: reuse the fixture's first three protocol steps; add a reviewed backend only for broader scenarios.
  for (const [index, [theme, turn]] of steps.slice(0, 3).entries()) {
    mark(`fixture:${theme}:${turn}`); const slot = [0, 0, 1][index]; if (!sessions[slot]) { const s = await call(`/api/bots/${bot.id}/sessions`, 'POST', { title: titles[slot], directory: report.installedBefore.root }); sessions.push(s); report.sessions = sessions; save(); assert(/^ses_[\w-]+$/.test(s.id) && s.kind === 'bot' && s.botID === bot.id && s.parentID === undefined && s.projectID === undefined && s.title === titles[slot] && s.directory === report.installedBefore.root); assert.deepEqual(s.model, model); }
    const s = sessions[slot], accepted = await call(`/api/sessions/${s.id}/prompt`, 'POST', { parts: [{ type: 'text', text: prompt(theme, turn) }], reasoning: true }); assert(/^msg_[\w-]+$/.test(accepted.messageID)); let history;
    await expect.poll(async () => { history = await call(`/api/sessions/${s.id}/messages`); return history.length === (turn === 'recover' ? 4 : 2) && Number.isFinite(history.at(-1)?.info.time.completed); }, { intervals: [100, 250, 500] }).toBe(true);
    assert.deepEqual(history.map(m => m.info.role), turn === 'recover' ? ['user', 'assistant', 'user', 'assistant'] : ['user', 'assistant']); assert(history.every(m => m.info.sessionID === s.id && m.info.agent === 'build' && m.info.model.providerID === 'fake' && m.info.model.modelID === 'reasoner' && m.parts.every(p => p.sessionID === s.id && p.messageID === m.info.id && ['step-start', 'step-finish', 'reasoning', 'text'].includes(p.type))));
    assert.equal(history.at(-2).info.id, accepted.messageID); assert.deepEqual(history.filter(m => m.info.role === 'user').map(m => m.parts.map(p => [p.type, p.text])), (turn === 'recover' ? ['fail', 'recover'] : ['fail']).map(t => [['text', prompt(theme, t)]]));
    const finished = history.filter(m => m.info.role === 'assistant'); assert(finished.every(m => Number.isFinite(m.info.time.completed) && m.info.time.completed >= m.info.time.created)); assert.equal(finished[0].info.error?.code, 'provider_auth_failed'); assert.deepEqual(finished[0].parts.filter(p => ['reasoning', 'text'].includes(p.type)), []);
    if (turn === 'recover') { assert.equal(finished[1].info.error, undefined); assert.deepEqual(finished[1].parts.filter(p => ['reasoning', 'text'].includes(p.type)).map(p => [p.type, p.text]), [['reasoning', reasoning(theme)], ['text', answer(theme)]]); assert.deepEqual(finished[1].parts.filter(p => p.type === 'step-finish').map(p => p.reason), ['stop']); }
    histories.set(s.id, history); report.checks.push({ stage, sessionID: s.id, messageID: history.at(-1).info.id, completed: history.at(-1).info.time.completed, outcome: turn === 'recover' ? 'Completed' : 'Failed', historySHA256: sha(JSON.stringify(history)) }); save();
  }
  receipt(3); const settledSessions = await call('/api/sessions'); assert.deepEqual(settledSessions.map(s => s.id).sort(), sessions.map(s => s.id).sort());
  const feed = async filtered => {
    await expect(scope).toBeVisible(); await expect(main.getByRole('button', { name: 'Export the log', exact: true })).toBeDisabled(); await expect(rows).toHaveCount(filtered ? 1 : 2); await expect(filtered ? errors : all).toHaveAttribute('aria-pressed', 'true');
    const indices = (filtered ? [1] : [0, 1]).sort((a, b) => histories.get(sessions[b].id).at(-1).info.time.completed - histories.get(sessions[a].id).at(-1).info.time.completed || (sessions[a].id < sessions[b].id ? -1 : 1)); await expect(rows.locator('.travail-grow > b:nth-of-type(2)')).toHaveText(indices.map(i => titles[i]));
    for (const i of indices) { const completed = histories.get(sessions[i].id).at(-1).info.time.completed; await expect(row(i).locator('.travail-grow > b').first()).toHaveText(bot.name); await expect(row(i).locator('.travail-meta')).toHaveText(i ? 'Failed' : 'Completed'); await expect(row(i).locator('time')).toHaveAttribute('datetime', new Date(completed).toISOString()); const time = await page.evaluate(n => new Intl.DateTimeFormat(document.documentElement.lang, { hour: '2-digit', minute: '2-digit' }).format(n), completed); await expect(row(i).locator('time')).toHaveText(time); }
    const text = await main.innerText(), forbidden = [key, 'Controlled credential refusal', ...steps.slice(0, 3).map(step => prompt(...step)), answer('light'), reasoning('light'), ...[...histories.values()].flat().flatMap(m => m.info.error ? [m.info.error.code, m.info.error.message] : [])]; assert(forbidden.every(value => !text.includes(value)), 'Activity leaked transcript or raw error');
  };
  changed = true; ssh('/usr/bin/osascript -e \'tell application "Cortex" to activate\' -e \'tell application "System Events" to tell process "Cortex" to set size of window 1 to {960,640}\''); await page.locator('.rail .theme [aria-checked=true]').focus(); await page.keyboard.press('Home'); await expect.poll(preference).toEqual({ stored: 'dark', pref: 'dark', theme: 'dark' }); await page.keyboard.press('ArrowLeft'); await expect.poll(async () => (await preference()).pref).toBe('system');
  const settle = async () => { await page.evaluate(() => document.fonts.ready); await page.waitForFunction(() => document.fonts.status === 'loaded' && document.getAnimations().filter(a => a.effect?.getTiming().iterations !== Infinity).every(a => a.playState === 'finished')); };
  const geometry = target => target.evaluate(el => {
    const clip = start => { let l = 0, t = 0, r = innerWidth, b = innerHeight, opacity = 1; for (let n = start; n; n = n.parentElement) { const s = getComputedStyle(n), q = n.getBoundingClientRect(); opacity *= s.visibility === 'visible' && s.display !== 'none' ? +s.opacity : 0; if (!['inline', 'contents'].includes(s.display)) { if (/^(auto|scroll|hidden|clip)$/.test(s.overflowX)) { l = Math.max(l, q.left + n.clientLeft); r = Math.min(r, q.left + n.clientLeft + n.clientWidth); } if (/^(auto|scroll|hidden|clip)$/.test(s.overflowY)) { t = Math.max(t, q.top + n.clientTop); b = Math.min(b, q.top + n.clientTop + n.clientHeight); } } } return { edges: [l, t, r, b], opacity }; };
    const box = r => [r.left, r.top, r.right, r.bottom], fits = (r, c) => r.width > 0 && r.height > 0 && r.left >= c.edges[0] - .5 && r.top >= c.edges[1] - .5 && r.right <= c.edges[2] + .5 && r.bottom <= c.edges[3] + .5, q = el.getBoundingClientRect(), boundsClip = clip(el.parentElement), ink = [];
    const walker = document.createTreeWalker(el, NodeFilter.SHOW_TEXT); for (let node; (node = walker.nextNode());) { if (!node.textContent.trim() || node.parentElement.closest('[aria-hidden=true]')) continue; const range = document.createRange(); range.selectNodeContents(node); const c = clip(node.parentElement); for (const r of range.getClientRects()) if (r.width && r.height) ink.push({ bounds: box(r), clip: c.edges, visible: fits(r, c) && c.opacity === 1 }); }
    return { text: (el.getAttribute('aria-label') || el.textContent).slice(0, 500), bounds: box(q), clip: boundsClip.edges, ink, visible: fits(q, boundsClip) && boundsClip.opacity === 1 && ink.length > 0 && ink.length <= 40 && ink.every(r => r.visible), hit: el.contains(document.elementFromPoint(q.x + q.width / 2, q.y + q.height / 2)) };
  });
  const capture = async (label, theme, filtered, targets, focus) => {
    mark(`${theme}:${label}:capture`); assert.equal(targets.length, 5); await main.locator('.content-top .title').hover(); await expect(page.locator('.toast, .tip, [role=menu]')).toHaveCount(0); await settle(); await feed(filtered); await expect(focus).toBeFocused(); assert(await focus.evaluate(el => el.matches(':focus-visible')));
    const renderer = async () => { await expect(page.locator('.window')).toHaveAttribute('data-sidebar', 'shown'); await expect(page.locator('html')).toHaveAttribute('data-theme', theme); assert.deepEqual(await page.evaluate(() => [innerWidth, innerHeight, matchMedia('(prefers-color-scheme: dark)').matches]), [960, 640, theme === 'dark']); }; await renderer();
    const measure = async () => { const boxes = []; for (const target of targets) { await expect(target).toBeVisible(); const g = await geometry(target); boxes.push(g); if (!g.visible || !g.hit) { report.failedGeometry = boxes; save(); assert.fail('Activity target clipped or covered'); } } return boxes; };
    const boxes = await measure(), win = nativeWindow(theme, 'before'); await pidCheck(); budget(); assert(report.capturesRequested < 4); const focusStyle = await focus.evaluate(el => ({ visible: el.matches(':focus-visible'), outline: getComputedStyle(el).outline, boxShadow: getComputedStyle(el).boxShadow }));
    const shot = { file: `${label}-${theme}.png`, requestedAt: new Date().toISOString(), theme, native: true, ...win, boxes, focus: focusStyle, status: 'requested' }; report.capturesRequested++; report.captures.push(shot); save();
    const response = await fetch(`http://127.0.0.1:19445/${win.id}`, { method: 'POST', signal: AbortSignal.timeout(15000) }); shot.httpStatus = response.status; save(); assert(response.ok); const bytes = Buffer.from(await response.arrayBuffer()); fs.writeFileSync(path.join(out, shot.file), bytes, { flag: 'wx' }); Object.assign(shot, { bytes: bytes.length, sha256: sha(bytes), status: 'original-retained' }); save();
    assert(bytes.length <= report.budget.originalBytes && report.captures.reduce((sum, c) => sum + (c.bytes ?? 0), 0) <= report.budget.totalBytes); assert(bytes.length >= 24 && bytes.subarray(0, 8).equals(Buffer.from('89504e470d0a1a0a', 'hex'))); shot.pixels = [bytes.readUInt32BE(16), bytes.readUInt32BE(20)]; assert(shot.pixels[0] >= 960 && shot.pixels[0] / 960 === shot.pixels[1] / 640);
    shot.afterBoxes = await measure(); await renderer(); await feed(filtered); await expect(focus).toBeFocused(); assert.deepEqual(nativeWindow(theme, 'after'), win); await pidCheck(); shot.status = 'passed'; shot.finishedAt = new Date().toISOString(); save(); mark(`${theme}:${label}:retained`);
  };
  for (const theme of ['light', 'dark']) {
    mark(`${theme}:all`); setAppearance(theme === 'dark'); await expect.poll(preference).toEqual({ stored: 'system', pref: 'system', theme }); await go('#/activity'); await feed(false);
    await picker.press('ArrowDown'); await expect(page.getByRole('menuitem')).toHaveCount(2); await page.keyboard.press('End'); const option = page.getByRole('menuitem', { name: bot.name, exact: true }); await expect(option).toBeFocused(); await page.keyboard.press('Enter'); await expect(picker).toHaveAttribute('aria-label', bot.name); await all.press('Space'); await feed(false);
    await capture('activity-all', theme, false, [scope, picker, all, row(1), row(0)], all);
    await all.press('Tab'); await expect(errors).toBeFocused(); await errors.press('Space'); await feed(true); await capture('activity-errors', theme, true, [scope, picker, all, errors, row(1)], errors);
    mark(`${theme}:exact-links`); await errors.press('Tab'); const clear = main.getByRole('button', { name: 'Clear filters', exact: true }); await expect(clear).toBeFocused(); await clear.press('Tab'); await expect(row(1)).toBeFocused(); await row(1).press('Enter');
    const destination = async i => { await expect(page).toHaveURL(`cortex://app/index.html#/work-task?id=${sessions[i].id}`); await expect(main.locator('.content-top .title')).toHaveText(titles[i]); await expect(main.getByPlaceholder(`Give ${bot.name} an instruction`, { exact: true })).toBeVisible(); await page.evaluate(() => history.back()); await expect(page).toHaveURL('cortex://app/index.html#/activity'); await feed(false); };
    await destination(1); await row(0).click(); await destination(0); report.checks.push({ stage, botFilterKeyboard: true, errorsSpace: true, failedRowEnter: sessions[1].id, completedRowPointer: sessions[0].id }); save();
  }
  mark('read-only-feed'); for (const s of sessions) assert.deepEqual(await call(`/api/sessions/${s.id}/messages`), histories.get(s.id)); assert.deepEqual(await call(`/api/bots/${bot.id}`), bot); assert.deepEqual(await call('/api/sessions'), settledSessions); assert.deepEqual(await call('/api/providers/fake'), saved);
  assert.equal(promptAttempts, 3); assert.equal(report.nativeChecks.length, 8); assert.equal(report.capturesRequested, 4); assert.equal(report.captures.filter(c => c.status === 'passed').length, 4); mark('flow-complete'); report.status = 'passed';
} catch (error) { report.status = 'failed'; report.failure = { stage, diagnostic: diagnostic(error) }; }
finally {
  report.flowDurationMs = elapsed(); cleanupPhase = true; const clean = async (name, fn) => { try { await fn(); report.cleanup[name] = true; } catch (error) { report.status = 'failed'; report.cleanup[name] = { diagnostic: diagnostic(error) }; } save(); };
  for (const s of sessions) if (/^ses_[\w-]+$/.test(s.id)) await clean(`sessionRemoved:${s.id}`, () => call(`/api/sessions/${s.id}`, 'DELETE'));
  if (bot?.id && /^bot_[\w-]+$/.test(bot.id)) await clean('ownedBotRemoved', () => call(`/api/bots/${bot.id}`, 'DELETE'));
  if (providerChanged) { await clean('fixtureKeyRemoved', async () => { const p = await call('/api/providers/fake/key', 'DELETE'); assert(p.hasKey === false && p.keyHint === undefined); }); await clean('providerValuesRestored', async () => { assert.deepEqual(await call('/api/providers/fake', 'PATCH', { enabled: previousProvider.enabled, baseURL: previousProvider.baseURL ?? null }), previousProvider); report.providerDocumentRetained = true; }); }
  if (changed) await clean('nativeAppearanceRestored', async () => setAppearance(oldDark === 'true'));
  if (changed && previous) await clean('themePreferenceRestored', async () => { await page.evaluate(pref => dispatchEvent(new CustomEvent('cortex-theme', { detail: pref })), previous.pref); await expect.poll(async () => { const { stored: _stored, ...value } = await preference(); return value; }).toEqual({ pref: previous.pref, theme: previous.theme }); await page.evaluate(stored => { if (stored === null) localStorage.removeItem('cortex.theme'); else localStorage.setItem('cortex.theme', stored); }, previous.stored); });
  if (go) await clean('routeRestored', async () => { await go(initialHash); if (previous) await expect.poll(preference).toEqual(previous); });
  if (fresh && verifyLists) await clean('controlledListsRestored', verifyLists);
  if (report.backend) await clean('controlledInferenceOnly', async () => receipt(promptAttempts));
  if (report.installedBefore) await clean('installedAfter', async () => { report.installedAfter = installed(); assert.deepEqual(report.installedAfter, report.installedBefore); });
  if (report.errors.length) report.status = 'failed'; report.finishedAt = new Date().toISOString(); report.durationMs = elapsed(); report.scope = 'Four English native Activity All/Errors images, two historical root outcomes, keyboard Bot/type filters and exact Work links. Three local fixture turns only. Cleanup checks fixture-key removal/default-provider retention. No restart/interruption/race/duplicate-Bot/40-root/preview/locale/full-product acceptance.'; save();
}
console.log(`Activity native: ${report.status}; ${stage}; ${path.join(out, 'manifest.json')}`); process.exit(report.status === 'passed' ? 0 : 1);
