// Preparation only: bounded AX-shape observation/cancellation; never Files/download acceptance.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { protocol, key, prompt, answer, reasoning, filename, model, png, fixture } from './files-native-backend.mjs';
const [out, root, asar, revision, membersFile] = process.argv.slice(2), started = Date.now(), repo = fs.realpathSync(process.cwd());
assert(process.argv.length === 7 && out === '/tmp/opencode/files-save-probe-d20a012-1' && /^\/(?:private\/)?tmp\/opencode\/desktop-files-native-d20a012-save-probe-1$/.test(root ?? '') && /^[a-f0-9]{64}$/.test(asar ?? '') && revision === 'd20a012fbb774aa9b348fe1913f85d3476430098' && path.isAbsolute(membersFile ?? '')); assert(!fs.existsSync(out)); fs.mkdirSync(out);
const sha = v => createHash('sha256').update(v).digest('hex'), quote = v => `'${v.replaceAll("'", "'\\''")}'`, helpers = { 'files-native-backend.mjs': '5c8239ef27f8d962b4a1cd5fcfb08e34c8ba4f3871f5242fe1043f73ef90476d', 'launch-files-native.py': 'd7463d642ab0348e8bcebb58f18db9495fbc8594f0dfcdae657e6f9878d149c8' };
const report = { status: 'running', scope: 'AX shape only; no screenshots, Save action or acceptance claim', revision, asar, startedAt: new Date(started).toISOString(), budget: { flowMs: 60000, absoluteMs: 100000, axNodes: 100, axBytes: 16384, axCalls: 5, ipcCalls: 80 }, calls: [], ax: [], errors: [], cleanup: {} };
const save = () => { const text = JSON.stringify(report, null, 2) + '\n'; assert(Buffer.byteLength(text) <= 262144); fs.writeFileSync(path.join(out, 'manifest.json'), text); }, diagnostic = e => String(e?.stack ?? e).replaceAll(key, '[fixture-key]').replace(/\bBearer\s+\S+/gi, 'Bearer [redacted]').replace(/https?:\/\/\S+/g, '[network-url]').slice(0, 900);
let cleaning = false, stage = 'identity', page, expect, call, session, previousProvider, initialUI, fresh = false, providerChanged = false, requested = false, attempts = 0;
const time = (limit = 8000) => { const left = (cleaning ? 100000 : 60000) - (Date.now() - started); assert(left > 0, 'Diagnostic deadline reached'); return Math.max(1, Math.min(limit, left)); };
const wait = async action => { const timeout = time(); page?.setDefaultTimeout(Math.min(5000, timeout)); let timer; try { return await Promise.race([action(), new Promise((_, reject) => { timer = setTimeout(() => reject(new Error('Diagnostic operation timed out')), timeout); })]); } finally { clearTimeout(timer); } };
const watchdog = setTimeout(() => { report.status = 'failed'; report.failure = '100-second absolute deadline; coordinator recovery required'; report.cleanupIncomplete = true; save(); process.exit(1); }, Math.max(1, 100000 - (Date.now() - started)));
const ssh = command => execFileSync('ssh', ['-o', 'BatchMode=yes', '-o', 'ConnectTimeout=4', 'mac-live', command], { encoding: 'utf8', timeout: time(10000), maxBuffer: 262144, stdio: ['pipe', 'pipe', 'pipe'] }).trim();
const python = (code, args = []) => JSON.parse(ssh(`/usr/bin/python3 -c ${quote(code)} ${args.map(quote).join(' ')}`));
const receipt = n => { const r = JSON.parse(ssh('/usr/bin/curl --fail --silent --show-error --max-time 3 http://127.0.0.1:9456/receipt')); report.backendReceipt = r; save(); assert(r.protocol === protocol && r.platform === 'darwin' && r.port === 9456 && r.root === report.installed.root && r.scriptSHA256 === helpers['files-native-backend.mjs']); if (report.runID) { assert.equal(r.runID, report.runID); assert.equal(r.pid, report.backendPID); } else { report.runID = r.runID; report.backendPID = r.pid; } assert.deepEqual(r.fixture, fixture); assert.equal(r.counts.errors, 0); assert.equal(r.counts.inference, n); assert.deepEqual(r.failures, []); assert.deepEqual(r.requests, n ? [{ imageSHA256: fixture.sha256, imageBytes: 393, modelExact: true, authorizationExact: true, messagesExact: true, toolsAbsent: true, httpStatus: 200, completed: true }] : []); };
const osa = String.raw`function run(argv) {
 const se=Application('System Events'), p=se.applicationProcesses.byName('Cortex'), pid=Number(argv[0]), op=argv[1], file=argv[2];
 const read=f=>{try{const v=f();return ['string','number','boolean'].includes(typeof v)?v:null;}catch(_){return null;}}, cut=v=>typeof v==='string'?v.slice(0,64):v;
 function snapshot(){const windows=p.windows(), nodes=[], queue=[];let truncated=false; windows.slice(0,3).forEach((w,i)=>{const sheets=w.sheets();if(sheets.length>3)truncated=true;sheets.slice(0,3).forEach((e,j)=>queue.push({e,path:'w'+(i+1)+'/s'+(j+1),sheet:null}));});
  while(queue.length&&nodes.length<100){const x=queue.shift(), role=read(()=>x.e.role()), sheet=role==='AXSheet'?x.path:x.sheet;nodes.push({path:x.path,sheet,role,name:cut(read(()=>x.e.name())),value:cut(read(()=>x.e.value())),focused:read(()=>x.e.attributes.byName('AXFocused').value())});let children=[];try{children=x.e.uiElements();}catch(_){}if(children.length>100)truncated=true;children.slice(0,100).forEach((e,i)=>queue.push({e,path:x.path+'/'+i,sheet}));}
  let focus=null;try{const f=p.attributes.byName('AXFocusedUIElement').value();focus={role:read(()=>f.role()),name:cut(read(()=>f.name())),value:cut(read(()=>f.value()))};}catch(_){} const s={pid:read(()=>p.unixId()),name:read(()=>p.name()),frontmost:read(()=>p.frontmost()),windows:windows.length,topSheets:windows.slice(0,3).map(w=>w.sheets().length),nodes,focus,truncated:truncated||queue.length>0||windows.length>3};while(unescape(encodeURIComponent(JSON.stringify(s))).length>14500){s.nodes.pop();s.truncated=true;}return s;}
 const need=(v,m)=>{if(!v)throw Error(m);}, owner=s=>need(s.pid===pid&&s.name==='Cortex'&&s.frontmost===true&&!s.truncated,'Unknown owner or truncated AX inventory');
 function shape(s){owner(s);const sheets=s.nodes.filter(n=>n.role==='AXSheet'), controls=x=>s.nodes.filter(n=>n.sheet===x.path&&n.path!==x.path), saves=sheets.filter(x=>{const c=controls(x);return c.filter(n=>n.role==='AXButton'&&n.name==='Save').length===1&&c.filter(n=>n.role==='AXButton'&&n.name==='Cancel').length===1&&c.filter(n=>n.role==='AXTextField'&&n.value===file).length===1;});need(saves.length===1&&saves[0].path.startsWith('w1/'),'Unknown Save owner/filename');return {save:saves[0],extra:sheets.filter(n=>n.path!==saves[0].path),controls};}
 function element(path){const parts=path.split('/'), e=p.windows()[Number(parts[0].slice(1))-1].sheets()[Number(parts[1].slice(1))-1];return parts.slice(2).reduce((n,i)=>n.uiElements()[Number(i)],e);}
 let before=null, after=null, action='none', error=null;try{before=snapshot();if(op==='inspect-save'||op==='inspect-folder'){for(let i=0;i<20&&before.nodes.filter(n=>n.role==='AXSheet').length<(op==='inspect-save'?1:2);i++){delay(.1);before=snapshot();}}
  if(op==='go'){const q=shape(before);need(q.extra.length===0&&before.topSheets[0]===1,'Expected one Save sheet');se.keystroke('g',{using:['command down','shift down']});action='Command+Shift+G';}
  else if(op==='cancel'){
   owner(before);if(before.nodes.some(n=>n.role==='AXSheet')){let q=shape(before);
    if(q.extra.length){need(q.extra.length===1,'Unknown additional modal');const c=q.controls(q.extra[0]);need(c.some(n=>['AXTextField','AXComboBox'].includes(n.role)&&n.focused===true)&&c.some(n=>n.role==='AXButton'&&n.name==='Go'),'Unknown Go to Folder focus');se.keyCode(53);action='Escape';for(let i=0;i<20;i++){delay(.1);after=snapshot();if(after.nodes.filter(n=>n.role==='AXSheet').length===1)break;}q=shape(after);need(q.extra.length===0,'Nested dialog retained');}
    const b=q.controls(q.save).filter(n=>n.role==='AXButton'&&n.name==='Cancel');need(b.length===1,'Unknown Cancel');const button=element(b[0].path);need(read(()=>button.role())==='AXButton'&&read(()=>button.name())==='Cancel'&&p.unixId()===pid&&p.frontmost()===true,'Cancel target changed');button.click();action+='; Cancel';
    for(let i=0;i<20;i++){delay(.1);after=snapshot();if(!after.nodes.some(n=>n.role==='AXSheet'))break;}need(!after.nodes.some(n=>n.role==='AXSheet'),'Save did not cancel');
   }else action='no-modal';
  }
  else need(op==='inspect-save'||op==='inspect-folder','Invalid operation');
 }catch(e){error=String(e).slice(0,256);}return JSON.stringify({before,after:after?{pid:after.pid,name:after.name,frontmost:after.frontmost,topSheets:after.topSheets,focus:after.focus}:null,action,error});
}`;
const probe = String.raw`import hashlib,json,subprocess,sys
try: r=subprocess.run(['/usr/bin/osascript','-l','JavaScript','-e',sys.argv[1],*sys.argv[2:5]],capture_output=True,timeout=float(sys.argv[5])); status=r.returncode; out=r.stdout; err=r.stderr
except subprocess.TimeoutExpired as e: status=None; out=e.stdout or b''; err=e.stderr or b''
raw=out+b'\n'+err; print(json.dumps({'status':status,'bytes':len(raw),'sha256':hashlib.sha256(raw).hexdigest(),'stdout':out[:16384].decode('utf8','replace'),'stderr':err[:max(0,16384-len(out))].decode('utf8','replace'),'truncated':len(raw)>16384}))`;
const ax = op => { assert(report.ax.length < 5); const result = python(probe, [osa, String(report.installed.pid), op, filename, String(Math.max(.1, (time(8000) - 1000) / 1000))]); report.ax.push({ stage, op, at: new Date().toISOString(), ...result }); save(); assert(result.status === 0 && !result.truncated, 'AX probe incomplete'); const sample = JSON.parse(result.stdout); assert(!sample.error, sample.error ?? 'AX error'); return sample; };
const lists = ['/api/bots','/api/sessions','/api/projects','/api/providers','/api/tasks','/api/plugins','/api/permissions'], create = { kind: 'chat', model, title: 'Native saved image' }, input = { parts: [{ type: 'text', text: prompt }, { type: 'file', mime: 'image/png', filename, data: png }], reasoning: true }, writes = new Set();
save();
try {
 report.sources = { [path.basename(fileURLToPath(import.meta.url))]: sha(fs.readFileSync(new URL(import.meta.url))), ...Object.fromEntries(Object.keys(helpers).map(n=>[n,sha(fs.readFileSync(new URL(n,import.meta.url)))])) }; for(const [n,h] of Object.entries(helpers))assert.equal(report.sources[n],h); assert.equal(Buffer.from(png,'base64').length,393); assert.equal(sha(Buffer.from(png,'base64')),fixture.sha256);
 const pins=fs.readFileSync(membersFile), members=JSON.parse(pins); assert.equal(members.revision,revision); report.membersSHA256=sha(pins); report.rootHelperHashes=python('import hashlib,json,pathlib,sys; p=pathlib.Path(sys.argv[1]); print(json.dumps({n:hashlib.sha256((p/n).read_bytes()).hexdigest() for n in sys.argv[2:]}))',[root,...Object.keys(helpers)]); assert.deepEqual(report.rootHelperHashes,helpers);
 report.installed=JSON.parse(ssh(`/usr/bin/python3 ${quote(`${root}/launch-files-native.py`)} --inspect ${quote(root)} ${asar} ${revision}`)); assert(report.installed.membersSHA256===report.membersSHA256&&report.installed.membersVerified===members.members.length&&report.installed.inspectorSHA256===helpers['launch-files-native.py']); receipt(0);
 const modules=[path.join(repo,'node_modules'),'/tmp/opencode/node_modules'].find(d=>fs.existsSync(path.join(d,'@playwright/test/index.mjs'))); assert(modules); assert.equal(JSON.parse(fs.readFileSync(path.join(modules,'@playwright/test/package.json'))).version,'1.63.0'); const pw=await wait(()=>import(pathToFileURL(path.join(modules,'@playwright/test/index.mjs')).href)); expect=pw.expect.configure({timeout:5000}); const browser=await wait(()=>pw.chromium.connectOverCDP('http://127.0.0.1:19444',{noDefaults:true,timeout:time()})), cdp=await wait(()=>browser.newBrowserCDPSession()); assert.deepEqual((await wait(()=>cdp.send('SystemInfo.getProcessInfo'))).processInfo.filter(p=>p.type==='browser').map(p=>p.id),[report.installed.pid]);
  const pages=browser.contexts().flatMap(c=>c.pages()).filter(p=>p.url().startsWith('cortex://app/')); assert.equal(pages.length,1);[page]=pages;page.setDefaultTimeout(5000);assert.equal(new URL(page.url()).hash,'#/home');await wait(()=>page.waitForFunction(()=>window.cortex?.platform==='darwin'&&document.querySelector('.theme [aria-checked=true]')));await wait(()=>expect(page.locator('html')).toHaveAttribute('lang','en'));initialUI=await wait(()=>page.evaluate(()=>({theme:localStorage.getItem('cortex.theme'),resolved:document.documentElement.dataset.theme}))); const error=e=>{if(report.errors.length<8)report.errors.push(diagnostic(e));};page.on('pageerror',error);page.on('console',m=>{if(m.type()==='error')error('Renderer console error');});for(const c of browser.contexts()){c.on('page',()=>error('Unexpected page'));c.on('request',r=>{if(/^https?:/.test(r.url()))error('Unexpected renderer HTTP request');});}
 call=async(route,method='GET',body)=>{time();assert(report.calls.length<(cleaning?80:60));const own=session&&route===`/api/sessions/${session.id}`, history=session&&route===`/api/sessions/${session.id}/messages`;let allowed=method==='GET'&&body===undefined&&(lists.includes(route)||['/api/connection','/api/providers/fake','/api/catalog/providers/fake/models'].includes(route)||own||history), status=200;
  if(fresh&&cleaning){if(method==='DELETE'&&body===undefined&&(own||providerChanged&&route==='/api/providers/fake/key'))allowed=true;if(method==='PATCH'&&providerChanged&&route==='/api/providers/fake'){assert.deepEqual(body,{enabled:true,baseURL:null});allowed=true;}}
  if(fresh&&!cleaning){if(method==='PATCH'&&route==='/api/providers/fake'){assert([JSON.stringify({enabled:true,baseURL:'http://127.0.0.1:9456/v1'}),JSON.stringify({enabled:false})].includes(JSON.stringify(body)));allowed=true;}if(method==='PUT'&&route==='/api/providers/fake/key'){assert.deepEqual(body,{key});allowed=true;}if(method==='POST'&&route==='/api/sessions'&&!session){assert.deepEqual(body,create);allowed=true;status=201;}if(method==='POST'&&session&&route===`/api/sessions/${session.id}/prompt`&&attempts===0){assert.deepEqual(body,input);attempts++;allowed=true;status=202;}}
  assert(allowed,'IPC refused');const bodySHA256=body===undefined?null:sha(JSON.stringify(body)), token=JSON.stringify([cleaning,route,method,bodySHA256]);if(method!=='GET'){assert(!writes.has(token));writes.add(token);}const entry={stage,route,method,bodySHA256,status:null};report.calls.push(entry);save();const r=await wait(()=>page.evaluate(async({route,method,body})=>{const v=await window.cortex.request({url:`cortex://local${route}`,method,headers:body===undefined?[]:[['content-type','application/json']],body:body===undefined?undefined:JSON.stringify(body)});return {status:v.status,data:JSON.parse(v.body)};},{route,method,body}));entry.status=r.status;save();assert(r.status===status||cleaning&&method==='DELETE'&&r.status===404,'IPC status refused');return r.data;};
 stage='fresh-profile';for(const r of lists)assert.deepEqual(await call(r),[]);assert.deepEqual(await call('/api/connection'),{mode:'local',signedIn:false});previousProvider=await call('/api/providers/fake');assert.deepEqual(previousProvider,{providerID:'fake',enabled:true,hasKey:false});fresh=true;assert.deepEqual((await call('/api/catalog/providers/fake/models')).map(m=>[m.id,m.capabilities.imageInput,m.tool_call]),[['reasoner',true,false]]);
 stage='controlled-image';providerChanged=true;await call('/api/providers/fake','PATCH',{enabled:true,baseURL:'http://127.0.0.1:9456/v1'});assert.equal((await call('/api/providers/fake/key','PUT',{key})).hasKey,true);session=await call('/api/sessions','POST',create);report.sessionID=session.id;save();assert(/^ses_[0-9a-f]{32,}$/.test(session.id)&&session.kind==='chat'&&session.parentID===undefined&&session.directory===undefined&&session.botID===undefined);const accepted=await call(`/api/sessions/${session.id}/prompt`,'POST',input);let history;
 await wait(()=>expect.poll(async()=>{history=await call(`/api/sessions/${session.id}/messages`);return history.length===2&&Number.isFinite(history[1]?.info.time.completed);},{intervals:[100,250,500]}).toBe(true));assert.deepEqual(history.map(m=>m.info.role),['user','assistant']);assert(history.every(m=>m.info.sessionID===session.id&&m.info.error===undefined));assert.equal(history[0].info.id,accepted.messageID);assert.deepEqual(history[0].parts.map(({id:_id,sessionID:_s,messageID:_m,...p})=>p),input.parts);assert.deepEqual(history[1].parts.filter(p=>['reasoning','text'].includes(p.type)).map(p=>[p.type,p.text]),[['reasoning',reasoning],['text',answer]]);
 const part=history[0].parts.find(p=>p.type==='file');assert(/^prt_[0-9a-f]{32,}$/.test(part.id)&&part.sessionID===session.id&&part.messageID===accepted.messageID);report.tuple={session:session.id,message:accepted.messageID,part:part.id};report.historySHA256=sha(JSON.stringify(history));await call('/api/providers/fake','PATCH',{enabled:false});stage='chat-open';await wait(()=>page.evaluate(id=>{history.pushState(null,'',`#/chat?id=${id}`);dispatchEvent(new Event('cortex-variant'));},session.id));
 const open=page.getByRole('button',{name:`Open ${filename}`,exact:true});await wait(()=>expect(open).toBeEnabled());await wait(()=>expect(page.getByPlaceholder('Reply to Cortex',{exact:true})).toHaveValue(''));await wait(()=>open.click());await wait(()=>expect(page).toHaveURL(`cortex://app/index.html#/file-image?${new URLSearchParams(report.tuple)}`));await wait(()=>expect.poll(()=>page.locator('.medias-image-live .medias-view img').evaluate(i=>[i.complete,i.naturalWidth,i.naturalHeight])).toEqual([true,120,180]));
 stage='download';const download=page.locator('.medias-image-live').getByRole('button',{name:'Download',exact:true});await wait(()=>expect(download).toBeEnabled());requested=true;report.downloadRequested=true;save();await wait(()=>download.click());stage='save-inventory';ax('inspect-save');ax('go');stage='folder-inventory';const folder=ax('inspect-folder');assert(folder.before.nodes.filter(n=>n.role==='AXSheet').length===2,'Unknown Go to Folder layout');time();report.status='observed';
} catch(e){report.status='failed';report.failure={stage,diagnostic:diagnostic(e)};}
finally {
 cleaning=true;report.flowMs=Date.now()-started;const clean=async(name,fn)=>{try{time();await fn();report.cleanup[name]=true;}catch(e){report.status='failed';report.cleanup[name]={diagnostic:diagnostic(e)};}save();};
 if(requested)await clean('nativeCancel',async()=>{stage='cancel';const s=ax('cancel');report.modalDisposition=s.action;assert(s.action.includes('Cancel'),'No recognized Save cancellation');});
 if(session?.id&&/^ses_[0-9a-f]{32,}$/.test(session.id))await clean('ownedChatRemoved',()=>call(`/api/sessions/${session.id}`,'DELETE'));
 if(providerChanged){await clean('keyRemoved',async()=>{const p=await call('/api/providers/fake/key','DELETE');assert(p.hasKey===false&&p.keyHint===undefined);});await clean('providerDefaults',async()=>{assert.deepEqual(await call('/api/providers/fake','PATCH',{enabled:true,baseURL:null}),previousProvider);report.providerDocumentRetained=true;});}
 if(fresh)await clean('listsRestored',async()=>{for(const r of lists)assert.deepEqual(await call(r),providerChanged&&r==='/api/providers'?[previousProvider]:[]);assert.deepEqual(await call('/api/connection'),{mode:'local',signedIn:false});});
 if(page&&initialUI)await clean('routeAndTheme',async()=>{await wait(()=>page.evaluate(()=>{history.pushState(null,'','#/home');dispatchEvent(new Event('cortex-variant'));}));await wait(()=>expect(page).toHaveURL('cortex://app/index.html#/home'));assert.deepEqual(await wait(()=>page.evaluate(()=>({theme:localStorage.getItem('cortex.theme'),resolved:document.documentElement.dataset.theme}))),initialUI);});
 if(report.installed)await clean('backendReceipt',async()=>receipt(attempts));
 if(report.installed)await clean('installedAfter',async()=>assert.deepEqual(JSON.parse(ssh(`/usr/bin/python3 ${quote(`${root}/launch-files-native.py`)} --inspect ${quote(root)} ${asar} ${revision}`)),report.installed));
 report.durationMs=Date.now()-started;if(report.errors.length||report.durationMs>=100000)report.status='failed';if(report.durationMs>=100000)report.cleanupIncomplete=true;report.finishedAt=new Date().toISOString();save();clearTimeout(watchdog);
}
console.log(`Files Save diagnostic: ${report.status}; ${path.join(out,'manifest.json')}`);process.exit(report.status==='observed'?0:1);
