// Prepared only. Coordinator owns the admitted package, Mac lease, execution and pixel review.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { pathToFileURL } from 'node:url';
import { protocol } from './terminal-state-native-backend.mjs';
const [outArg, root, expectedAsar, revision, membersArg] = process.argv.slice(2);
assert(outArg && path.isAbsolute(outArg) && /^\/(?:private\/)?tmp\/opencode\/desktop-terminal-state-appearance-theme-[\w.-]+$/.test(root ?? '') && /^[a-f0-9]{64}$/.test(expectedAsar ?? '') && /^[a-f0-9]{40}$/.test(revision ?? '') && membersArg && path.isAbsolute(membersArg), 'Usage: node appearance-theme-native.mjs <fresh-output> <fresh-mac-root> <asar-sha256> <revision> <members.json>');
const out = path.resolve(outArg), repo = fs.realpathSync(process.cwd()), sha = value => createHash('sha256').update(value).digest('hex');
const originals = { 'terminal-state-native-backend.mjs': 'd22fcbe2287a7898452778ea58d665f0742f4a1d4d580ec7c237dc10cfc70d4d', 'launch-terminal-state-native.py': '4aec6651e6178bf890a299551497514f5159342a8f94db8972515c000fc10257', 'cleanup-terminal-state-native.py': 'c46f218f17bcda2ba031fe8f2959f9f8e18dda379a7edcd076b01be0c881c08a' };
const helperHashes = Object.fromEntries(['appearance-theme-native.mjs', ...Object.keys(originals)].map(name => [name, sha(fs.readFileSync(new URL(name, import.meta.url)))]));
for (const [name, hash] of Object.entries(originals)) assert.equal(helperHashes[name], hash);
const pins = fs.readFileSync(membersArg); assert.equal(JSON.parse(pins).revision, revision); assert(!fs.existsSync(out) && out !== repo && !out.startsWith(`${repo}/`)); fs.mkdirSync(out, { recursive: true });
const report = { status: 'running', revision, expectedAsar, membersSHA256: sha(pins), helperHashes, startedAt: new Date().toISOString(), invocation: { execPath: process.execPath, nodeVersion: process.version, argv: process.argv.slice(1), cwd: repo }, checks: [], captures: [], engineReads: [], pageErrors: [], consoleErrors: [], rendererHttp: [], unexpectedDialogs: 0, cleanup: {} };
const save = () => fs.writeFileSync(path.join(out, 'manifest.json'), JSON.stringify(report, null, 2) + '\n');
const diagnostic = e => String(e?.stack ?? e?.message ?? e).replace(/\bBearer\s+[^\s"'`,]+/gi, 'Bearer [redacted]').replace(/https?:\/\/[^\s"'<>]+/g, '[network-url]');
const quote = value => `'${value.replaceAll("'", "'\\''")}'`;
const ssh = command => execFileSync('ssh', ['-o', 'BatchMode=yes', '-o', 'ConnectTimeout=10', 'mac-live', command], { encoding: 'utf8', timeout: 30000, maxBuffer: 4 * 1024 * 1024, stdio: ['pipe', 'pipe', 'pipe'] }).trim();
const appearance = () => ssh(`/usr/bin/osascript -e 'tell application "System Events" to tell appearance preferences to get dark mode'`);
let osTheme; const setAppearance = theme => { ssh(`/usr/bin/osascript -e 'tell application "System Events" to tell appearance preferences to set dark mode to ${theme === 'dark'}'`); assert.equal(appearance(), String(theme === 'dark')); osTheme = theme; };
const backend = endpoint => JSON.parse(ssh(`/usr/bin/curl --fail --silent --show-error --max-time 5 http://127.0.0.1:9456/${endpoint}`));
const receipt = () => { const r = backend('receipt'); assert.equal(r.runID, report.backend.runID); assert.equal(r.counts.errors, 0); assert.deepEqual(r.failures, []); assert.deepEqual(r.requests, []); report.backendReceipt = r; };
const installed = () => { const v = JSON.parse(ssh(`/usr/bin/python3 ${quote(`${root}/launch-terminal-state-native.py`)} --inspect ${quote(root)} ${expectedAsar} ${revision}`)); assert.equal(v.membersSHA256, sha(pins)); assert.equal(v.membersVerified, JSON.parse(pins).members.length); assert.equal(v.inspectorSHA256, originals['launch-terminal-state-native.py']); return v; };
const swift = 'import Foundation; import AppKit; import CoreGraphics; let all = CGWindowListCopyWindowInfo([.optionOnScreenOnly], kCGNullWindowID) as! [[String: Any]]; let rows = all.filter { $0["kCGWindowOwnerName"] as? String == "Cortex" && $0["kCGWindowLayer"] as? Int == 0 }.map { w in ["id": w["kCGWindowNumber"]!, "pid": w["kCGWindowOwnerPID"]!, "bounds": w["kCGWindowBounds"]!, "active": NSWorkspace.shared.frontmostApplication?.processIdentifier == (w["kCGWindowOwnerPID"] as! Int32)] as [String: Any] }; print(String(data: try! JSONSerialization.data(withJSONObject: rows), encoding: .utf8)!)';
const nativeWindow = () => { const rows = JSON.parse(ssh(`/usr/bin/swift -e ${quote(swift)}`)); assert.equal(rows.length, 1); const w = rows[0]; assert(w.active && w.pid === report.installedBefore.pid && w.bounds.Width === 960 && w.bounds.Height === 640); if (report.captures.length) assert.equal(w.id, report.captures[0].id); return w; };
let page, expect, emptyEngine, initialURL, oldAppearance, previous, changed = false, stage = 'identity';
try {
  report.installedBefore = installed(); report.backend = backend('health'); assert.equal(report.backend.protocol, protocol); assert.equal(report.backend.platform, 'darwin'); assert.equal(report.backend.port, 9456); assert.equal(report.backend.root, report.installedBefore.root); assert.equal(report.backend.scriptSHA256, originals['terminal-state-native-backend.mjs']); receipt(); save();
  const modules = [path.join(repo, 'node_modules'), '/tmp/opencode/node_modules'].find(d => fs.existsSync(path.join(d, 'playwright/index.mjs')) && fs.existsSync(path.join(d, '@playwright/test/index.mjs'))); assert(modules);
  const { chromium } = await import(pathToFileURL(path.join(modules, 'playwright/index.mjs')).href); ({ expect } = await import(pathToFileURL(path.join(modules, '@playwright/test/index.mjs')).href)); expect = expect.configure({ timeout: 15000 });
  const browser = await chromium.connectOverCDP('http://127.0.0.1:19444', { timeout: 15000 }), cdp = await browser.newBrowserCDPSession();
  const identity = async () => { const mains = (await cdp.send('SystemInfo.getProcessInfo')).processInfo.filter(p => p.type === 'browser'); assert.equal(mains.length, 1); assert.equal(mains[0].id, report.installedBefore.pid); const v = installed(); assert.deepEqual(v, report.installedBefore); return v; };
  await identity(); const pages = browser.contexts().flatMap(c => c.pages()).filter(p => p.url().startsWith('cortex://app/')); assert.equal(pages.length, 1); [page] = pages; page.setDefaultTimeout(15000); initialURL = page.url();
  const watch = target => { target.on('pageerror', e => report.pageErrors.push(diagnostic(e))); target.on('console', m => { if (m.type() === 'error') report.consoleErrors.push(diagnostic(m.text())); }); target.on('dialog', async d => { report.unexpectedDialogs++; await d.dismiss().catch(() => {}); }); };
  for (const context of browser.contexts()) { context.pages().forEach(watch); context.on('page', watch); context.on('request', r => { if (/^https?:/.test(r.url())) report.rendererHttp.push(sha(r.url())); }); }
  await page.waitForFunction(() => window.cortex?.platform === 'darwin' && document.querySelector('.theme [aria-checked=true]')); await expect(page.locator('html')).toHaveAttribute('lang', 'en'); await expect(page.locator('html')).toHaveAttribute('data-theme', /^(light|dark)$/);
  previous = await page.evaluate(() => ({ stored: localStorage.getItem('cortex.theme'), theme: document.documentElement.dataset.theme, pref: document.querySelector('.theme [aria-checked=true]').dataset.themeValue })); assert(['system', 'light', 'dark'].includes(previous.pref)); assert(previous.stored === null || previous.stored === previous.pref); report.previousPreference = previous; oldAppearance = appearance(); assert(['true', 'false'].includes(oldAppearance));
  emptyEngine = async () => { for (const route of ['/api/connection', '/api/sessions', '/api/bots', '/api/tasks', '/api/providers', '/api/plugins', '/api/permissions']) { const r = await page.evaluate(async route => { const v = await window.cortex.request({ url: `cortex://local${route}`, method: 'GET', headers: [] }); return { status: v.status, body: JSON.parse(v.body) }; }, route); report.engineReads.push({ route, ...r }); assert.equal(r.status, 200); assert.deepEqual(r.body, route === '/api/connection' ? { mode: 'local', signedIn: false } : []); } };
  await emptyEngine(); changed = true; setAppearance('light'); ssh(`/usr/bin/osascript -e 'tell application "Cortex" to activate' -e 'tell application "System Events" to tell process "Cortex" to set size of window 1 to {960,640}'`);
  await page.goto('cortex://app/index.html#/settings?section=appearance&theme=light'); await page.reload(); await expect(page.getByTestId('settings-nav-appearance')).toHaveAttribute('aria-current', 'true');
  const names = ['System', 'Light', 'Dark'], values = names.map(n => n.toLowerCase()), group = page.locator('main .pg-themes[role=radiogroup]'), rail = page.locator('.rail .theme[role=radiogroup]'), language = page.locator('main .pg-panel').getByRole('button', { name: 'English', exact: true });
  await expect(group).toHaveAttribute('aria-label', 'Theme'); await expect(group.getByRole('radio')).toHaveCount(3); const card = pref => group.getByRole('radio', { name: names[values.indexOf(pref)], exact: true }), owner = await group.elementHandle();
  const settle = async () => { await page.evaluate(() => document.fonts.ready); await page.waitForFunction(() => document.fonts.status === 'loaded' && document.getAnimations().filter(a => a.effect?.getTiming().iterations !== Infinity).every(a => a.playState === 'finished')); };
  const snapshot = () => page.evaluate(() => {
    const g = document.querySelector('main .pg-themes'), row = el => ({ name: el.getAttribute('aria-label') || el.textContent.trim(), tag: el.tagName, type: el.getAttribute('type'), checked: el.getAttribute('aria-checked'), tabIndex: el.tabIndex });
    return { main: [...g.querySelectorAll('[role=radio]')].map(row), rail: ['system', 'light', 'dark'].map(v => { const el = document.querySelector(`.theme [data-theme-value="${v}"]`); return { name: el.getAttribute('aria-label'), checked: el.getAttribute('aria-checked'), tabIndex: el.tabIndex }; }), hidden: [...g.querySelectorAll('input')].map(el => ({ type: el.type, ariaHidden: el.getAttribute('aria-hidden'), tabIndex: el.tabIndex })), theme: document.documentElement.dataset.theme, stored: localStorage.getItem('cortex.theme'), hashTheme: new URLSearchParams(location.hash.split('?')[1]).get('theme'), osDark: matchMedia('(prefers-color-scheme: dark)').matches };
  });
  const check = async (label, pref, stored = pref) => {
    stage = label; const radios = names.map((name, i) => ({ name, checked: String(values[i] === pref), tabIndex: values[i] === pref ? 0 : -1 }));
    await expect.poll(snapshot).toEqual({ main: radios.map(r => ({ ...r, tag: 'BUTTON', type: 'button' })), rail: radios, hidden: names.map(() => ({ type: 'radio', ariaHidden: 'true', tabIndex: -1 })), theme: pref === 'system' ? osTheme : pref, stored, hashTheme: pref, osDark: osTheme === 'dark' }); await settle(); assert(await owner.evaluate(el => el.isConnected && el === document.querySelector('main .pg-themes'))); report.checks.push({ stage, pref, sameGroup: true, focus: await page.evaluate(() => { const el = document.activeElement; return { name: el.getAttribute('aria-label') || el.textContent.trim(), mainRadio: el.matches('main .pg-themes [role=radio]'), focusVisible: el.matches(':focus-visible') }; }), ...await snapshot() }); save();
  };
  await check('initial-hash-light', 'light', previous.stored);
  await card('light').click(); await check('initial-selected-card-persists', 'light');
  const geometry = async locator => locator.evaluate(el => {
    let left = 0, top = 0, right = innerWidth, bottom = innerHeight, opacity = 1;
    for (let n = el; n; n = n.parentElement) { const s = getComputedStyle(n), b = n.getBoundingClientRect(); opacity *= s.visibility === 'visible' && s.display !== 'none' ? Number(s.opacity) : 0; if ((n !== el || !(el instanceof HTMLInputElement)) && /^(auto|scroll|hidden|clip)$/.test(s.overflowX)) { left = Math.max(left, b.left + n.clientLeft); right = Math.min(right, b.left + n.clientLeft + n.clientWidth); } if ((n !== el || !(el instanceof HTMLInputElement)) && /^(auto|scroll|hidden|clip)$/.test(s.overflowY)) { top = Math.max(top, b.top + n.clientTop); bottom = Math.min(bottom, b.top + n.clientTop + n.clientHeight); } }
    const box = b => [b.left, b.top, b.right, b.bottom], inside = b => b.width > 0 && b.height > 0 && b.left >= left - .5 && b.top >= top - .5 && b.right <= right + .5 && b.bottom <= bottom + .5;
    const b = el.getBoundingClientRect(), range = document.createRange(); range.selectNodeContents(el); const ink = [...range.getClientRects()].filter(r => r.width && r.height); return { text: el.textContent, bounds: box(b), clip: [left, top, right, bottom], ink: ink.map(box), opacity, visible: inside(b) && opacity === 1 && ink.length > 0 && ink.every(inside), hit: el.contains(document.elementFromPoint(b.x + b.width / 2, b.y + b.height / 2)) };
  });
  for (const theme of ['light', 'dark']) {
    await card('system').click(); await check(`${theme}:main-pointer-system`, 'system'); setAppearance(theme === 'light' ? 'dark' : 'light'); await check(`${theme}:system-opposite-os`, 'system'); setAppearance(theme); await check(`${theme}:system-target-os`, 'system');
    await card('dark').click(); await check(`${theme}:main-pointer-dark`, 'dark'); await rail.hover(); await settle(); await rail.getByRole('radio', { name: 'Light', exact: true }).click(); await check(`${theme}:rail-pointer-light`, 'light');
    await language.focus(); await page.keyboard.press('Shift+Tab'); await expect(card('light')).toBeFocused(); await check(`${theme}:external-Tab-entry`, 'light'); await page.keyboard.press('Tab'); await expect(language).toBeFocused(); await check(`${theme}:Tab-exit`, 'light');
    await card('system').click(); await card('system').focus(); await check(`${theme}:arrows-start`, 'system');
    for (const [key, sequence] of [['ArrowRight', ['light', 'dark', 'system']], ['ArrowLeft', ['dark', 'light', 'system']], ['ArrowDown', ['light', 'dark', 'system']], ['ArrowUp', ['dark', 'light', 'system']]]) {
      for (const pref of sequence) { stage = `${theme}:${key}:${pref}`; await page.keyboard.press(key); await expect(card(pref)).toBeFocused(); await check(stage, pref); }
    }
    stage = `${theme}:Space`; await card('dark').focus(); await expect(card('dark')).toHaveAttribute('aria-checked', 'false'); await page.keyboard.press('Space'); await expect(card('dark')).toBeFocused(); await check(stage, 'dark');
    if (theme === 'light') { await page.keyboard.press('ArrowLeft'); await check('light:final-keyboard-selection', 'light'); }
    await page.locator('main .content-top').hover(); await language.focus(); await page.keyboard.press('Shift+Tab'); await expect(card(theme)).toBeFocused(); await check(`${theme}:capture`, theme);
    await expect(page.locator('html')).toHaveAttribute('lang', 'en'); await expect(page.locator('.window')).toHaveAttribute('data-sidebar', 'shown'); assert.deepEqual(await page.evaluate(() => [innerWidth, innerHeight]), [960, 640]);
    const measure = async () => { const boxes = []; for (const target of [...values.map(card), ...values.map(p => card(p).locator('.pg-theme-l')), language]) { await expect(target).toBeVisible(); const b = await geometry(target); assert(b.visible && b.hit); boxes.push(b); } return boxes; };
    const boxes = await measure(), focus = await card(theme).evaluate(el => { const s = getComputedStyle(el); return { focusVisible: el.matches(':focus-visible'), outlineStyle: s.outlineStyle, outlineWidth: s.outlineWidth, outlineColor: s.outlineColor, outlineOffset: s.outlineOffset, boxShadow: s.boxShadow }; }); assert(focus.focusVisible);
    await identity(); const win = nativeWindow(); assert.equal(appearance(), String(theme === 'dark')); const response = await fetch(`http://127.0.0.1:19445/${win.id}`, { method: 'POST', signal: AbortSignal.timeout(15000) }); assert(response.ok); const bytes = Buffer.from(await response.arrayBuffer()); assert(bytes.subarray(0, 8).equals(Buffer.from('89504e470d0a1a0a', 'hex')));
    const pixels = [bytes.readUInt32BE(16), bytes.readUInt32BE(20)]; assert(pixels[0] >= 960 && pixels[0] / 960 === pixels[1] / 640); await measure(); await expect(card(theme)).toBeFocused(); assert.equal(nativeWindow().id, win.id); assert.equal(appearance(), String(theme === 'dark')); receipt();
    const file = `appearance-theme-${theme}.png`; fs.writeFileSync(path.join(out, file), bytes, { flag: 'wx' }); report.captures.push({ file, theme, native: true, ...win, pixels, viewport: [960, 640], sha256: sha(bytes), boxes, focus, state: await snapshot() }); save();
  }
  assert.equal(report.captures.length, 2); await emptyEngine(); receipt(); report.installedAfter = await identity(); report.status = 'passed';
} catch (e) { report.status = 'failed'; report.failure = { stage, diagnostic: diagnostic(e) }; }
finally {
  const cleanup = async (name, fn) => { try { await fn(); report.cleanup[name] = true; } catch (e) { report.status = 'failed'; report.cleanup[name] = { diagnostic: diagnostic(e) }; } };
  if (changed) await cleanup('appearanceRestored', async () => { setAppearance(oldAppearance === 'true' ? 'dark' : 'light'); });
  if (changed && page && previous) await cleanup('preferenceRestored', async () => { await page.evaluate(pref => dispatchEvent(new CustomEvent('cortex-theme', { detail: pref })), previous.pref); await expect.poll(() => page.evaluate(() => ({ theme: document.documentElement.dataset.theme, stored: localStorage.getItem('cortex.theme'), pref: document.querySelector('.theme [aria-checked=true]').dataset.themeValue }))).toEqual({ ...previous, stored: previous.pref }); if (previous.stored === null) await page.evaluate(() => localStorage.removeItem('cortex.theme')); });
  if (page && initialURL && previous) await cleanup('initialRouteRestored', async () => { await page.goto(initialURL); await expect.poll(() => page.evaluate(() => ({ stored: localStorage.getItem('cortex.theme'), theme: document.documentElement.dataset.theme, pref: document.querySelector('.theme [aria-checked=true]')?.dataset.themeValue }))).toEqual(previous); });
  if (emptyEngine) await cleanup('engineUnchanged', emptyEngine);
  if (report.backend) await cleanup('zeroInference', async () => { receipt(); });
  if (report.pageErrors.length || report.consoleErrors.length || report.rendererHttp.length || report.unexpectedDialogs) report.status = 'failed';
  report.finishedAt = new Date().toISOString(); report.durationMs = Date.parse(report.finishedAt) - Date.parse(report.startedAt); report.scope = 'Installed English Settings Appearance, 960x640, two final theme captures; pointer synchronization, four arrows with wrap, Space, one Tab stop and OS-following System. No Home/End claim, API writes, provider keys or inference.'; save();
}
console.log(`Appearance theme native: ${report.status}; stage ${stage}; ${path.join(out, 'manifest.json')}`);
process.exit(report.status === 'passed' ? 0 : 1); // Coordinator owns app/helpers/tunnel/lease.
