// Frozen design route/variant IDs are immutable lookup keys; current registry IDs drive navigation.
export type FamilyDef = { id: string; section: string; title: string; route: string; v: string; source: string; usage: string; target: string; targets?: Record<string, string>; note?: string };
export const MOTIONS: [string, string, string, string][] = [
  ["components.motion.0.name","components.motion.0.behavior","components.motion.0.duration","components.motion.0.easing"],
  ["components.motion.1.name","components.motion.1.behavior","components.motion.1.duration","components.motion.1.easing"],
  ["components.motion.2.name","components.motion.2.behavior","components.motion.2.duration","components.motion.2.easing"],
  ["components.motion.3.name","components.motion.3.behavior","components.motion.3.duration","components.motion.3.easing"],
  ["components.motion.4.name","components.motion.4.behavior","components.motion.4.duration","components.motion.4.easing"],
  ["components.motion.5.name","components.motion.5.behavior","components.motion.5.duration","components.motion.5.easing"],
  ["components.motion.6.name","components.motion.6.behavior","components.motion.6.duration","components.motion.6.easing"],
  ["components.motion.7.name","components.motion.7.behavior","components.motion.7.duration","components.motion.7.easing"],
  ["components.motion.8.name","components.motion.8.behavior","components.motion.8.duration","components.motion.8.easing"],
  ["components.motion.9.name","components.motion.9.behavior","components.motion.9.duration","components.motion.9.easing"],
  ["components.motion.10.name","components.motion.10.behavior","components.motion.10.duration","components.motion.10.easing"],
  ["components.motion.11.name","components.motion.11.behavior","components.motion.11.duration","components.motion.11.easing"],
  ["components.motion.12.name","components.motion.12.behavior","components.motion.12.duration","components.motion.12.easing"],
  ["components.motion.13.name","components.motion.13.behavior","components.motion.13.duration","components.motion.13.easing"],
  ["components.motion.14.name","components.motion.14.behavior","components.motion.14.duration","components.motion.14.easing"],
  ["components.motion.15.name","components.motion.15.behavior","components.motion.15.duration","components.motion.15.easing"],
  ["components.motion.16.name","components.motion.16.behavior","components.motion.16.duration","components.motion.16.easing"],
  ["components.motion.17.name","components.motion.17.behavior","components.motion.17.duration","components.motion.17.easing"],
  ["components.motion.18.name","components.motion.18.behavior","components.motion.18.duration","components.motion.18.easing"],
  ["components.motion.19.name","components.motion.19.behavior","components.motion.19.duration","components.motion.19.easing"],
  ["components.motion.20.name","components.motion.20.behavior","components.motion.20.duration","components.motion.20.easing"],
  ["components.motion.21.name","components.motion.21.behavior","components.motion.21.duration","components.motion.21.easing"],
  ["components.motion.22.name","components.motion.22.behavior","components.motion.22.duration","components.motion.22.easing"],
  ["components.motion.23.name","components.motion.23.behavior","components.motion.23.duration","components.motion.23.easing"],
  ["components.motion.24.name","components.motion.24.behavior","components.motion.24.duration","components.motion.24.easing"],
  ["components.motion.25.name","components.motion.25.behavior","components.motion.25.duration","components.motion.25.easing"],
  ["components.motion.26.name","components.motion.26.behavior","components.motion.26.duration","components.motion.26.easing"],
  ["components.motion.27.name","components.motion.27.behavior","components.motion.27.duration","components.motion.27.easing"],
  ["components.motion.28.name","components.motion.28.behavior","components.motion.28.duration","components.motion.28.easing"],
  ["components.motion.29.name","components.motion.29.behavior","components.motion.29.duration","components.motion.29.easing"],
];
export const SECTIONS: [string, string][] = [
  ["shell","components.section.shell"],
  ["navigation","components.section.navigation"],
  ["chat","components.section.chat"],
  ["bots","components.section.bots"],
  ["work","components.section.work"],
  ["files","components.section.files"],
  ["code","components.section.code"],
  ["system","components.section.system"],
  ["forms","components.section.forms"],
  ["overlays","components.section.overlays"],
  ["status","components.section.status"],
  ["motion","components.section.motion"],
];
export const FAMILIES: FamilyDef[] = [
  {"id":"voice","section":"chat","title":"components.family.voice.title","route":"voice","v":"ecoute","source":"screens/chat/voice.tsx · Voice","usage":"components.family.voice.usage","target":".chat-voice","note":"components.family.voice.note"},
  {"id":"tools","section":"chat","title":"components.family.tools.title","route":"chat-states","v":"outil","source":"screens/chat/states.tsx · ChatStates","usage":"components.family.tools.usage","target":".thread","targets":{"vide":".home"}},
  {"id":"canvas","section":"chat","title":"components.family.canvas.title","route":"canvas","v":"document","source":"screens/chat/canvas.tsx · Canvas","usage":"components.family.canvas.usage","target":".chat-canvas-r"},
  {"id":"research","section":"chat","title":"components.family.research.title","route":"deep-research","v":"plan","source":"screens/chat/research.tsx · DeepResearch","usage":"components.family.research.usage","target":".thread","targets":{"termine":".chat-report"}},
  {"id":"sources","section":"chat","title":"components.family.sources.title","route":"chat-states","v":"sources","source":"screens/chat/states.tsx · ChatStates","usage":"components.family.sources.usage","target":".chat-cols","targets":{"vide":".home"}},
  {"id":"web","section":"chat","title":"components.family.web.title","route":"search-results","v":"resultats","source":"screens/chat/research.tsx · SearchResults","usage":"components.family.web.usage","target":".thread"},
  {"id":"images","section":"chat","title":"components.family.images.title","route":"image-gen","v":"resultats","source":"screens/chat/extras.tsx · ImageGen","usage":"components.family.images.usage","target":".thread","targets":{"edition":".chat-edit-img"}},
  {"id":"routine","section":"work","title":"components.family.routine.title","route":"automation-edit","v":"horaire","source":"screens/work/routines.tsx · AutomationEdit","usage":"components.family.routine.usage","target":".travail-form"},
  {"id":"connectors","section":"work","title":"components.family.connectors.title","route":"connectors","v":"grille","source":"screens/work/desk.tsx · Connectors","usage":"components.family.connectors.usage","target":".travail-mid","targets":{"connexion":".dialog","permissions":".dialog","erreur":".dialog"}},
  {"id":"computer","section":"work","title":"components.family.computer.title","route":"work-task","v":"apercu","source":"screens/work/home.tsx · WorkTask","usage":"components.family.computer.usage","target":".travail-task","targets":{"main":".travail-take"}},
  {"id":"permissions","section":"work","title":"components.family.permissions.title","route":"bot-settings","v":"autorisations","source":"screens/bots/team.tsx · BotSettings","usage":"components.family.permissions.usage","target":".pg-panel"},
  {"id":"pdf","section":"files","title":"components.family.pdf.title","route":"file-pdf","v":"lecture","source":"screens/files/docs.tsx · FilePdf","usage":"components.family.pdf.usage","target":".fichiers-root"},
  {"id":"pptx","section":"files","title":"components.family.pptx.title","route":"file-pptx","v":"edition","source":"screens/files/docs.tsx · FilePptx","usage":"components.family.pptx.usage","target":".fichiers-root","targets":{"presentation":".fichiers-show"}},
  {"id":"docx","section":"files","title":"components.family.docx.title","route":"file-docx","v":"commentaires","source":"screens/files/docs.tsx · FileDocx","usage":"components.family.docx.usage","target":".fichiers-root","note":"components.family.docx.note"},
  {"id":"xlsx","section":"files","title":"components.family.xlsx.title","route":"file-xlsx","v":"plage","source":"screens/files/docs.tsx · FileXlsx","usage":"components.family.xlsx.usage","target":".fichiers-root"},
  {"id":"image","section":"files","title":"components.family.image.title","route":"file-image","v":"zoom","source":"screens/files/media.tsx · ImageScreen","usage":"components.family.image.usage","target":".medias-body"},
  {"id":"code-file","section":"files","title":"components.family.code-file.title","route":"file-code","v":"affichage","source":"screens/files/media.tsx · CodeScreen","usage":"components.family.code-file.usage","target":".medias-body"},
  {"id":"audio","section":"files","title":"components.family.audio.title","route":"file-audio","v":"lecture","source":"screens/files/media.tsx · AudioScreen","usage":"components.family.audio.usage","target":".medias-stage"},
  {"id":"video","section":"files","title":"components.family.video.title","route":"file-video","v":"pause","source":"screens/files/media.tsx · VideoScreen","usage":"components.family.video.usage","target":".medias-stage"},
  {"id":"zip","section":"files","title":"components.family.zip.title","route":"file-zip","v":"arborescence","source":"screens/files/media.tsx · ZipScreen","usage":"components.family.zip.usage","target":".medias-stage"},
  {"id":"upload","section":"files","title":"components.family.upload.title","route":"upload","v":"erreurs","source":"screens/files/docs.tsx · Upload","usage":"components.family.upload.usage","target":".fichiers-uwrap"},
  {"id":"review","section":"code","title":"components.family.review.title","route":"code-review","v":"revue","source":"screens/code/lot-code.tsx · ReviewScreen","usage":"components.family.review.usage","target":".code-cols"},
  {"id":"diff","section":"code","title":"components.family.diff.title","route":"code-diff","v":"cote","source":"screens/code/lot-code.tsx · DiffScreen","usage":"components.family.diff.usage","target":".code-dpane"},
  {"id":"environments","section":"code","title":"components.family.environments.title","route":"code-env","v":"liste","source":"screens/code/lot-code.tsx · EnvScreen","usage":"components.family.environments.usage","target":".code-wrap","targets":{"demarrage":".code-cols","erreur":".code-cols"}},
  {"id":"secrets","section":"code","title":"components.family.secrets.title","route":"code-env","v":"edition","source":"screens/code/lot-code.tsx · EnvScreen","usage":"components.family.secrets.usage","target":".code-form > section:nth-child(3)","targets":{"liste":".code-wrap","demarrage":".code-cols","erreur":".code-cols"}},
  {"id":"projects","section":"system","title":"components.family.projects.title","route":"projects","v":"grille","source":"screens/system/projects.tsx · ProjectsScreen","usage":"components.family.projects.usage","target":".systeme-pgrid","targets":{"creation":".dialog","vide":".empty"}},
  {"id":"project","section":"system","title":"components.family.project.title","route":"project","v":"apercu","source":"screens/system/projects.tsx · ProjectScreen","usage":"components.family.project.usage","target":".systeme-mid"},
  {"id":"memory","section":"system","title":"components.family.memory.title","route":"memory","v":"liste","source":"screens/system/projects.tsx · MemoryScreen","usage":"components.family.memory.usage","target":".systeme-narrow"},
  {"id":"account","section":"system","title":"components.family.account.title","route":"profile","v":"profil","source":"screens/system/account.tsx · ProfileScreen","usage":"components.family.account.usage","target":".systeme-narrow","targets":{"suppression":".dialog"}},
  {"id":"payment","section":"system","title":"components.family.payment.title","route":"pricing","v":"paiement","source":"screens/system/account.tsx · PricingScreen","usage":"components.family.payment.usage","target":".systeme-mid"},
  {"id":"update","section":"system","title":"components.family.update.title","route":"update","v":"disponible","source":"screens/system/misc.tsx · UpdateScreen","usage":"components.family.update.usage","target":".systeme-upd"},
];
