#!/usr/bin/env bun
/**
 * Bundle attribution via sourcemap.
 * Decodes the VLQ mappings of a built chunk and attributes generated bytes
 * to each original source module, so we can see what actually dominates a bundle.
 *
 * Usage: bun scripts/attribute-bundle.ts <path-to-.js.map> [topN]
 */

import { readFile } from 'fs/promises';

const B64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
const B64_MAP = new Map<string, number>();
for (let i = 0; i < B64.length; i++) B64_MAP.set(B64[i], i);

/** Decode a base64 VLQ segment string into numbers. */
function decodeVLQ(segment: string): number[] {
  const result: number[] = [];
  let shift = 0;
  let value = 0;

  for (const ch of segment) {
    const digit = B64_MAP.get(ch);
    if (digit === undefined) throw new Error(`Invalid VLQ char: ${ch}`);

    const hasContinuation = digit & 32;
    value += (digit & 31) << shift;

    if (hasContinuation) {
      shift += 5;
    } else {
      const shouldNegate = value & 1;
      value >>= 1;
      result.push(shouldNegate ? -value : value);
      value = 0;
      shift = 0;
    }
  }
  return result;
}

interface SourceMap {
  sources: string[];
  mappings: string;
  sourcesContent?: (string | null)[];
}

/**
 * Walk the mappings and assign the byte-length of each generated span
 * to the source file that produced it.
 */
function attributeBytes(map: SourceMap, generatedLines: string[]): Map<string, number> {
  const bytesBySource = new Map<string, number>();
  const lines = map.mappings.split(';');

  let sourceIndex = 0;
  let origLine = 0;
  let origCol = 0;

  for (let lineNo = 0; lineNo < lines.length; lineNo++) {
    const lineContent = generatedLines[lineNo] ?? '';
    const segments = lines[lineNo].split(',').filter(Boolean);

    let genCol = 0;
    const spans: { col: number; source: string }[] = [];

    for (const seg of segments) {
      const fields = decodeVLQ(seg);
      genCol += fields[0];

      if (fields.length >= 4) {
        sourceIndex += fields[1];
        origLine += fields[2];
        origCol += fields[3];
        spans.push({ col: genCol, source: map.sources[sourceIndex] ?? '<unknown>' });
      } else {
        // Segment with no source info: terminates the previous span.
        spans.push({ col: genCol, source: '<no-source>' });
      }
    }

    // Each span runs until the next span's column (or end of line).
    for (let i = 0; i < spans.length; i++) {
      const start = spans[i].col;
      const end = i + 1 < spans.length ? spans[i + 1].col : lineContent.length;
      const len = Math.max(0, end - start);
      if (len === 0) continue;
      const key = spans[i].source;
      bytesBySource.set(key, (bytesBySource.get(key) ?? 0) + len);
    }
  }

  return bytesBySource;
}

/** Collapse a source path into a coarse package/group label. */
function groupOf(source: string): string {
  const norm = source.replace(/\\/g, '/');
  const nm = norm.lastIndexOf('node_modules/');
  if (nm !== -1) {
    const rest = norm.slice(nm + 'node_modules/'.length);
    const parts = rest.split('/');
    // Handle bun's .bun/<pkg>@<ver>/node_modules/<pkg> layout and scoped names.
    if (parts[0] === '.bun') return 'node_modules(.bun-internal)';
    return parts[0].startsWith('@') ? `${parts[0]}/${parts[1]}` : parts[0];
  }
  if (norm.includes('/src/')) {
    const after = norm.slice(norm.indexOf('/src/') + 5);
    const seg = after.split('/');
    return seg.length > 1 ? `app:src/${seg[0]}` : `app:src/${after}`;
  }
  return `other:${norm}`;
}

function fmt(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
}

async function main() {
  const mapPath = process.argv[2];
  const topN = Number(process.argv[3] ?? 30);
  if (!mapPath) {
    console.error('Usage: bun scripts/attribute-bundle.ts <path-to-.js.map> [topN]');
    process.exit(1);
  }

  const raw = await readFile(mapPath, 'utf8');
  const map: SourceMap = JSON.parse(raw);

  const jsPath = mapPath.replace(/\.map$/, '');
  let generatedLines: string[] = [];
  try {
    generatedLines = (await readFile(jsPath, 'utf8')).split('\n');
  } catch {
    console.warn(`(could not read ${jsPath}; span lengths may be truncated)`);
  }

  const perSource = attributeBytes(map, generatedLines);

  // Aggregate into groups.
  const perGroup = new Map<string, number>();
  for (const [src, bytes] of perSource) {
    const g = groupOf(src);
    perGroup.set(g, (perGroup.get(g) ?? 0) + bytes);
  }

  const totalAttributed = [...perSource.values()].reduce((a, b) => a + b, 0);

  console.log(`\n=== Bundle attribution: ${jsPath.split('/').pop()} ===`);
  console.log(`Attributed bytes: ${fmt(totalAttributed)} across ${perSource.size} source modules\n`);

  console.log(`--- Top ${topN} groups (package / app area) ---`);
  const groups = [...perGroup.entries()].sort((a, b) => b[1] - a[1]).slice(0, topN);
  const pct = (n: number) => ((n / totalAttributed) * 100).toFixed(1).padStart(5);
  for (const [g, bytes] of groups) {
    console.log(`  ${pct(bytes)}%  ${fmt(bytes).padStart(9)}  ${g}`);
  }

  console.log(`\n--- Top ${topN} individual modules ---`);
  const mods = [...perSource.entries()].sort((a, b) => b[1] - a[1]).slice(0, topN);
  for (const [src, bytes] of mods) {
    const short = src.replace(/.*node_modules\//, 'nm/').replace(/^.*\/src\//, 'src/');
    console.log(`  ${pct(bytes)}%  ${fmt(bytes).padStart(9)}  ${short}`);
  }
  console.log();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
