// Diagnostic fork of main 9548b413: two filename-overflow originals; never native acceptance.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { protocol, key, prompt, answer, reasoning, filename, model, png, fixture, validateFixture } from './files-native-backend.mjs';
const [out, root, asar, revision, membersFile] = process.argv.slice(2), repo = fs.realpathSync(process.cwd());
assert(process.argv.length === 7 && out === '/tmp/opencode/files-native-name-probe-d20a012-1' && /^\/(?:private\/)?tmp\/opencode\/desktop-files-native-d20a012-name-probe-1$/.test(root ?? '') && /^[a-f0-9]{64}$/.test(asar ?? '') && revision === 'd20a012fbb774aa9b348fe1913f85d3476430098' && path.isAbsolute(membersFile ?? ''), 'Usage: node files-name-diagnostic.mjs <fresh-output> <fresh-mac-root> <asar-sha256> <revision> <members.json>');
assert(!fs.existsSync(out) && out !== repo && !out.startsWith(`${repo}/`)); fs.mkdirSync(out);
const sha = value => createHash('sha256').update(value).digest('hex'), quote = value => `'${value.replaceAll("'", "'\\''")}'`;
const helpers = { 'files-native-backend.mjs': '5c8239ef27f8d962b4a1cd5fcfb08e34c8ba4f3871f5242fe1043f73ef90476d', 'launch-files-native.py': '7d4fdba05afe52d09a79e7775f2f1e0c234ab12ec28cda42e45be0474eae339b' };
const report = { status: 'running', baseCollectorSHA256: '9548b41317d5afd545dc086bf8b3ac463b3d477ade19a1075855202ffb05e009', diagnosticOnly: true, revision, asar, startedAt: new Date().toISOString(), invocation: { argv: process.argv.slice(1), cwd: repo, nodeVersion: process.version }, budget: { flowMs: 150000, cleanupMs: 45000, absoluteMs: 195000, rawOperationMs: 10000, captures: 2, nativeSamples: 4, originalBytes: 3145728, totalBytes: 6291456, manifestBytes: 409600, ipcCalls: 100, downloads: 0 }, capturesRequested: 0, captures: [], nativeChecks: [], checks: [], calls: [], errors: [], cleanup: {} };
const save = () => { const text = JSON.stringify(report, null, 2) + '\n'; assert(Buffer.byteLength(text) <= report.budget.manifestBytes); fs.writeFileSync(path.join(out, 'manifest.json'), text); };
const diagnostic = error => String(error?.stack ?? error).replaceAll(key, '[redacted-test-key]').replace(/\bBearer\s+[^\s"'`,]+/gi, 'Bearer [redacted]').replace(/https?:\/\/[^\s"'<>]+/g, '[network-url]').slice(0, 1200);
const ssh = command => { try { return execFileSync('ssh', ['-o', 'BatchMode=yes', '-o', 'ConnectTimeout=8', 'mac-live', command], { encoding: 'utf8', timeout: remaining(15000), maxBuffer: 1048576, stdio: ['pipe', 'pipe', 'pipe'] }).trim(); } catch (error) { if (!cleanupPhase) flowFailure ??= error; throw error; } };
const python = (source, args = []) => JSON.parse(ssh(`/usr/bin/python3 -c ${quote(source)} ${args.map(quote).join(' ')}`));
const appearance = () => ssh(`/usr/bin/osascript -e 'tell application "System Events" to tell appearance preferences to get dark mode'`);
const setAppearance = dark => assert.equal(ssh(`/usr/bin/osascript -e 'tell application "System Events" to tell appearance preferences to set dark mode to ${dark}' -e 'tell application "System Events" to tell appearance preferences to get dark mode'`), String(dark));
const backend = endpoint => { assert(['health', 'receipt'].includes(endpoint)); return JSON.parse(ssh(`/usr/bin/curl --fail --silent --show-error --max-time 5 http://127.0.0.1:9456/${endpoint}`)); };
const receipt = count => { const r = backend('receipt'); report.backendReceipt = r; save(); for (const field of ['runID', 'root', 'pid', 'scriptSHA256']) assert.equal(r[field], report.backend[field]); assert.deepEqual(r.fixture, fixture); assert.equal(r.counts.errors, 0); assert.equal(r.counts.inference, count); assert.deepEqual(r.failures, []); assert.deepEqual(r.requests, count ? [{ imageSHA256: fixture.sha256, imageBytes: fixture.bytes, modelExact: true, authorizationExact: true, messagesExact: true, toolsAbsent: true, httpStatus: 200, completed: true }] : []); };
const installed = () => { const value = JSON.parse(ssh(`/usr/bin/python3 ${quote(`${root}/launch-files-native.py`)} --inspect ${quote(root)} ${asar} ${revision}`)); assert.equal(value.membersSHA256, report.membersSHA256); assert.equal(value.membersVerified, report.memberCount); assert.equal(value.inspectorSHA256, helpers['launch-files-native.py']); return value; };
const swift = 'import Foundation; import AppKit; import CoreGraphics; let rows = (CGWindowListCopyWindowInfo([.optionOnScreenOnly], kCGNullWindowID) as! [[String: Any]]).filter { $0["kCGWindowOwnerName"] as? String == "Cortex" && $0["kCGWindowLayer"] as? Int == 0 }.map { w in ["id": w["kCGWindowNumber"]!, "pid": w["kCGWindowOwnerPID"]!, "bounds": w["kCGWindowBounds"]!, "active": NSWorkspace.shared.frontmostApplication?.processIdentifier == (w["kCGWindowOwnerPID"] as! Int32)] as [String: Any] }; print(String(data: try! JSONSerialization.data(withJSONObject: rows), encoding: .utf8)!)';
const nativeProbe = String.raw`import json,subprocess,sys; rows=json.loads(subprocess.check_output(["/usr/bin/swift","-e",sys.argv[1]],text=True,timeout=10)); dark=subprocess.run(["/usr/bin/osascript","-e",'tell application "System Events" to tell appearance preferences to get dark mode'],capture_output=True,text=True,timeout=3); print(json.dumps({"rows":rows,"appearanceStatus":dark.returncode,"appearanceStdout":dark.stdout}))`;
const nativeWindow = (theme, point) => { assert(report.nativeChecks.length < 4); const sample = python(nativeProbe, [swift]); report.nativeChecks.push({ stage, theme, point, measuredAt: new Date().toISOString(), ...sample }); save(); assert.equal(sample.appearanceStatus, 0); assert(['true\n', 'false\n'].includes(sample.appearanceStdout)); assert(Array.isArray(sample.rows)); assert.equal(sample.rows.length, 1); const w = { ...sample.rows[0], osDark: sample.appearanceStdout === 'true\n' }; assert(w.active && w.pid === report.installedBefore.pid && w.bounds.Width === 960 && w.bounds.Height === 640 && w.osDark === (theme === 'dark')); if (report.captures.length) { const first = report.captures[0]; assert.deepEqual(w, { id: first.id, pid: first.pid, bounds: first.bounds, active: first.active, osDark: first.osDark }); } return w; };
// No Save/download branch in this diagnostic; identity/IPC/deadline helpers retain main 9548b413 behavior.
let page, expect, call, verifyLists, go, session, history, previous, previousProvider, oldDark, initialHash, fresh = false, changed = false, providerChanged = false, cleanupPhase = false, stage = 'preflight', promptAttempts = 0, flowFailure, cleanupDeadline = Infinity, nameHandle, originalNameOverflow, nameStyleChanged = false;
const writes = new Set(), elapsed = () => Date.now() - Date.parse(report.startedAt);
const remaining = (ceiling = 10000) => {
  if (!cleanupPhase && flowFailure) throw flowFailure;
  const left = Math.min(cleanupPhase ? cleanupDeadline - Date.now() : 150000 - elapsed(), 195000 - elapsed());
  if (left <= 0) { const error = new Error(cleanupPhase ? 'Files cleanup deadline reached' : 'Files flow exceeded 150-second budget'); if (!cleanupPhase) flowFailure ??= error; throw error; } return Math.max(1, Math.min(ceiling, left));
};
const within = async (op, perCeil = 10000) => {
  const ms = remaining(perCeil), flow = !cleanupPhase; let timer;
  try { const value = await Promise.race([new Promise((_, reject) => { timer = setTimeout(() => { const error = new Error('Files operation deadline reached'); if (flow) flowFailure ??= error; report.timeout = { stage, phase: flow ? 'flow' : 'cleanup', limitMs: ms }; save(); reject(error); }, ms); }), Promise.resolve().then(() => { remaining(); return op(); })]); if (flow && (flowFailure || cleanupPhase)) throw flowFailure ?? new Error('Late flow result refused'); remaining(); return value; }
  catch (error) { if (flow) flowFailure ??= error; throw error; } finally { clearTimeout(timer); }
};
const budget = () => remaining(), stop = reason => { report.status = 'failed'; report.deadlineFailure = { reason, stage, elapsedMs: elapsed() }; report.cleanupIncomplete = true; save(); process.exit(1); };
const watchdog = setTimeout(() => stop('195-second absolute deadline'), Math.max(1, 195000 - elapsed()));
const mark = next => { stage = next; report.stage = next; save(); budget(); };
const preference = () => within(() => page.evaluate(() => ({ stored: localStorage.getItem('cortex.theme'), pref: document.querySelector('.theme [aria-checked=true]')?.dataset.themeValue, theme: document.documentElement.dataset.theme })));
const sessionInput = { kind: 'chat', title: 'Native saved image', model }, promptInput = { parts: [{ type: 'text', text: prompt }, { type: 'file', mime: 'image/png', filename, data: png }], reasoning: true };
save();
try {
  report.helperHashes = { [path.basename(fileURLToPath(import.meta.url))]: sha(fs.readFileSync(new URL(import.meta.url))), ...Object.fromEntries(Object.keys(helpers).map(name => [name, sha(fs.readFileSync(new URL(name, import.meta.url)))])) }; for (const [name, hash] of Object.entries(helpers)) assert.equal(report.helperHashes[name], hash); validateFixture(); report.fixture = fixture;
  const pins = fs.readFileSync(membersFile), members = JSON.parse(pins); assert.equal(members.revision, revision); assert(Array.isArray(members.members) && members.members.length >= 4 && members.members.every(m => /^(packages\/app\/dist\/|packages\/desktop\/dist\/)/.test(m.path) && /^[a-f0-9]{64}$/.test(m.sha256))); assert.equal(new Set(members.members.map(m => m.path)).size, members.members.length); report.membersSHA256 = sha(pins); report.memberCount = members.members.length;
  const hashSource = 'import hashlib,json,pathlib,sys; p=pathlib.Path(sys.argv[1]); print(json.dumps({n:hashlib.sha256((p/n).read_bytes()).hexdigest() for n in sys.argv[2:]}))'; report.rootHelperHashes = python(hashSource, [root, ...Object.keys(helpers)]); assert.deepEqual(report.rootHelperHashes, helpers);
  mark('identity'); report.installedBefore = installed(); report.backend = backend('health'); assert.equal(report.backend.protocol, protocol); assert.equal(report.backend.platform, 'darwin'); assert.equal(report.backend.port, 9456); assert.equal(report.backend.root, report.installedBefore.root); assert.equal(report.backend.scriptSHA256, helpers['files-native-backend.mjs']); receipt(0);
  const modules = [path.join(repo, 'node_modules'), '/tmp/opencode/node_modules'].find(dir => fs.existsSync(path.join(dir, '@playwright/test/index.mjs'))); assert(modules); report.playwrightVersion = JSON.parse(fs.readFileSync(path.join(modules, '@playwright/test/package.json'))).version; assert.equal(report.playwrightVersion, '1.63.0', 'Review noDefaults support before changing this pin'); const pw = await within(() => import(pathToFileURL(path.join(modules, '@playwright/test/index.mjs')).href)); expect = pw.expect.configure({ timeout: 10000 });
  const browser = await within(() => pw.chromium.connectOverCDP('http://127.0.0.1:19444', { timeout: remaining(), noDefaults: true })), cdp = await within(() => browser.newBrowserCDPSession()); report.nativeDownloadOverrides = 'none; connectOverCDP noDefaults:true';
  const pidCheck = async () => assert.deepEqual((await within(() => cdp.send('SystemInfo.getProcessInfo'))).processInfo.filter(p => p.type === 'browser').map(p => p.id), [report.installedBefore.pid]); await pidCheck();
  const pages = browser.contexts().flatMap(context => context.pages()).filter(p => p.url().startsWith('cortex://app/')); assert.equal(pages.length, 1); [page] = pages; page.setDefaultTimeout(10000); initialHash = new URL(page.url()).hash; assert.equal(initialHash, '#/home');
  await within(() => page.emulateMedia({ colorScheme: null, reducedMotion: null, forcedColors: null, contrast: null })); const fail = error => { if (report.errors.length < 20) report.errors.push(diagnostic(error)); }; page.on('pageerror', fail); page.on('console', message => { if (message.type() === 'error') fail('Renderer console error'); }); page.on('dialog', dialog => { fail('Unexpected JavaScript dialog'); void within(() => dialog.dismiss()).catch(fail); }); for (const context of browser.contexts()) { context.on('page', () => fail('Unexpected page')); context.on('request', request => { if (/^https?:/.test(request.url())) fail('Unexpected renderer HTTP request'); }); }
  const lists = ['/api/bots', '/api/sessions', '/api/projects', '/api/providers', '/api/tasks', '/api/plugins', '/api/permissions'];
  call = async (route, method = 'GET', body) => {
    budget(); assert(report.calls.length < (cleanupPhase ? 100 : 80)); const ownSession = session && route === `/api/sessions/${session.id}`, messages = session && route === `/api/sessions/${session.id}/messages`; let allowed = false, status = 200;
    if (method === 'GET') allowed = body === undefined && (lists.includes(route) || ['/api/connection', '/api/providers/fake', '/api/catalog/providers', '/api/catalog/providers/fake/models'].includes(route) || ownSession || messages);
    else if (fresh && cleanupPhase) { allowed = method === 'DELETE' && body === undefined && (ownSession || providerChanged && route === '/api/providers/fake/key'); if (providerChanged && method === 'PATCH' && route === '/api/providers/fake') { assert.deepEqual(body, { enabled: previousProvider.enabled, baseURL: null }); allowed = true; } }
    else if (fresh) {
      if (method === 'PATCH' && route === '/api/providers/fake') { assert([JSON.stringify({ enabled: true, baseURL: 'http://127.0.0.1:9456/v1' }), JSON.stringify({ enabled: false })].includes(JSON.stringify(body))); allowed = true; }
      if (method === 'PUT' && route === '/api/providers/fake/key') { assert.deepEqual(body, { key }); allowed = true; }
      if (method === 'POST' && route === '/api/sessions' && !session) { assert.deepEqual(body, sessionInput); allowed = true; status = 201; }
      if (session && method === 'POST' && route === `/api/sessions/${session.id}/prompt` && promptAttempts === 0) { assert.deepEqual(body, promptInput); promptAttempts++; allowed = true; status = 202; }
    }
    assert(allowed, 'Refused uncontrolled IPC request'); if (method !== 'GET') { const token = sha(JSON.stringify([cleanupPhase, method, route, body])); assert(!writes.has(token), 'Duplicate mutation refused'); writes.add(token); }
    const entry = { stage, route, method, status: null, state: 'pending' }; report.calls.push(entry); save();
    const response = await within(() => page.evaluate(async ({ route, method, body }) => { const r = await window.cortex.request({ url: `cortex://local${route}`, method, headers: body === undefined ? [] : [['content-type', 'application/json']], body: body === undefined ? undefined : JSON.stringify(body) }); return { status: r.status, data: JSON.parse(r.body) }; }, { route, method, body })); Object.assign(entry, { status: response.status, state: 'returned', ...(Array.isArray(response.data) ? { count: response.data.length } : {}) }); save(); assert(response.status === status || cleanupPhase && method === 'DELETE' && response.status === 404, `Unexpected IPC status: ${method} ${route}`); return response.data;
  };
  verifyLists = async () => { for (const route of lists) assert.deepEqual(await call(route), cleanupPhase && providerChanged && route === '/api/providers' ? [previousProvider] : []); assert.deepEqual(await call('/api/connection'), { mode: 'local', signedIn: false }); };
  await within(() => page.waitForFunction(() => window.cortex?.platform === 'darwin' && document.querySelector('.theme [aria-checked=true]'), undefined, { timeout: remaining() })); await expect(page.locator('html')).toHaveAttribute('lang', 'en', { timeout: remaining() }); mark('fresh-profile'); await verifyLists(); previousProvider = await call('/api/providers/fake'); assert.deepEqual(previousProvider, { providerID: 'fake', enabled: true, hasKey: false }); fresh = true;
  const providers = await call('/api/catalog/providers'), models = await call('/api/catalog/providers/fake/models'); assert.deepEqual(providers.map(p => [p.id, p.api, p.npm, p.modelCount]), [['fake', 'http://127.0.0.1:9456/v1', '@ai-sdk/openai-compatible', 1]]); assert.deepEqual(models.map(m => [m.providerID, m.id, m.capabilities.imageInput, m.tool_call]), [['fake', 'reasoner', true, false]]);
  await within(() => page.waitForFunction(() => document.documentElement.dataset.theme === (document.querySelector('.theme [aria-checked=true]')?.dataset.themeValue === 'system' ? matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light' : document.querySelector('.theme [aria-checked=true]')?.dataset.themeValue), undefined, { timeout: remaining() })); previous = await preference(); oldDark = appearance(); assert(['true', 'false'].includes(oldDark) && ['system', 'light', 'dark'].includes(previous.pref)); report.previous = { ...previous, nativeDark: oldDark, hash: initialHash };
  go = async hash => { assert(hash === initialHash || session && hash === `#/chat?id=${session.id}`); await within(() => page.evaluate(value => { history.pushState(null, '', value); dispatchEvent(new Event('cortex-variant')); }, hash)); await expect(page).toHaveURL(`cortex://app/index.html${hash}`, { timeout: remaining() }); };
  mark('controlled-image'); providerChanged = true; await call('/api/providers/fake', 'PATCH', { enabled: true, baseURL: 'http://127.0.0.1:9456/v1' }); const saved = await call('/api/providers/fake/key', 'PUT', { key }); assert.deepEqual(saved, { providerID: 'fake', enabled: true, hasKey: true, keyHint: key.slice(-4), baseURL: 'http://127.0.0.1:9456/v1' });
  session = await call('/api/sessions', 'POST', sessionInput); report.session = session; save(); assert(/^ses_[0-9a-f]{32,}$/.test(session.id) && session.kind === 'chat' && session.title === sessionInput.title && session.parentID === undefined && session.botID === undefined && session.projectID === undefined && session.directory === undefined); assert.deepEqual(session.model, model);
  const accepted = await call(`/api/sessions/${session.id}/prompt`, 'POST', promptInput); assert(/^msg_[0-9a-f]{32,}$/.test(accepted.messageID)); await expect.poll(async () => { history = await call(`/api/sessions/${session.id}/messages`); return history.length === 2 && Number.isFinite(history[1]?.info.time.completed); }, { intervals: [100, 250, 500], timeout: remaining() }).toBe(true); budget();
  assert.deepEqual(history.map(m => m.info.role), ['user', 'assistant']); assert(history.every(m => m.info.sessionID === session.id && m.info.agent === 'build' && m.info.error === undefined && m.parts.every(p => p.sessionID === session.id && p.messageID === m.info.id && ['text', 'file', 'reasoning', 'step-start', 'step-finish'].includes(p.type)))); assert.equal(history[0].info.id, accepted.messageID);
  assert.deepEqual(history[0].parts.map(({ id: _id, sessionID: _sid, messageID: _mid, ...part }) => part), promptInput.parts); assert.deepEqual(history[1].parts.filter(p => ['text', 'reasoning'].includes(p.type)).map(p => [p.type, p.text]), [['reasoning', reasoning], ['text', answer]]); assert.deepEqual(history[1].parts.filter(p => p.type === 'step-finish').map(p => p.reason), ['stop']);
  const part = history[0].parts.find(p => p.type === 'file'); assert(/^prt_[0-9a-f]{32,}$/.test(part.id)); report.savedImage = { sessionID: session.id, messageID: accepted.messageID, partID: part.id, historySHA256: sha(JSON.stringify(history)), fileSHA256: fixture.sha256 }; save(); receipt(1);
  const disabled = await call('/api/providers/fake', 'PATCH', { enabled: false }); assert.deepEqual(disabled, { ...saved, enabled: false }); const settledSession = await call(`/api/sessions/${session.id}`);
  changed = true; ssh('/usr/bin/osascript -e \'tell application "Cortex" to activate\' -e \'tell application "System Events" to tell process "Cortex" to set size of window 1 to {960,640}\''); await page.locator('.rail .theme [aria-checked=true]').focus({ timeout: remaining() }); await within(() => page.keyboard.press('Home')); await expect.poll(preference, { timeout: remaining() }).toEqual({ stored: 'dark', pref: 'dark', theme: 'dark' }); await within(() => page.keyboard.press('ArrowLeft')); await expect.poll(async () => (await preference()).pref, { timeout: remaining() }).toBe('system');
  const viewer = page.locator('main .medias-image-live'), stageView = viewer.locator('.medias-view'), image = stageView.locator('img'), fit = viewer.getByRole('button', { name: 'Fit', exact: true }), download = viewer.getByRole('button', { name: 'Download', exact: true });
  const settle = async () => { await within(() => page.evaluate(() => document.fonts.ready)); await within(() => page.waitForFunction(() => document.fonts.status === 'loaded' && document.getAnimations().filter(a => a.effect?.getTiming().iterations !== Infinity).every(a => a.playState === 'finished'), undefined, { timeout: remaining() })); };
  const ready = async zoom => {
    await expect(viewer).toBeVisible({ timeout: remaining() }); await expect(image).toBeVisible({ timeout: remaining() }); await expect(viewer.locator('.medias-name')).toHaveText(filename, { timeout: remaining() }); await expect(viewer.locator('.medias-zoomv')).toHaveText(`${zoom}% of Fit`, { timeout: remaining() }); await expect(download).toBeEnabled({ timeout: remaining() }); await expect(viewer.locator('.medias-kv > span:last-child')).toHaveText(['120 × 180', 'PNG', '393 bytes'], { timeout: remaining() });
    await expect.poll(() => within(() => image.evaluate(img => [img.complete, img.naturalWidth, img.naturalHeight])), { timeout: remaining() }).toEqual([true, 120, 180]);
    const sample = await within(() => image.evaluate(img => { const c = document.createElement('canvas'); c.width = 120; c.height = 180; const ctx = c.getContext('2d'); ctx.drawImage(img, 0, 0); return { dimensions: [img.naturalWidth, img.naturalHeight], complete: img.complete, protocol: new URL(img.src).protocol, scale: img.style.scale, translate: img.style.translate, rgba: [30, 90, 150].map(y => [...ctx.getImageData(60, y, 1, 1).data]) }; })); assert.deepEqual(sample.dimensions, [120, 180]); assert(sample.complete && sample.protocol === 'blob:' && sample.scale === String(zoom / 100)); assert.deepEqual(sample.rgba, fixture.rgb.map(rgb => [...rgb, 255])); return sample;
  };
  const geometry = target => within(() => target.evaluate(el => {
    const clip = start => { let l = 0, t = 0, r = innerWidth, b = innerHeight, opacity = 1; for (let n = start; n; n = n.parentElement) { const s = getComputedStyle(n), q = n.getBoundingClientRect(); opacity *= s.visibility === 'visible' && s.display !== 'none' ? +s.opacity : 0; if (!['inline', 'contents'].includes(s.display)) { if (/^(auto|scroll|hidden|clip)$/.test(s.overflowX)) { l = Math.max(l, q.left + n.clientLeft); r = Math.min(r, q.left + n.clientLeft + n.clientWidth); } if (/^(auto|scroll|hidden|clip)$/.test(s.overflowY)) { t = Math.max(t, q.top + n.clientTop); b = Math.min(b, q.top + n.clientTop + n.clientHeight); } } } return { edges: [l, t, r, b], opacity }; };
    const box = r => [r.left, r.top, r.right, r.bottom], fits = (r, c) => r.width > 0 && r.height > 0 && r.left >= c.edges[0] - .5 && r.top >= c.edges[1] - .5 && r.right <= c.edges[2] + .5 && r.bottom <= c.edges[3] + .5, q = el.getBoundingClientRect(), boundsClip = clip(el.parentElement), ink = [];
    const walker = document.createTreeWalker(el, NodeFilter.SHOW_TEXT); for (let node; (node = walker.nextNode());) { if (!node.textContent.trim() || node.parentElement.closest('[aria-hidden=true]')) continue; const range = document.createRange(); range.selectNodeContents(node); const c = clip(node.parentElement); for (const r of range.getClientRects()) if (r.width && r.height) ink.push({ bounds: box(r), clip: c.edges, visible: fits(r, c) && c.opacity === 1 }); }
    return { text: (el.getAttribute('aria-label') || el.textContent).slice(0, 500), bounds: box(q), clip: boundsClip.edges, ink, visible: fits(q, boundsClip) && boundsClip.opacity === 1 && ink.length <= 40 && (ink.length > 0 ? ink.every(r => r.visible) : el.matches('button[aria-label],[role=img][aria-label]')), hit: el.contains(document.elementFromPoint(q.x + q.width / 2, q.y + q.height / 2)) };
  }));
  const nameProbe = () => within(() => nameHandle.evaluate(el => {
    const s = getComputedStyle(el), box = r => [r.left, r.top, r.right, r.bottom], range = document.createRange(); range.selectNodeContents(el);
    const properties = ['display', 'font', 'font-family', 'font-size', 'font-weight', 'font-style', 'font-stretch', 'line-height', 'letter-spacing', 'font-kerning', 'font-feature-settings', 'font-variation-settings', 'font-variant-ligatures', 'font-optical-sizing', 'text-rendering', '-webkit-font-smoothing', 'color', 'text-shadow', 'direction', 'writing-mode', 'vertical-align', 'white-space', 'overflow', 'overflow-x', 'overflow-y', 'max-height'];
    const canvas = document.createElement('canvas'), ctx = canvas.getContext('2d'); ctx.font = s.font; ctx.textBaseline = 'alphabetic'; ctx.direction = s.direction; ctx.letterSpacing = s.letterSpacing; const m = ctx.measureText(el.textContent);
    const metrics = Object.fromEntries(['width', 'actualBoundingBoxLeft', 'actualBoundingBoxRight', 'actualBoundingBoxAscent', 'actualBoundingBoxDescent', 'fontBoundingBoxAscent', 'fontBoundingBoxDescent', 'emHeightAscent', 'emHeightDescent', 'alphabeticBaseline'].map(key => [key, m[key] ?? null]));
    const clipChain = []; for (let n = el; n; n = n.parentElement) { const c = getComputedStyle(n); clipChain.push({ tag: n.tagName, className: n.className, bounds: box(n.getBoundingClientRect()), display: c.display, overflowX: c.overflowX, overflowY: c.overflowY, client: [n.clientLeft, n.clientTop, n.clientWidth, n.clientHeight], scroll: [n.scrollLeft, n.scrollTop, n.scrollWidth, n.scrollHeight], clipPath: c.clipPath, transform: c.transform, zoom: c.zoom, opacity: c.opacity, visibility: c.visibility }); }
    return { text: el.textContent, owner: el.isConnected && el === document.querySelector('main .medias-image-live .medias-name'), style: el.getAttribute('style'), computed: Object.fromEntries(properties.map(key => [key, s.getPropertyValue(key)])), bounds: box(el.getBoundingClientRect()), offset: [el.offsetLeft, el.offsetTop, el.offsetWidth, el.offsetHeight], client: [el.clientLeft, el.clientTop, el.clientWidth, el.clientHeight], scroll: [el.scrollLeft, el.scrollTop, el.scrollWidth, el.scrollHeight], ranges: [...range.getClientRects()].map(box), clipChain, canvas: { requestedFont: s.font, resolvedFont: ctx.font, letterSpacing: ctx.letterSpacing, baseline: ctx.textBaseline, metrics }, viewport: [innerWidth, innerHeight, devicePixelRatio], layout: [...document.querySelectorAll('body *')].map(n => [n.tagName, box(n.getBoundingClientRect())]) };
  }));
  let baselineLayout, baselineName;
  const capture = async label => {
    const theme = 'light', zoom = 100, focus = fit; mark(`${theme}:${label}:capture`); await expect(page.locator('.toast, .tip, [role=menu]')).toHaveCount(0, { timeout: remaining() }); await settle(); await expect(focus).toBeFocused({ timeout: remaining() }); assert(await within(() => focus.evaluate(el => el.matches(':focus-visible'))));
    const renderer = async () => { await expect(page.locator('.window')).toHaveAttribute('data-sidebar', 'shown', { timeout: remaining() }); await expect(page.locator('html')).toHaveAttribute('data-theme', theme, { timeout: remaining() }); assert.deepEqual(await within(() => page.evaluate(() => [innerWidth, innerHeight, matchMedia('(prefers-color-scheme: dark)').matches])), [960, 640, false]); }; await renderer();
    const measure = async () => { const boxes = []; for (const target of [viewer.locator('.medias-name'), viewer.locator('.medias-bar'), stageView, viewer.locator('.medias-exif'), download]) { const g = await geometry(target); boxes.push(g); if (!g.hit || boxes.length > 1 && !g.visible) { report.failedGeometry = boxes; save(); assert.fail('Non-filename target clipped or target covered'); } } return boxes; }; // Filename range visibility is recorded, never accepted/re-toleranced by this diagnostic.
    const measuredName = async () => {
      const { layout, ...name } = await nameProbe(), sample = { ...name, layoutSHA256: sha(JSON.stringify(layout)), layoutNodes: layout.length, geometry: await geometry(viewer.locator('.medias-name')) }; const samples = report.nameSamples ??= []; assert(samples.length < 4); samples.push(sample);
      if (!baselineLayout) { baselineLayout = layout; baselineName = name; report.baselineLayout = layout; } else if (JSON.stringify(layout) !== JSON.stringify(baselineLayout)) report.changedLayout = layout; save(); assert(name.owner && name.text === filename);
      assert.deepEqual(layout, baselineLayout, 'DOM geometry changed'); for (const key of ['bounds', 'ranges', 'offset', 'client', 'scroll', 'viewport', 'canvas']) assert.deepEqual(name[key], baselineName[key], `Filename ${key} changed`);
      const expected = nameStyleChanged ? 'visible' : 'auto'; assert.deepEqual(name.computed, { ...baselineName.computed, overflow: expected, 'overflow-x': expected, 'overflow-y': expected }); assert.deepEqual(name.clipChain, baselineName.clipChain.map((node, i) => i ? node : { ...node, overflowX: expected, overflowY: expected })); return sample;
    };
    const boxes = await measure(), imageSample = await ready(zoom), nameSample = await measuredName(), win = nativeWindow(theme, 'before'); await pidCheck(); budget(); assert(report.capturesRequested < 2); const shot = { file: `${label}-light.png`, requestedAt: new Date().toISOString(), theme, native: true, diagnosticOnly: true, ...win, boxes, imageSample, nameSample, focus: await within(() => focus.evaluate(el => ({ visible: el.matches(':focus-visible'), outline: getComputedStyle(el).outline, boxShadow: getComputedStyle(el).boxShadow }))), status: 'requested' }; report.capturesRequested++; report.captures.push(shot); save();
    const signal = AbortSignal.timeout(remaining(15000)), response = await within(() => fetch(`http://127.0.0.1:19445/${win.id}`, { method: 'POST', signal }), 15000); shot.httpStatus = response.status; save(); assert(response.ok); const bytes = Buffer.from(await within(() => response.arrayBuffer(), 15000)); fs.writeFileSync(path.join(out, shot.file), bytes, { flag: 'wx' }); Object.assign(shot, { bytes: bytes.length, sha256: sha(bytes), status: 'original-retained' }); save();
    assert(bytes.length <= 3145728 && report.captures.reduce((sum, c) => sum + (c.bytes ?? 0), 0) <= 6291456); assert(bytes.length >= 24 && bytes.subarray(0, 8).equals(Buffer.from('89504e470d0a1a0a', 'hex'))); shot.pixels = [bytes.readUInt32BE(16), bytes.readUInt32BE(20)]; assert(shot.pixels[0] >= 960 && shot.pixels[0] / 960 === shot.pixels[1] / 640); assert.deepEqual(shot.pixels, report.captures[0].pixels);
    shot.afterBoxes = await measure(); shot.afterName = await measuredName(); assert.deepEqual(shot.afterName, nameSample); await renderer(); assert.deepEqual(await ready(zoom), imageSample); await expect(focus).toBeFocused({ timeout: remaining() }); assert.deepEqual(nativeWindow(theme, 'after'), win); await pidCheck(); shot.status = 'observed'; shot.finishedAt = new Date().toISOString(); save(); mark(`${theme}:${label}:retained`);
  };
  await go(`#/chat?id=${session.id}`); mark('light:open-saved-image'); setAppearance(false); await expect.poll(preference, { timeout: remaining() }).toEqual({ stored: 'system', pref: 'system', theme: 'light' }); assert.deepEqual(await call('/api/providers/fake'), disabled);
  const open = page.getByRole('button', { name: `Open ${filename}`, exact: true }); await expect(open).toHaveCount(1, { timeout: remaining() }); await expect(open).toBeEnabled({ timeout: remaining() }); await expect(page.getByPlaceholder('Reply to Cortex', { exact: true })).toHaveValue('', { timeout: remaining() }); await open.press('Enter', { timeout: remaining() });
  const expectedHash = `#/file-image?${new URLSearchParams({ session: session.id, message: accepted.messageID, part: part.id })}`; await expect(page).toHaveURL(`cortex://app/index.html${expectedHash}`, { timeout: remaining() }); await ready(100); await fit.focus({ timeout: remaining() }); await viewer.locator('.medias-name').hover({ timeout: remaining() }); await settle();
  nameHandle = await within(() => viewer.locator('.medias-name').elementHandle()); assert(nameHandle); originalNameOverflow = await within(() => nameHandle.evaluate(el => ({ style: el.getAttribute('style'), value: el.style.overflow, priority: el.style.getPropertyPriority('overflow'), x: getComputedStyle(el).overflowX, y: getComputedStyle(el).overflowY }))); report.originalNameOverflow = originalNameOverflow; save(); assert.deepEqual([originalNameOverflow.x, originalNameOverflow.y], ['auto', 'auto']); await capture('name-clipped');
  mark('light:temporary-overflow'); nameStyleChanged = true; report.mutation = { property: 'overflow', value: 'visible', diagnosticOnly: true }; save(); await within(() => nameHandle.evaluate(el => { if (!el.isConnected || el !== document.querySelector('main .medias-image-live .medias-name')) throw Error('Filename owner changed'); el.style.overflow = 'visible'; })); await capture('name-unclipped');
  mark('read-only-viewer'); assert.deepEqual(await call(`/api/sessions/${session.id}/messages`), history); assert.deepEqual(await call(`/api/sessions/${session.id}`), settledSession); assert.deepEqual(await call('/api/providers/fake'), disabled); assert.equal(report.capturesRequested, 2); assert.equal(report.nativeChecks.length, 4); assert.equal(report.captures.filter(c => c.status === 'observed').length, 2); assert.equal(promptAttempts, 1); mark('flow-complete'); report.status = 'observed';
} catch (error) { flowFailure ??= error; report.status = 'failed'; report.failure = { stage, diagnostic: diagnostic(error) }; }
finally {
  report.flowDurationMs = elapsed(); cleanupPhase = true; cleanupDeadline = Math.min(Date.now() + 45000, Date.parse(report.startedAt) + 195000); report.cleanupStartedAt = new Date().toISOString(); report.cleanupDeadline = new Date(cleanupDeadline).toISOString(); save();
  const cleanupWatchdog = setTimeout(() => stop('45-second cleanup deadline'), Math.max(1, cleanupDeadline - Date.now()));
  const clean = async (name, fn) => { try { remaining(); await fn(); remaining(); report.cleanup[name] = true; } catch (error) { report.status = 'failed'; report.cleanup[name] = { diagnostic: diagnostic(error) }; } save(); };
  if (nameStyleChanged && nameHandle && originalNameOverflow) await clean('nameStyleRestored', async () => { report.nameRestored = await within(() => nameHandle.evaluate((el, original) => { if (!el.isConnected || el !== document.querySelector('main .medias-image-live .medias-name')) throw Error('Filename owner changed'); if (original.style === null) el.removeAttribute('style'); else el.setAttribute('style', original.style); return { style: el.getAttribute('style'), value: el.style.overflow, priority: el.style.getPropertyPriority('overflow'), x: getComputedStyle(el).overflowX, y: getComputedStyle(el).overflowY }; }, originalNameOverflow)); assert.deepEqual(report.nameRestored, originalNameOverflow); });
  if (session?.id && /^ses_[0-9a-f]{32,}$/.test(session.id)) await clean('ownedChatRemoved', () => call(`/api/sessions/${session.id}`, 'DELETE'));
  if (providerChanged) { await clean('fixtureKeyRemoved', async () => { const value = await call('/api/providers/fake/key', 'DELETE'); assert(value.hasKey === false && value.keyHint === undefined); }); await clean('providerValuesRestored', async () => { assert.deepEqual(await call('/api/providers/fake', 'PATCH', { enabled: previousProvider.enabled, baseURL: null }), previousProvider); report.providerDocumentRetained = true; }); }
  if (changed) await clean('nativeAppearanceRestored', async () => setAppearance(oldDark === 'true'));
  if (changed && previous) await clean('themePreferenceRestored', async () => { await within(() => page.evaluate(pref => dispatchEvent(new CustomEvent('cortex-theme', { detail: pref })), previous.pref)); await expect.poll(async () => { const { stored: _stored, ...value } = await preference(); return value; }, { timeout: remaining() }).toEqual({ pref: previous.pref, theme: previous.theme }); await within(() => page.evaluate(stored => { if (stored === null) localStorage.removeItem('cortex.theme'); else localStorage.setItem('cortex.theme', stored); }, previous.stored)); });
  if (go) await clean('routeRestored', async () => { await go(initialHash); if (previous) await expect.poll(preference, { timeout: remaining() }).toEqual(previous); });
  if (fresh && verifyLists) await clean('controlledListsRestored', verifyLists);
  if (report.backend) await clean('controlledInferenceOnly', async () => receipt(promptAttempts));
  if (report.installedBefore) await clean('installedAfter', async () => { report.installedAfter = installed(); assert.deepEqual(report.installedAfter, report.installedBefore); });
  if (Date.now() >= cleanupDeadline || elapsed() >= 195000) report.cleanupIncomplete = true; if (report.errors.length || report.cleanupIncomplete) report.status = 'failed'; report.finishedAt = new Date().toISOString(); report.durationMs = elapsed(); report.scope = 'Diagnostic only: two light native filename originals, baseline then temporary overflow:visible. Nominal Range visibility recorded without acceptance or tolerance change. Coordinator pixel comparison determines glyph clipping; canvas metrics imply no CSS baseline. No Save/dark/zoom/app changes.'; save(); clearTimeout(cleanupWatchdog); clearTimeout(watchdog);
}
console.log(`Files filename diagnostic: ${report.status}; ${stage}; ${path.join(out, 'manifest.json')}`); process.exit(report.status === 'observed' ? 0 : 1);
