// Prepared only; coordinator admits the future Memory package, lease, execution and original pixels.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { pathToFileURL } from 'node:url';
import { protocol } from './terminal-state-native-backend.mjs';
const [out, root, asar, revision, membersFile] = process.argv.slice(2), repo = fs.realpathSync(process.cwd());
assert(process.argv.length === 7 && /^\/tmp\/opencode\/memory-native-[\w.-]+$/.test(out ?? '') && /^\/(?:private\/)?tmp\/opencode\/desktop-terminal-state-memory-[\w.-]+$/.test(root ?? '') && /^[a-f0-9]{64}$/.test(asar ?? '') && /^[a-f0-9]{40}$/.test(revision ?? '') && path.isAbsolute(membersFile ?? ''), 'Usage: node memory-native.mjs <fresh-output> <fresh-mac-root> <asar-sha256> <revision> <members.json>');
assert(!fs.existsSync(out) && out !== repo && !out.startsWith(`${repo}/`)); fs.mkdirSync(out);
const sha = v => createHash('sha256').update(v).digest('hex'), quote = v => `'${v.replaceAll("'", "'\\''")}'`;
const helpers = { 'terminal-state-native-backend.mjs': 'd22fcbe2287a7898452778ea58d665f0742f4a1d4d580ec7c237dc10cfc70d4d', 'launch-terminal-state-native.py': '4aec6651e6178bf890a299551497514f5159342a8f94db8972515c000fc10257', 'cleanup-terminal-state-native.py': 'c46f218f17bcda2ba031fe8f2959f9f8e18dda379a7edcd076b01be0c881c08a' };
const report = { status: 'running', revision, asar, startedAt: new Date().toISOString(), invocation: { argv: process.argv.slice(1), cwd: repo, nodeVersion: process.version }, budget: { captures: 4, originalBytes: 8388608, totalBytes: 33554432, flowMs: 120000, manifestBytes: 409600 }, capturesRequested: 0, captures: [], checks: [], calls: [], errors: [], cleanup: {} };
const save = () => { const text = JSON.stringify(report, null, 2) + '\n'; assert(Buffer.byteLength(text) <= report.budget.manifestBytes); fs.writeFileSync(path.join(out, 'manifest.json'), text); };
const diagnostic = e => String(e?.stack ?? e).replace(/\bBearer\s+[^\s"'`,]+/gi, 'Bearer [redacted]').replace(/https?:\/\/[^\s"'<>]+/g, '[network-url]').slice(0, 1200);
const ssh = command => execFileSync('ssh', ['-o', 'BatchMode=yes', '-o', 'ConnectTimeout=8', 'mac-live', command], { encoding: 'utf8', timeout: 15000, maxBuffer: 1048576, stdio: ['pipe', 'pipe', 'pipe'] }).trim();
const appearance = () => ssh(`/usr/bin/osascript -e 'tell application "System Events" to tell appearance preferences to get dark mode'`);
const setAppearance = dark => assert.equal(ssh(`/usr/bin/osascript -e 'tell application "System Events" to tell appearance preferences to set dark mode to ${dark}' -e 'tell application "System Events" to tell appearance preferences to get dark mode'`), String(dark));
const backend = endpoint => JSON.parse(ssh(`/usr/bin/curl --fail --silent --show-error --max-time 5 http://127.0.0.1:9456/${endpoint}`));
const receipt = () => { const r = backend('receipt'); for (const k of ['runID', 'root', 'pid', 'scriptSHA256']) assert.equal(r[k], report.backend[k]); assert.deepEqual(r.requests, []); assert.deepEqual(r.failures, []); assert.equal(r.counts.errors, 0); report.backendReceipt = r; };
const installed = () => { const r = JSON.parse(ssh(`/usr/bin/python3 ${quote(`${root}/launch-terminal-state-native.py`)} --inspect ${quote(root)} ${asar} ${revision}`)); assert.equal(r.membersSHA256, report.membersSHA256); assert.equal(r.membersVerified, report.memberCount); assert.equal(r.inspectorSHA256, helpers['launch-terminal-state-native.py']); return r; };
const swift = 'import Foundation; import AppKit; import CoreGraphics; let rows = (CGWindowListCopyWindowInfo([.optionOnScreenOnly], kCGNullWindowID) as! [[String: Any]]).filter { $0["kCGWindowOwnerName"] as? String == "Cortex" && $0["kCGWindowLayer"] as? Int == 0 }.map { w in ["id": w["kCGWindowNumber"]!, "pid": w["kCGWindowOwnerPID"]!, "bounds": w["kCGWindowBounds"]!, "active": NSWorkspace.shared.frontmostApplication?.processIdentifier == (w["kCGWindowOwnerPID"] as! Int32), "osDark": UserDefaults.standard.string(forKey: "AppleInterfaceStyle") == "Dark"] as [String: Any] }; print(String(data: try! JSONSerialization.data(withJSONObject: rows), encoding: .utf8)!)';
const nativeWindow = theme => { const rows = JSON.parse(ssh(`/usr/bin/swift -e ${quote(swift)}`)); assert.equal(rows.length, 1); const w = rows[0]; assert(w.active && w.pid === report.installedBefore.pid && w.bounds.Width === 960 && w.bounds.Height === 640 && w.osDark === (theme === 'dark')); if (report.captures.length) assert.equal(w.id, report.captures[0].id); return w; };
let page, expect, call, verifyEmpty, go, bot, note, previous, oldDark, initialHash, fresh = false, changed = false, settingsTouched = false, cleanupPhase = false, stage = 'preflight';
const mark = next => { stage = next; report.stage = next; save(); assert(Date.now() - Date.parse(report.startedAt) < report.budget.flowMs, 'Memory flow exceeded 120-second budget'); };
const preference = () => page.evaluate(() => ({ stored: localStorage.getItem('cortex.theme'), pref: document.querySelector('.theme [aria-checked=true]')?.dataset.themeValue, theme: document.documentElement.dataset.theme }));
save();
try {
  report.helperHashes = Object.fromEntries(['memory-native.mjs', ...Object.keys(helpers)].map(n => [n, sha(fs.readFileSync(new URL(n, import.meta.url)))])); for (const [n, h] of Object.entries(helpers)) assert.equal(report.helperHashes[n], h);
  const pins = fs.readFileSync(membersFile), members = JSON.parse(pins); assert.equal(members.revision, revision); assert(Array.isArray(members.members) && members.members.length >= 4 && members.members.every(m => /^(packages\/app\/dist\/|packages\/desktop\/dist\/)/.test(m.path) && /^[a-f0-9]{64}$/.test(m.sha256))); assert.equal(new Set(members.members.map(m => m.path)).size, members.members.length); report.membersSHA256 = sha(pins); report.memberCount = members.members.length;
  const hashSource = 'import hashlib,json,pathlib,sys; p=pathlib.Path(sys.argv[1]); print(json.dumps({n:hashlib.sha256((p/n).read_bytes()).hexdigest() for n in sys.argv[2:]}))'; report.rootHelperHashes = JSON.parse(ssh(`/usr/bin/python3 -c ${quote(hashSource)} ${quote(root)} ${Object.keys(helpers).map(quote).join(' ')}`)); assert.deepEqual(report.rootHelperHashes, helpers);
  mark('identity'); report.installedBefore = installed(); report.backend = backend('health'); assert.equal(report.backend.protocol, protocol); assert.equal(report.backend.platform, 'darwin'); assert.equal(report.backend.port, 9456); assert.equal(report.backend.root, report.installedBefore.root); assert.equal(report.backend.scriptSHA256, helpers['terminal-state-native-backend.mjs']); receipt();
  const modules = [path.join(repo, 'node_modules'), '/tmp/opencode/node_modules'].find(d => fs.existsSync(path.join(d, '@playwright/test/index.mjs'))); assert(modules); const pw = await import(pathToFileURL(path.join(modules, '@playwright/test/index.mjs')).href); expect = pw.expect.configure({ timeout: 10000 });
  const browser = await pw.chromium.connectOverCDP('http://127.0.0.1:19444', { timeout: 10000 }), cdp = await browser.newBrowserCDPSession();
  const pidCheck = async () => assert.deepEqual((await cdp.send('SystemInfo.getProcessInfo')).processInfo.filter(p => p.type === 'browser').map(p => p.id), [report.installedBefore.pid]); await pidCheck();
  const pages = browser.contexts().flatMap(c => c.pages()).filter(p => p.url().startsWith('cortex://app/')); assert.equal(pages.length, 1); [page] = pages; page.setDefaultTimeout(10000); initialHash = new URL(page.url()).hash; assert(!/[?&](theme|preview|shot)\b/.test(initialHash));
  await page.emulateMedia({ colorScheme: null, reducedMotion: null, forcedColors: null, contrast: null }); const fail = e => { if (report.errors.length < 20) report.errors.push(diagnostic(e)); };
  page.on('pageerror', fail); page.on('console', m => { if (m.type() === 'error') fail('Renderer console error'); }); page.on('dialog', async d => { fail('Unexpected dialog'); await d.dismiss(); }); for (const c of browser.contexts()) { c.on('page', () => fail('Unexpected page')); c.on('request', r => { if (/^https?:/.test(r.url())) fail('Unexpected renderer HTTP request'); }); }
  const lists = ['/api/bots', '/api/sessions', '/api/projects', '/api/providers', '/api/tasks', '/api/plugins', '/api/permissions'];
  call = async (route, method = 'GET', body, statuses = [200]) => {
    assert(report.calls.length < 180); const ownBot = bot && route === `/api/bots/${bot.id}`, ownMemory = bot && route === `/api/bots/${bot.id}/memory`;
    assert(method === 'GET' && (lists.includes(route) || ['/api/settings', '/api/connection'].includes(route) || ownBot || ownMemory) || fresh && (method === 'POST' && (route === '/api/bots' && !bot || ownMemory && !note) || method === 'DELETE' && ownBot || cleanupPhase && method === 'PUT' && route === '/api/settings' && JSON.stringify(body) === '{"memoryEnabled":true}'), 'Refused uncontrolled IPC request');
    const r = await page.evaluate(async ({ route, method, body }) => { const r = await window.cortex.request({ url: `cortex://local${route}`, method, headers: body === undefined ? [] : [['content-type', 'application/json']], body: body === undefined ? undefined : JSON.stringify(body) }); return { status: r.status, data: JSON.parse(r.body) }; }, { route, method, body });
    report.calls.push({ stage, route, method, status: r.status, ...(Array.isArray(r.data) ? { count: r.data.length } : {}) }); save(); assert(statuses.includes(r.status), `Unexpected IPC status: ${method} ${route}`); return r.data;
  };
  verifyEmpty = async () => { for (const r of lists) { const v = await call(r); assert(Array.isArray(v) && v.length === 0, `Expected empty ${r}`); } const c = await call('/api/connection'); assert(c.mode === 'local' && c.signedIn === false && Object.keys(c).length === 2, 'Expected local signed-out mode'); };
  await page.waitForFunction(() => window.cortex?.platform === 'darwin' && document.querySelector('.theme [aria-checked=true]')); await expect(page.locator('html')).toHaveAttribute('lang', 'en'); assert.equal(await page.evaluate(() => localStorage.getItem('cortex.pref.privacy.memory')), null);
  mark('fresh-profile'); await verifyEmpty(); const initialSettings = await call('/api/settings'); assert(initialSettings.memoryEnabled === true && Object.keys(initialSettings).length === 1, 'Expected fresh enabled setting'); report.initialSettings = initialSettings; fresh = true;
  await page.waitForFunction(() => document.documentElement.dataset.theme === (document.querySelector('.theme [aria-checked=true]')?.dataset.themeValue === 'system' ? matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light' : document.querySelector('.theme [aria-checked=true]')?.dataset.themeValue)); previous = await preference(); oldDark = appearance(); assert(['true', 'false'].includes(oldDark) && ['system', 'light', 'dark'].includes(previous.pref)); report.previous = { ...previous, nativeDark: oldDark, hash: initialHash };
  go = async hash => { assert(hash === initialHash || ['#/memory', '#/settings?section=privacy'].includes(hash)); await page.evaluate(hash => { history.pushState(null, '', hash); dispatchEvent(new Event('cortex-variant')); }, hash); await expect(page).toHaveURL(`cortex://app/index.html${hash}`); };
  const fixture = { name: 'Native memory Bot', persona: 'Use only the controlled notes.', model: { providerID: 'native-memory', modelID: 'unconfigured' }, mascot: { shape: 'pebble', color: 'meadow', eyes: 'round', mouth: 'smile', accessories: [] }, tools: {}, permission: [] };
  mark('controlled-note'); bot = await call('/api/bots', 'POST', fixture, [201]); assert(/^bot_[\w-]+$/.test(bot.id)); report.bot = bot; save(); assert.deepEqual(bot, { ...fixture, id: bot.id, memory: [], routines: [], time: bot.time }); assert(Number.isFinite(bot.time.created) && bot.time.created === bot.time.updated && Object.keys(bot.time).length === 2);
  note = await call(`/api/bots/${bot.id}/memory`, 'POST', { content: 'Keep the blue folder.' }, [201]); assert(/^mem_[\w-]+$/.test(note.id)); report.note = note; save(); assert.deepEqual(note, { id: note.id, botID: bot.id, content: 'Keep the blue folder.', time: note.time }); assert(Number.isFinite(note.time));
  const unchanged = async () => { assert.deepEqual(await call(`/api/bots/${bot.id}/memory`), [note]); assert.deepEqual(await call(`/api/bots/${bot.id}`), { ...bot, memory: [note] }); };
  changed = true; ssh('/usr/bin/osascript -e \'tell application "Cortex" to activate\' -e \'tell application "System Events" to tell process "Cortex" to set size of window 1 to {960,640}\'');
  await page.locator('.rail .theme [aria-checked=true]').focus(); await page.keyboard.press('Home'); await expect.poll(preference).toEqual({ stored: 'dark', pref: 'dark', theme: 'dark' }); await page.keyboard.press('ArrowLeft'); await expect.poll(async () => (await preference()).pref).toBe('system');
  const settle = async () => { await page.evaluate(() => document.fonts.ready); await page.waitForFunction(() => document.fonts.status === 'loaded' && document.getAnimations().filter(a => a.effect?.getTiming().iterations !== Infinity).every(a => a.playState === 'finished')); };
  const geometry = target => target.evaluate(el => {
    let l = 0, t = 0, r = innerWidth, b = innerHeight, opacity = 1;
    for (let n = el; n; n = n.parentElement) { const s = getComputedStyle(n), q = n.getBoundingClientRect(); opacity *= s.visibility === 'visible' && s.display !== 'none' ? +s.opacity : 0; if (/^(auto|scroll|hidden|clip)$/.test(s.overflowX)) { l = Math.max(l, q.left + n.clientLeft); r = Math.min(r, q.left + n.clientLeft + n.clientWidth); } if (/^(auto|scroll|hidden|clip)$/.test(s.overflowY)) { t = Math.max(t, q.top + n.clientTop); b = Math.min(b, q.top + n.clientTop + n.clientHeight); } }
    const q = el.getBoundingClientRect(), range = document.createRange(); range.selectNodeContents(el); const ink = [...range.getClientRects()].filter(x => x.width && x.height), box = x => [x.left, x.top, x.right, x.bottom], fits = x => x.width > 0 && x.height > 0 && x.left >= l - .5 && x.top >= t - .5 && x.right <= r + .5 && x.bottom <= b + .5;
    return { text: (el.getAttribute('aria-label') || el.textContent).slice(0, 500), bounds: box(q), clip: [l, t, r, b], ink: ink.map(box), opacity, visible: fits(q) && opacity === 1 && (el.matches('[role=switch][aria-label],button[aria-label]') || ink.length > 0 && ink.every(fits)), hit: el.contains(document.elementFromPoint(q.x + q.width / 2, q.y + q.height / 2)) };
  });
  const verifyState = async (control, value) => { await expect(control).toHaveAttribute('aria-checked', String(value)); await expect(control).toBeEnabled(); assert.deepEqual(await call('/api/settings'), { memoryEnabled: value }); await unchanged(); report.checks.push({ stage, memoryEnabled: value, notesAndBotUnchanged: true }); save(); };
  const capture = async (label, theme, targets, focus) => {
    mark(`${theme}:${label}:capture`); assert.equal(targets.length, 5); await targets[0].hover(); await expect(page.locator('.toast, .tip')).toHaveCount(0); await settle(); await expect(focus).toBeFocused(); assert(await focus.evaluate(el => el.matches(':focus-visible')));
    await expect(page.locator('.window')).toHaveAttribute('data-sidebar', 'shown'); await expect(page.locator('html')).toHaveAttribute('data-theme', theme); assert.deepEqual(await page.evaluate(() => [innerWidth, innerHeight, matchMedia('(prefers-color-scheme: dark)').matches]), [960, 640, theme === 'dark']);
    const measure = async () => { const rows = []; for (const target of targets) { await expect(target).toBeVisible(); const g = await geometry(target); rows.push(g); if (!g.visible || !g.hit) { report.failedGeometry = rows; save(); assert.fail('Target clipped or covered'); } } return rows; };
    const boxes = await measure(), win = nativeWindow(theme), focusStyle = await focus.evaluate(el => { const s = getComputedStyle(el); return { name: el.getAttribute('aria-label'), visible: el.matches(':focus-visible'), outline: s.outline, boxShadow: s.boxShadow }; }); await pidCheck(); assert(report.capturesRequested < 4);
    const shot = { file: `${label}-${theme}.png`, requestedAt: new Date().toISOString(), theme, native: true, ...win, boxes, focus: focusStyle, status: 'requested' }; report.capturesRequested++; report.captures.push(shot); save();
    const response = await fetch(`http://127.0.0.1:19445/${win.id}`, { method: 'POST', signal: AbortSignal.timeout(15000) }); shot.httpStatus = response.status; save(); assert(response.ok); const bytes = Buffer.from(await response.arrayBuffer()); fs.writeFileSync(path.join(out, shot.file), bytes, { flag: 'wx' }); Object.assign(shot, { bytes: bytes.length, sha256: sha(bytes), status: 'original-retained' }); save();
    assert(bytes.length <= report.budget.originalBytes && report.captures.reduce((n, c) => n + (c.bytes ?? 0), 0) <= report.budget.totalBytes); assert(bytes.length >= 24 && bytes.subarray(0, 8).equals(Buffer.from('89504e470d0a1a0a', 'hex'))); shot.pixels = [bytes.readUInt32BE(16), bytes.readUInt32BE(20)]; assert(shot.pixels[0] >= 960 && shot.pixels[0] / 960 === shot.pixels[1] / 640);
    await measure(); await expect(focus).toBeFocused(); await expect(page.locator('html')).toHaveAttribute('data-theme', theme); assert.deepEqual(nativeWindow(theme), win); shot.finishedAt = new Date().toISOString(); shot.status = 'passed'; save(); mark(`${theme}:${label}:retained`);
  };
  const memory = page.locator('main').getByRole('switch', { name: 'Turn on memory', exact: true }), privacy = page.locator('main').getByRole('switch', { name: 'Memory', exact: true }), forget = page.locator('main').getByRole('button', { name: 'Forget', exact: true });
  for (const theme of ['light', 'dark']) {
    mark(`${theme}:memory`); setAppearance(theme === 'dark'); await expect.poll(preference).toEqual({ stored: 'system', pref: 'system', theme }); await go('#/memory'); await expect(page.locator('main .systeme-mem > .systeme-grow')).toContainText(note.content);
    if (theme === 'light') { await verifyState(memory, true); settingsTouched = true; await memory.click(); } await verifyState(memory, false);
    for (const value of [true, false]) { settingsTouched = true; await memory.press('Space'); await verifyState(memory, value); }
    await expect(page.locator('.systeme-memoff b')).toHaveText('Memory turned off'); await expect(page.locator('.systeme-memoff .systeme-grow > span')).toHaveText('Saved notes stay on this device. Bots stop using them in future turns; previous messages are unchanged.'); await expect(page.locator('main .banner.warn .grow')).toHaveText('Saved notes remain available to review, export or delete.');
    await capture('memory-off', theme, [page.locator('.systeme-memoff b'), page.locator('.systeme-memoff .systeme-grow > span'), memory, page.locator('main .banner.warn .grow'), page.locator('main .systeme-mem > .systeme-grow')], memory);
    mark(`${theme}:privacy`); await go('#/settings?section=privacy'); await expect(page.getByTestId('settings-nav-privacy')).toHaveAttribute('aria-current', 'true'); await verifyState(privacy, false);
    for (const value of [true, false]) { await privacy.press('Space'); await verifyState(privacy, value); }
    const row = page.locator('main .pg-panel .li').filter({ has: page.getByRole('switch', { name: 'Memory', exact: true }) }); await expect(row.locator('.sub')).toHaveText('Allow Bots to use their saved notes in future turns.');
    await capture('privacy-off', theme, [page.locator('main .pg-panel .page-title'), page.getByTestId('settings-nav-privacy'), row.locator('.ttl'), row.locator('.sub'), privacy], privacy);
    mark(`${theme}:paused-manual-access`); await go('#/memory'); await verifyState(memory, false); await memory.press('Tab'); await expect(forget).toBeFocused(); await expect(forget).toBeEnabled(); await forget.hover(); await settle(); const g = await geometry(forget); assert(g.visible && g.hit && await forget.evaluate(el => el.matches(':focus-visible'))); report.checks.push({ stage, forgetKeyboardFocusAndPointerHit: true, geometry: g }); save();
    if (theme === 'dark') { await forget.press('Enter'); await expect(page.locator('main .systeme-mem')).toHaveCount(0); assert.deepEqual(await call(`/api/bots/${bot.id}/memory`), []); assert.deepEqual(await call(`/api/bots/${bot.id}`), bot); assert.deepEqual(await call('/api/settings'), { memoryEnabled: false }); report.pausedForgetAccepted = true; save(); }
  }
  assert.equal(report.capturesRequested, 4); assert.equal(report.captures.filter(c => c.status === 'passed').length, 4); mark('flow-complete'); report.status = 'passed';
} catch (e) { report.status = 'failed'; report.failure = { stage, diagnostic: diagnostic(e) }; }
finally {
  cleanupPhase = true; const clean = async (name, fn) => { try { await fn(); report.cleanup[name] = true; } catch (e) { report.status = 'failed'; report.cleanup[name] = { diagnostic: diagnostic(e) }; } save(); };
  if (fresh && settingsTouched) await clean('settingsValueRestored', async () => { assert.deepEqual(await call('/api/settings', 'PUT', { memoryEnabled: true }), report.initialSettings); assert.deepEqual(await call('/api/settings'), report.initialSettings); report.settingsDocumentRetained = true; });
  if (bot?.id && /^bot_[\w-]+$/.test(bot.id)) await clean('ownedBotRemoved', () => call(`/api/bots/${bot.id}`, 'DELETE', undefined, [200, 404]));
  if (changed) await clean('nativeAppearanceRestored', async () => setAppearance(oldDark === 'true'));
  if (changed && previous) await clean('themePreferenceRestored', async () => { await page.evaluate(pref => dispatchEvent(new CustomEvent('cortex-theme', { detail: pref })), previous.pref); await expect.poll(async () => { const { stored: _stored, ...v } = await preference(); return v; }).toEqual({ pref: previous.pref, theme: previous.theme }); await page.evaluate(stored => { if (stored === null) localStorage.removeItem('cortex.theme'); else localStorage.setItem('cortex.theme', stored); }, previous.stored); });
  if (go && initialHash !== undefined) await clean('routeRestored', async () => { await go(initialHash); if (previous) await expect.poll(preference).toEqual(previous); });
  if (fresh && verifyEmpty) await clean('controlledListsEmpty', verifyEmpty);
  if (report.backend) await clean('zeroInference', async () => receipt());
  if (report.installedBefore) await clean('installedAfter', async () => { report.installedAfter = installed(); assert.deepEqual(report.installedAfter, report.installedBefore); });
  if (report.errors.length) report.status = 'failed'; report.finishedAt = new Date().toISOString(); report.durationMs = Date.parse(report.finishedAt) - Date.parse(report.startedAt); report.scope = 'Four native English Memory/Privacy off-state images, UI switch synchronization, one controlled Bot/note, paused manual Forget. No inference, persistence restart, legacy migration, preview isolation, refusal/race or full-product acceptance. Settings value restored; isolated settings document retained.'; save();
}
console.log(`Memory native: ${report.status}; ${stage}; ${path.join(out, 'manifest.json')}`); process.exit(report.status === 'passed' ? 0 : 1);
