import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';

const { chromium } = await import(path.join(process.cwd(), 'node_modules/playwright/index.mjs'));
const [out] = process.argv.slice(2);
assert(out);
fs.mkdirSync(out, { recursive: true });
const browser = await chromium.connectOverCDP('http://127.0.0.1:19444');
const page = browser.contexts()[0].pages().find(p => p.url().startsWith('cortex://app/'));
assert(page);
const ssh = command => execFileSync('ssh', ['-o', 'BatchMode=yes', 'mac-live', command], { encoding: 'utf8' }).trim();
const wid = ssh(`swift -e 'import CoreGraphics; for w in CGWindowListCopyWindowInfo([.optionOnScreenOnly], kCGNullWindowID) as! [[String: Any]] where w["kCGWindowOwnerName"] as? String == "Cortex" && w["kCGWindowLayer"] as? Int == 0 { print(w["kCGWindowNumber"] as! Int); break }' 2>/dev/null`);
assert(/^\d+$/.test(wid));
const errors = [];
page.on('pageerror', e => errors.push(e.message));
const call = (url, method = 'GET', body) => page.evaluate(async ({ url, method, body }) => {
  const r = await window.__bridgeFetch(`cortex://local${url}`, { method, headers: { 'content-type': 'application/json' }, body: body === undefined ? undefined : JSON.stringify(body) });
  if (!r.ok) throw new Error(`Native test setup failed: ${r.status}`);
  return r.status === 204 ? null : r.json();
}, { url, method, body });
const show = async hash => {
  await page.goto(`cortex://app/index.html#/${hash}`);
  await page.waitForFunction(() => document.querySelector('main.content')?.textContent.trim());
  await page.evaluate(() => document.fonts.ready);
};
await show('home');
await page.evaluate(() => localStorage.setItem('cortex.locale', 'en'));
await page.reload();
await page.emulateMedia({ reducedMotion: 'reduce' });
ssh('osascript -e \'tell application "System Events" to tell process "Cortex" to set size of window 1 to {960, 640}\'');
await page.waitForFunction(() => innerWidth === 960 && innerHeight === 640);
await call('/api/providers/fake/key', 'PUT', { key: 'sk-test-native-admission' });
const captures = [];
for (const theme of ['light', 'dark']) {
  ssh(`osascript -e 'tell application "System Events" to tell appearance preferences to set dark mode to ${theme === 'dark'}'`);
  await show(`home?theme=${theme}`);
  const choose = async name => {
    await page.getByTestId('model-trigger').click();
    await page.getByTestId('model-option').filter({ hasText: name }).click();
  };
  await choose('Reasoner Large');
  await page.getByTestId('attach-input').setInputFiles({ name: 'dot.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==', 'base64') });
  await page.getByTestId('composer-input').fill('Read the attached image');
  await page.getByTestId('composer-send').click();
  await page.getByTestId('assistant-text').first().waitFor();
  await page.getByTestId('composer-send').waitFor();
  const id = new URLSearchParams(page.url().split('?')[1]).get('id');
  assert(id);
  const before = await call(`/api/sessions/${id}/messages`);
  assert.equal(before.length, 2);
  assert(before[1].info.time.completed !== undefined && !before[1].info.error);
  assert(before[0].parts.some(p => p.type === 'file' && p.mime === 'image/png'));
  await choose('Plain Text');
  const draft = 'Follow up on the earlier image';
  await page.getByTestId('composer-input').fill(draft);
  const time = Date.now();
  await page.clock.install({ time });
  await page.clock.pauseAt(time + 1000);
  await page.getByTestId('composer-send').click();
  await page.getByText('This model can’t read images.', { exact: true }).first().waitFor();
  assert.equal(await page.getByTestId('composer-input').inputValue(), draft);
  assert.equal(await page.locator('.chat-att-img').count(), 0);
  assert.deepEqual(await call(`/api/sessions/${id}/messages`), before);
  assert.equal((await call(`/api/sessions/${id}`)).model.modelID, 'reasoner');
  for (const control of [page.getByTestId('composer-input'), page.getByTestId('model-trigger'), page.getByTestId('composer-send')]) await control.click({ trial: true, timeout: 1500 });
  assert.equal(await page.locator('html').getAttribute('data-theme'), theme);
  const name = `history-image-refusal-${theme}`;
  const res = await fetch(`http://127.0.0.1:19445/${wid}`, { method: 'POST' });
  assert(res.ok);
  fs.writeFileSync(path.join(out, `${name}.png`), Buffer.from(await res.arrayBuffer()));
  captures.push({ name, theme, width: 960, height: 640, url: page.url(), messageCount: before.length, draftRetained: true, historyUnchanged: true, sessionModelUnchanged: true, controlsReachable: true, toastClockPaused: true });
  await page.getByTestId('model-trigger').click();
  await page.clock.runFor(100);
  await page.getByTestId('model-option').filter({ hasText: 'Reasoner Large' }).click();
  await page.clock.runFor(100);
  assert.equal(await page.getByTestId('composer-input').inputValue(), draft);
  await page.clock.resume();
  await page.getByTestId('composer-send').click();
  await page.waitForFunction(async id => {
    const msgs = await (await window.__bridgeFetch(`cortex://local/api/sessions/${id}/messages`)).json();
    return msgs.length === 4 && msgs.at(-1).info.time.completed !== undefined;
  }, id);
  assert.equal(await page.getByTestId('composer-input').inputValue(), '');
  captures.at(-1).recoveryAccepted = true;
}
assert.deepEqual(errors, []);
fs.writeFileSync(path.join(out, 'manifest.json'), JSON.stringify({ appSha256: ssh('shasum -a 256 /Applications/Cortex.app/Contents/Resources/app.asar').split(/\s/)[0], nativeWindowID: Number(wid), captures, errors }, null, 2) + '\n');
await browser.close();
console.log(`Verified ${captures.length} native history-capability refusals and recoveries`);
