// Prepared, unexecuted. Coordinator owns package admission, Mac lease and native pixel acceptance.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { pathToFileURL } from 'node:url';
import { protocol } from './terminal-state-native-backend.mjs';
const [outArg, root, expectedAsar, revision, membersArg] = process.argv.slice(2);
assert(process.argv.length === 7 && outArg && path.isAbsolute(outArg) && /^\/(?:private\/)?tmp\/opencode\/desktop-terminal-state-projects-[\w.-]+$/.test(root ?? '') && /^[a-f0-9]{64}$/.test(expectedAsar ?? '') && /^[a-f0-9]{40}$/.test(revision ?? '') && membersArg && path.isAbsolute(membersArg), 'Usage: node projects-native.mjs <fresh-output> <fresh-mac-root> <asar-sha256> <revision> <members.json>');
const out = path.resolve(outArg), repo = fs.realpathSync(process.cwd()), sha = value => createHash('sha256').update(value).digest('hex');
assert(!fs.existsSync(out) && out !== repo && !out.startsWith(`${repo}/`)); fs.mkdirSync(out, { recursive: true });
const originals = { 'terminal-state-native-backend.mjs': 'd22fcbe2287a7898452778ea58d665f0742f4a1d4d580ec7c237dc10cfc70d4d', 'launch-terminal-state-native.py': '4aec6651e6178bf890a299551497514f5159342a8f94db8972515c000fc10257', 'cleanup-terminal-state-native.py': 'c46f218f17bcda2ba031fe8f2959f9f8e18dda379a7edcd076b01be0c881c08a' };
const report = { status: 'running', revision, expectedAsar, startedAt: new Date().toISOString(), invocation: { execPath: process.execPath, nodeVersion: process.version, argv: process.argv.slice(1), cwd: repo }, budget: { captureRequests: 4, bytesPerOriginal: 8388608, originalBytesTotal: 33554432, flowMs: 120000 }, captureRequests: 0, captures: [], themes: [], stateCalls: [], pageErrors: [], consoleErrors: [], rendererHttp: [], unexpectedDialogs: 0, cleanup: {} };
const save = () => fs.writeFileSync(path.join(out, 'manifest.json'), JSON.stringify(report, null, 2) + '\n');
const diagnostic = e => String(e?.stack ?? e?.message ?? e).replace(/\bBearer\s+[^\s"'`,]+/gi, 'Bearer [redacted]').replace(/https?:\/\/[^\s"'<>]+/g, '[network-url]');
const quote = value => `'${value.replaceAll("'", "'\\''")}'`;
const ssh = command => execFileSync('ssh', ['-o', 'BatchMode=yes', '-o', 'ConnectTimeout=10', 'mac-live', command], { encoding: 'utf8', timeout: 30000, maxBuffer: 4 * 1024 * 1024, stdio: ['pipe', 'pipe', 'pipe'] }).trim();
const appearance = () => ssh(`/usr/bin/osascript -e 'tell application "System Events" to tell appearance preferences to get dark mode'`);
const setAppearance = dark => { ssh(`/usr/bin/osascript -e 'tell application "System Events" to tell appearance preferences to set dark mode to ${dark}'`); assert.equal(appearance(), String(dark)); };
const backend = endpoint => JSON.parse(ssh(`/usr/bin/curl --fail --silent --show-error --max-time 5 http://127.0.0.1:9456/${endpoint}`));
const receipt = () => { const r = backend('receipt'); assert.equal(r.runID, report.backend.runID); assert.equal(r.counts.errors, 0); assert.deepEqual(r.failures, []); assert.deepEqual(r.requests, []); report.backendReceipt = r; };
const installed = () => { const r = JSON.parse(ssh(`/usr/bin/python3 ${quote(`${root}/launch-terminal-state-native.py`)} --inspect ${quote(root)} ${expectedAsar} ${revision}`)); assert.equal(r.membersSHA256, report.membersSHA256); assert.equal(r.membersVerified, report.memberCount); assert.equal(r.inspectorSHA256, originals['launch-terminal-state-native.py']); return r; };
const swift = 'import Foundation; import AppKit; import CoreGraphics; let all = CGWindowListCopyWindowInfo([.optionOnScreenOnly], kCGNullWindowID) as! [[String: Any]]; let rows = all.filter { $0["kCGWindowOwnerName"] as? String == "Cortex" && $0["kCGWindowLayer"] as? Int == 0 }.map { w in ["id": w["kCGWindowNumber"]!, "pid": w["kCGWindowOwnerPID"]!, "bounds": w["kCGWindowBounds"]!, "active": NSWorkspace.shared.frontmostApplication?.processIdentifier == (w["kCGWindowOwnerPID"] as! Int32)] as [String: Any] }; print(String(data: try! JSONSerialization.data(withJSONObject: rows), encoding: .utf8)!)';
const nativeWindow = () => { const rows = JSON.parse(ssh(`/usr/bin/swift -e ${quote(swift)}`)); assert.equal(rows.length, 1); const w = rows[0]; assert(w.active && w.pid === report.installedBefore.pid && w.bounds.Width === 960 && w.bounds.Height === 640); if (report.captures[0]?.id) assert.equal(w.id, report.captures[0].id); return w; };
let page, expect, call, emptyEngine, previous, oldAppearance, initialURL, fresh = false, changed = false, stage = 'preflight';
const mark = next => { stage = next; report.stage = next; save(); assert(Date.now() - Date.parse(report.startedAt) < report.budget.flowMs, 'Native flow exceeded its 120-second budget'); };
save();
try {
  report.helperHashes = Object.fromEntries(['projects-native.mjs', ...Object.keys(originals)].map(name => [name, sha(fs.readFileSync(new URL(name, import.meta.url)))]));
  for (const [name, hash] of Object.entries(originals)) assert.equal(report.helperHashes[name], hash);
  const pins = fs.readFileSync(membersArg), members = JSON.parse(pins); assert.equal(members.revision, revision); assert(Array.isArray(members.members) && members.members.length >= 4);
  assert(members.members.every(r => /^(packages\/app\/dist\/|packages\/desktop\/dist\/)/.test(r.path) && /^[a-f0-9]{64}$/.test(r.sha256))); assert.equal(new Set(members.members.map(r => r.path)).size, members.members.length); report.membersSHA256 = sha(pins); report.memberCount = members.members.length;
  mark('identity'); report.installedBefore = installed();
  const hashSource = 'import hashlib,json,pathlib,sys; r=pathlib.Path(sys.argv[1]); print(json.dumps({n:hashlib.sha256((r/n).read_bytes()).hexdigest() for n in sys.argv[2:]}))';
  report.rootHelperHashes = JSON.parse(ssh(`/usr/bin/python3 -c ${quote(hashSource)} ${quote(root)} ${Object.keys(originals).map(quote).join(' ')}`)); assert.deepEqual(report.rootHelperHashes, originals);
  report.backend = backend('health'); assert.equal(report.backend.protocol, protocol); assert.equal(report.backend.platform, 'darwin'); assert.equal(report.backend.port, 9456); assert.equal(report.backend.root, report.installedBefore.root); assert.equal(report.backend.scriptSHA256, originals['terminal-state-native-backend.mjs']); receipt(); save();
  const modules = [path.join(repo, 'node_modules'), '/tmp/opencode/node_modules'].find(d => fs.existsSync(path.join(d, 'playwright/index.mjs')) && fs.existsSync(path.join(d, '@playwright/test/index.mjs'))); assert(modules);
  const { chromium } = await import(pathToFileURL(path.join(modules, 'playwright/index.mjs')).href); ({ expect } = await import(pathToFileURL(path.join(modules, '@playwright/test/index.mjs')).href)); expect = expect.configure({ timeout: 10000 });
  const browser = await chromium.connectOverCDP('http://127.0.0.1:19444', { timeout: 10000 }), cdp = await browser.newBrowserCDPSession();
  const identity = async () => { const mains = (await cdp.send('SystemInfo.getProcessInfo')).processInfo.filter(p => p.type === 'browser'); assert.equal(mains.length, 1); assert.equal(mains[0].id, report.installedBefore.pid); const r = installed(); assert.deepEqual(r, report.installedBefore); return r; };
  await identity(); const pages = browser.contexts().flatMap(c => c.pages()).filter(p => p.url().startsWith('cortex://app/')); assert.equal(pages.length, 1); [page] = pages; page.setDefaultTimeout(10000); page.setDefaultNavigationTimeout(10000); initialURL = page.url();
  await page.emulateMedia({ colorScheme: null, reducedMotion: null, forcedColors: null, contrast: null }); // Release CDP defaults; actual OS preferences drive media queries.
  const watch = target => { target.on('pageerror', e => report.pageErrors.push(diagnostic(e))); target.on('console', m => { if (m.type() === 'error') report.consoleErrors.push(diagnostic(m.text())); }); target.on('dialog', async d => { report.unexpectedDialogs++; await d.dismiss().catch(() => {}); }); };
  for (const context of browser.contexts()) { context.pages().forEach(watch); context.on('page', watch); context.on('request', r => { if (/^https?:/.test(r.url())) report.rendererHttp.push(sha(r.url())); }); }
  call = async (route, method = 'GET', body, expected = 200) => {
    assert(method === 'GET' || fresh && (method === 'POST' && route === '/api/sessions' || method === 'DELETE' && report.themes.some(r => r.projectID && route === `/api/projects/${r.projectID}` || r.sessionID && route === `/api/sessions/${r.sessionID}`)), 'Only controlled session creation and exact-owned-ID cleanup are allowed');
    const r = await page.evaluate(async ({ route, method, body }) => { const v = await window.cortex.request({ url: `cortex://local${route}`, method, headers: body === undefined ? [] : [['content-type', 'application/json']], body: body === undefined ? undefined : JSON.stringify(body) }); let data; try { data = JSON.parse(v.body); } catch { throw new Error('Invalid IPC JSON'); } return { status: v.status, data }; }, { route, method, body });
    report.stateCalls.push({ stage, route, method, status: r.status, ...(Array.isArray(r.data) ? { count: r.data.length } : {}) }); save(); assert([expected].flat().includes(r.status), `Unexpected IPC status ${r.status}: ${method} ${route}`); return r.status === 404 ? null : r.data;
  };
  emptyEngine = async () => { for (const route of ['/api/projects', '/api/sessions', '/api/bots', '/api/tasks', '/api/providers', '/api/plugins', '/api/permissions']) { const rows = await call(route); assert(Array.isArray(rows) && rows.length === 0, `${route} must be empty`); } const c = await call('/api/connection'); assert(c.mode === 'local' && c.signedIn === false && Object.keys(c).length === 2, 'Expected local signed-out connection'); };
  await page.waitForFunction(() => window.cortex?.platform === 'darwin' && document.querySelector('.theme [aria-checked=true]')); await expect(page.locator('html')).toHaveAttribute('lang', 'en'); mark('fresh-engine'); await emptyEngine(); fresh = true;
  const preference = () => page.evaluate(() => ({ stored: localStorage.getItem('cortex.theme'), theme: document.documentElement.dataset.theme, pref: document.querySelector('.theme [aria-checked=true]')?.dataset.themeValue }));
  await page.waitForFunction(() => { const pref = document.querySelector('.theme [aria-checked=true]')?.dataset.themeValue; return document.documentElement.dataset.theme === (pref === 'system' ? matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light' : pref); });
  previous = await preference(); assert(['system', 'light', 'dark'].includes(previous.pref)); report.previousPreference = previous; oldAppearance = appearance(); assert(['true', 'false'].includes(oldAppearance)); report.previousNativeDark = oldAppearance; report.initialURL = initialURL;
  changed = true; setAppearance(false); ssh(`/usr/bin/osascript -e 'tell application "Cortex" to activate' -e 'tell application "System Events" to tell process "Cortex" to set size of window 1 to {960,640}'`);
  await page.goto('cortex://app/index.html#/projects'); const rail = page.locator('.rail .theme'); await rail.locator('[aria-checked=true]').focus(); await page.keyboard.press('Home'); await expect.poll(preference).toEqual({ stored: 'dark', pref: 'dark', theme: 'dark' }); await expect(rail.getByRole('radio', { name: 'Dark', exact: true })).toBeFocused(); await page.keyboard.press('ArrowLeft');
  const settle = async () => { await page.evaluate(() => document.fonts.ready); await page.waitForFunction(() => document.fonts.status === 'loaded' && document.getAnimations().filter(a => a.effect?.getTiming().iterations !== Infinity).every(a => a.playState === 'finished')); };
  const widths = locator => locator.evaluateAll(elements => elements.map(el => { const r = el.getBoundingClientRect(); return { tag: el.tagName, className: el.className, width: el.clientWidth, contentWidth: el.scrollWidth, left: r.left, right: r.right, fits: el.clientWidth > 0 && el.scrollWidth <= el.clientWidth + 1 && r.left >= 0 && r.right <= innerWidth }; }));
  const geometry = locator => locator.evaluate(el => {
    const field = el instanceof HTMLInputElement || el instanceof HTMLTextAreaElement; let left = 0, top = 0, right = innerWidth, bottom = innerHeight, opacity = 1;
    for (let n = el; n; n = n.parentElement) { const s = getComputedStyle(n), b = n.getBoundingClientRect(); opacity *= s.visibility === 'visible' && s.display !== 'none' ? Number(s.opacity) : 0; if ((n !== el || !field) && /^(auto|scroll|hidden|clip)$/.test(s.overflowX)) { left = Math.max(left, b.left + n.clientLeft); right = Math.min(right, b.left + n.clientLeft + n.clientWidth); } if ((n !== el || !field) && /^(auto|scroll|hidden|clip)$/.test(s.overflowY)) { top = Math.max(top, b.top + n.clientTop); bottom = Math.min(bottom, b.top + n.clientTop + n.clientHeight); } }
    const box = b => [b.left, b.top, b.right, b.bottom], inside = b => b.width > 0 && b.height > 0 && b.left >= left - .5 && b.top >= top - .5 && b.right <= right + .5 && b.bottom <= bottom + .5;
    const b = el.getBoundingClientRect(), range = document.createRange(); range.selectNodeContents(el); const ink = [...range.getClientRects()].filter(r => r.width && r.height), fieldFits = !field || el.scrollWidth <= el.clientWidth + 1 && el.scrollHeight <= el.clientHeight + 1;
    return { text: field ? el.value : el.textContent, tag: el.tagName, bounds: box(b), clip: [left, top, right, bottom], ink: ink.map(box), opacity, fieldFits, visible: inside(b) && opacity === 1 && fieldFits && (field || el.matches('button[aria-label]') || ink.length > 0 && ink.every(inside)), hit: el.contains(document.elementFromPoint(b.x + b.width / 2, b.y + b.height / 2)) };
  });
  const capture = async (label, theme, targets, focused) => {
    mark(`${theme}:${label}:capture`); assert.equal(targets.length, 14); await targets[0].hover(); await expect(page.locator('.toast, .tip')).toHaveCount(0); await settle(); await expect(focused).toBeFocused();
    await expect(page.locator('html')).toHaveAttribute('data-theme', theme); await expect(page.locator('.window')).toHaveAttribute('data-sidebar', 'shown'); assert.deepEqual(await page.evaluate(() => [innerWidth, innerHeight]), [960, 640]); assert.equal(await page.evaluate(() => matchMedia('(prefers-color-scheme: dark)').matches), theme === 'dark');
    const measure = async () => { const boxes = []; for (const target of targets) { await expect(target).toBeVisible(); const b = await geometry(target); boxes.push(b); if (!b.visible || !b.hit) { report.failedGeometry = { stage, boxes }; save(); assert.fail(`Target ${boxes.length} clipped or covered`); } } return boxes; };
    const boxes = await measure(), focus = await focused.evaluate(el => { const s = getComputedStyle(el); return { name: el.getAttribute('aria-label') || el.textContent.trim(), visible: el.matches(':focus-visible'), outlineStyle: s.outlineStyle, outlineWidth: s.outlineWidth, outlineColor: s.outlineColor, boxShadow: s.boxShadow }; }); assert(focus.visible);
    await identity(); const win = nativeWindow(); assert.equal(appearance(), String(theme === 'dark')); assert(report.captureRequests < report.budget.captureRequests); report.captureRequests++; const shot = { file: `${label}-${theme}.png`, theme, native: true, ...win, viewport: [960, 640], boxes, focus, status: 'requested' }; report.captures.push(shot); save();
    const response = await fetch(`http://127.0.0.1:19445/${win.id}`, { method: 'POST', signal: AbortSignal.timeout(15000) }); shot.httpStatus = response.status; assert(response.ok); const bytes = Buffer.from(await response.arrayBuffer()); fs.writeFileSync(path.join(out, shot.file), bytes, { flag: 'wx' }); Object.assign(shot, { bytes: bytes.length, sha256: sha(bytes), status: 'original-retained' }); save();
    assert(bytes.length <= report.budget.bytesPerOriginal && report.captures.reduce((n, r) => n + (r.bytes ?? 0), 0) <= report.budget.originalBytesTotal); assert(bytes.subarray(0, 8).equals(Buffer.from('89504e470d0a1a0a', 'hex'))); shot.pixels = [bytes.readUInt32BE(16), bytes.readUInt32BE(20)]; assert(shot.pixels[0] >= 960 && shot.pixels[0] / 960 === shot.pixels[1] / 640);
    await measure(); await expect(focused).toBeFocused(); assert.deepEqual(nativeWindow(), win); assert.equal(appearance(), String(theme === 'dark')); receipt(); shot.status = 'passed'; save();
  };
  for (const theme of ['light', 'dark']) {
    mark(`${theme}:create-form`); setAppearance(theme === 'dark'); await expect.poll(preference).toEqual({ stored: 'system', pref: 'system', theme }); await expect(page.getByRole('heading', { name: 'No projects yet', exact: true })).toBeVisible();
    const name = `Native ${theme} project`, instructions = `Use ${theme} project notes.`, edited = `Use revised ${theme} project notes.`, title = `Native ${theme} chat`, colorName = theme === 'light' ? 'Orange' : 'Teal', color = theme === 'light' ? '#FF6A13' : '#12B8A0';
    const longName = 'W'.repeat(48), longInstructions = 'W'.repeat(4000);
    const row = { theme, expected: { name, instructions, icon: 'rocket', color }, editedInstructions: edited, title }; report.themes.push(row); save();
    await page.locator('.sidebar').getByRole('button', { name: 'New project', exact: true }).click(); const dialog = page.getByRole('dialog', { name: 'New project', exact: true }), input = dialog.getByRole('textbox', { name: 'Name', exact: true }), notes = dialog.getByRole('textbox', { name: 'Instructions', exact: true });
    mark(`${theme}:long-create-form`); await input.fill(longName); await notes.fill(longInstructions); await settle(); const enteredName = await input.inputValue(), enteredNotes = await notes.inputValue();
    row.longInputChecks = { creation: { widths: await widths(dialog.locator('.systeme-preview, .systeme-preview > span:last-child')), nameLength: enteredName.length, instructionsLength: enteredNotes.length, nameSHA256: sha(enteredName), instructionsSHA256: sha(enteredNotes), valuesUnchanged: enteredName === longName && enteredNotes === longInstructions } }; save();
    assert(row.longInputChecks.creation.valuesUnchanged, 'Maximum-length creation draft changed'); assert.equal(row.longInputChecks.creation.widths.length, 2); assert(row.longInputChecks.creation.widths.every(r => r.fits), 'Long creation preview overflows');
    await input.fill(name); await notes.fill(instructions); await expect(input).toHaveAttribute('maxlength', '48'); await expect(notes).toHaveAttribute('maxlength', '4000'); await expect(dialog.getByRole('radio', { name: 'Calendar', exact: true })).toHaveAttribute('aria-checked', 'true'); await expect(dialog.getByRole('radio', { name: 'Violet', exact: true })).toHaveAttribute('aria-checked', 'true');
    await dialog.getByRole('radio', { name: 'Calendar', exact: true }).focus(); await page.keyboard.press('ArrowLeft'); await expect(dialog.getByRole('radio', { name: 'Rocket', exact: true })).toBeFocused(); await dialog.getByRole('radio', { name: 'Violet', exact: true }).focus(); for (let n = 0; n < (theme === 'light' ? 3 : 2); n++) await page.keyboard.press('ArrowRight');
    await expect(dialog.getByRole('radio', { name: colorName, exact: true })).toHaveAttribute('aria-checked', 'true'); await expect(dialog.getByRole('radio', { name: 'Rocket', exact: true })).toHaveAttribute('aria-checked', 'true');
    row.radios = await dialog.locator('[role=radiogroup]').evaluateAll(groups => groups.map(g => ({ id: g.getAttribute('aria-labelledby'), roots: [...g.querySelectorAll('[role=radio]')].map(el => ({ name: el.getAttribute('aria-label'), checked: el.getAttribute('aria-checked'), tabIndex: el.tabIndex, tag: el.tagName })), inputs: [...g.querySelectorAll('input')].map(el => ({ type: el.type, hidden: el.getAttribute('aria-hidden'), tabIndex: el.tabIndex })) })));
    assert.deepEqual(row.radios.map(g => g.roots.length), [8, 6]); for (const g of row.radios) { assert.equal(g.roots.filter(r => r.checked === 'true').length, 1); assert.equal(g.roots.filter(r => r.tabIndex === 0).length, 1); assert(g.roots.every(r => r.tag === 'BUTTON' && r.tabIndex === (r.checked === 'true' ? 0 : -1))); assert.equal(g.inputs.length, g.roots.length); assert(g.inputs.every(r => r.type === 'radio' && r.hidden === 'true' && r.tabIndex === -1)); }
    const cancel = dialog.getByRole('button', { name: 'Cancel', exact: true }), create = dialog.getByRole('button', { name: 'Create project', exact: true }); await notes.focus(); await page.keyboard.press('Tab'); await expect(cancel).toBeFocused(); await page.keyboard.press('Tab'); await expect(create).toBeFocused();
    await capture('project-create', theme, [dialog.getByRole('heading'), dialog.locator('p'), dialog.locator('.systeme-preview b'), dialog.locator('label[for=systeme-pn]'), input, dialog.locator('#systeme-pi'), dialog.getByRole('radio', { name: 'Rocket', exact: true }), dialog.locator('#systeme-pc'), dialog.getByRole('radio', { name: colorName, exact: true }), dialog.locator('label[for=systeme-pins]'), notes, dialog.locator('.field .sub'), cancel, create], create);
    mark(`${theme}:create-accepted`); row.createSubmitted = true; save(); await create.click(); await expect(dialog).toHaveCount(0); await expect(page.locator('.systeme-phead h1')).toHaveText(name); const id = await page.evaluate(() => new URLSearchParams(location.hash.split('?')[1]).get('id')); assert(/^prj_[\w-]+$/.test(id)); row.projectID = id; save();
    const created = await call(`/api/projects/${id}`); assert.deepEqual({ name: created.name, instructions: created.instructions, icon: created.icon, color: created.color }, row.expected); assert.equal(created.id, id); row.created = created; save(); assert.deepEqual(await call('/api/projects'), [created]);
    mark(`${theme}:long-instructions-save`); await page.locator('.systeme-phead h1').hover(); await expect(page.locator('.toast')).toHaveCount(0); await page.getByRole('button', { name: 'Edit instructions', exact: true }).click(); const editor = page.getByRole('textbox', { name: 'Project instructions', exact: true }); await expect(editor).toHaveValue(instructions); await editor.fill(longInstructions); await page.locator('main').getByRole('button', { name: 'Save', exact: true }).click(); await expect(editor).toHaveCount(0);
    const longText = page.locator('main p.systeme-instr'); await expect(longText).toHaveCount(1); await expect.poll(() => longText.evaluate(el => ({ length: el.textContent.length, exact: el.textContent === 'W'.repeat(4000) }))).toEqual({ length: 4000, exact: true }); await expect(page.locator('.systeme-phead h1')).toHaveText(name); await settle();
    const longSaved = await call(`/api/projects/${id}`); row.longInputChecks.savedInstructions = { widths: await widths(page.locator('main, main .page, main p.systeme-instr')), renderedLength: await longText.evaluate(el => el.textContent.length), savedLength: longSaved.instructions.length, savedSHA256: sha(longSaved.instructions), valueUnchanged: longSaved.instructions === longInstructions }; save();
    assert(row.longInputChecks.savedInstructions.valueUnchanged, 'Maximum-length saved instructions changed'); assert.equal(row.longInputChecks.savedInstructions.widths.length, 3); assert(row.longInputChecks.savedInstructions.widths.every(r => r.fits), 'Long saved instructions overflow'); assert.deepEqual({ ...longSaved, instructions: created.instructions, time: created.time }, created); assert.equal(longSaved.time.created, created.time.created); assert(longSaved.time.updated >= created.time.updated);
    mark(`${theme}:instructions-save`); await page.locator('main').getByRole('button', { name: 'Edit', exact: true }).click(); assert(await editor.inputValue() === longInstructions, 'Saved long instructions did not reopen intact'); await editor.fill(edited); await page.locator('main').getByRole('button', { name: 'Save', exact: true }).click(); await expect(editor).toHaveCount(0); await expect(page.locator('main .systeme-instr')).toHaveText(edited);
    row.edited = await call(`/api/projects/${id}`); assert.deepEqual(row.edited, { ...created, instructions: edited, time: row.edited.time }); assert.equal(row.edited.time.created, created.time.created); assert(row.edited.time.updated >= created.time.updated); save();
    mark(`${theme}:keyless-chat-fixture`); const fixture = { kind: 'chat', agent: 'build', title, model: { providerID: 'native-project', modelID: 'reasoner' }, projectID: id }; row.sessionIntent = fixture; save(); const chat = await call('/api/sessions', 'POST', fixture, 201); assert(/^ses_[\w-]+$/.test(chat.id)); row.sessionID = chat.id; row.session = chat; save(); assert.deepEqual(chat, { ...fixture, id: chat.id, time: chat.time }); assert.deepEqual(await call(`/api/sessions/${chat.id}/messages`), []);
    const tabs = page.getByRole('tablist', { name: 'Project sections', exact: true }), overview = tabs.getByRole('tab', { name: 'Overview', exact: true }); await overview.click(); const tree = page.locator('.sidebar button.row').filter({ hasText: name }); await tree.click(); await expect(tree).toHaveAttribute('aria-expanded', 'true'); const children = page.locator(`[id="${await tree.getAttribute('aria-controls')}"]`), child = children.getByRole('button', { name: title, exact: true }), seeAll = children.getByRole('button', { name: 'See all', exact: true });
    mark(`${theme}:sidebar-exact-link`); await child.click(); await expect(page).toHaveURL(new RegExp(`#/chat\\?id=${chat.id}(?:&|$)`)); assert.deepEqual(await call(`/api/sessions/${chat.id}`), chat); await seeAll.click(); await expect(page).toHaveURL(new RegExp(`#/project\\?id=${id}(?:&|$)`)); await expect(page.locator('.systeme-phead h1')).toHaveText(name); await expect(page.locator('main .systeme-instr')).toHaveText(edited); await expect(page.locator('.systeme-phead .sub')).toHaveText('1 chat');
    const rootChat = page.locator('main .list').getByRole('button').filter({ hasText: title }); await expect(rootChat).toHaveCount(1); await expect(child).toBeVisible(); await expect(children).not.toHaveAttribute('inert', ''); await overview.focus(); await page.keyboard.press('ArrowRight'); await expect(tabs.getByRole('tab', { name: 'Files', exact: true })).toBeFocused(); await page.keyboard.press('ArrowLeft'); await expect(overview).toBeFocused(); await expect(overview).toHaveAttribute('aria-selected', 'true'); row.sidebarLinkVerified = true; save();
    await capture('project-overview', theme, [page.locator('.systeme-phead h1'), page.locator('.systeme-phead .sub'), page.locator('main').getByRole('button', { name: 'New chat', exact: true }), ...['Overview', 'Files', 'Instructions', 'Sharing'].map(name => tabs.getByRole('tab', { name, exact: true })), rootChat, page.locator('main .systeme-card h3'), page.locator('main .systeme-instr'), page.getByRole('button', { name: 'Edit instructions', exact: true }), tree, child, seeAll], overview);
    mark(`${theme}:delete-project-ui`); await page.locator('main .content-top').getByRole('button', { name: 'More actions', exact: true }).click(); await page.getByRole('menuitem', { name: 'Delete project', exact: true }).click(); await expect(page).toHaveURL(/#\/projects(?:\?|$)/); assert.deepEqual(await call('/api/projects'), []); assert.equal(await call(`/api/projects/${id}`, 'GET', undefined, 404), null); row.projectDeleted = true;
    const { projectID: _project, ...detached } = chat; row.detached = await call(`/api/sessions/${chat.id}`); assert.deepEqual(row.detached, detached); assert.deepEqual(await call(`/api/sessions/${chat.id}/messages`), []); row.emptyMessagesPreserved = true; save(); await call(`/api/sessions/${chat.id}`, 'DELETE'); row.sessionDeleted = true; await emptyEngine(); receipt(); save();
  }
  assert.equal(report.captureRequests, 4); assert.equal(report.captures.filter(r => r.status === 'passed').length, 4); report.installedAfter = await identity(); mark('flow-complete'); report.status = 'passed';
} catch (e) { report.status = 'failed'; report.failure = { stage, diagnostic: diagnostic(e) }; }
finally {
  const cleanup = async (name, fn) => { try { await fn(); report.cleanup[name] = true; } catch (e) { report.status = 'failed'; report.cleanup[name] = { diagnostic: diagnostic(e) }; } save(); };
  for (const row of report.themes) { if (row.projectID && !row.projectDeleted) await cleanup(`${row.theme}:ownedProjectRemoved`, () => call(`/api/projects/${row.projectID}`, 'DELETE', undefined, [200, 404])); if (row.sessionID && !row.sessionDeleted) await cleanup(`${row.theme}:ownedSessionRemoved`, () => call(`/api/sessions/${row.sessionID}`, 'DELETE', undefined, [200, 404])); }
  if (changed) await cleanup('appearanceRestored', async () => { setAppearance(oldAppearance === 'true'); });
  if (changed && page && previous) await cleanup('preferenceRestored', async () => { await page.evaluate(pref => dispatchEvent(new CustomEvent('cortex-theme', { detail: pref })), previous.pref); await expect.poll(() => page.evaluate(() => ({ theme: document.documentElement.dataset.theme, pref: document.querySelector('.theme [aria-checked=true]')?.dataset.themeValue }))).toEqual({ theme: previous.theme, pref: previous.pref }); await page.evaluate(stored => { if (stored === null) localStorage.removeItem('cortex.theme'); else localStorage.setItem('cortex.theme', stored); }, previous.stored); });
  if (changed && page && initialURL && previous) await cleanup('initialRouteRestored', async () => { await page.goto(initialURL); await expect.poll(() => page.evaluate(() => ({ stored: localStorage.getItem('cortex.theme'), theme: document.documentElement.dataset.theme, pref: document.querySelector('.theme [aria-checked=true]')?.dataset.themeValue }))).toEqual(previous); });
  if (fresh && emptyEngine) await cleanup('localEngineEmpty', emptyEngine);
  if (report.backend) await cleanup('zeroInference', async () => { receipt(); });
  if (report.pageErrors.length || report.consoleErrors.length || report.rendererHttp.length || report.unexpectedDialogs) { report.status = 'failed'; report.failure ??= { stage, diagnostic: 'Unexpected renderer error, HTTP request or dialog; inspect retained arrays' }; }
  report.finishedAt = new Date().toISOString(); report.durationMs = Date.parse(report.finishedAt) - Date.parse(report.startedAt); report.scope = 'Installed English Projects at 960x640 in actual OS light/dark: screenshot-free 48-character creation-name preview and 4000-character draft/saved-instructions checks, UI create/edit/delete, exact sidebar Chat link, keyless IPC-created root Chat, preserved empty messages/model/times on project deletion. Four original short-text window captures. No inference, process-restart, busy-refusal, pixel-reference or broader product acceptance.'; save();
}
console.log(`Projects native: ${report.status}; stage ${stage}; ${path.join(out, 'manifest.json')}`);
process.exit(report.status === 'passed' ? 0 : 1); // Coordinator owns app/helpers/tunnel/lease; no automatic rerun.
